\documentclass[a4paper,11pt, icelandic, english]{report}
\usepackage[T1]{fontenc}
\usepackage[english]{babel}
\usepackage{natbib}
\bibliographystyle{humanbio}
%\pdfmapline{=eufm10     eufm10     <eufm10.pfb}
\bibpunct{(}{)}{,}{a}{}{}

% Define margins of document
\sloppy
\usepackage{geometry}
\geometry{verbose,a4paper,tmargin=25mm,bmargin=35mm,lmargin=32mm,rmargin=32mm}
\usepackage{verbatim}
\usepackage{multicol,adjustbox,rotating}
\usepackage{setspace}
\singlespacing
\usepackage{dcolumn,arydshln}
%\usepackage[usenames]{color}
%\usepackage{graphicx,rotating,overpic}
%\usepackage{pstricks}
%\usepackage{pstricks,pst-node,pst-text,pst-3d}
\usepackage{amsfonts, amscd, amsmath, wrapfig,wasysym}
%\usepackage{graphpap}
%\usepackage{rjwmath}
%\usepackage{psfrag}
%\usepackage{longtable}
% For references like (See following page)
\usepackage{varioref}
% For symbols like celcius
%\usepackage{textcomp} %  ^o  \textdegree ; C^o \textcelsius
% Ams stuff
\usepackage{amsfonts, amscd, amsmath, wrapfig,wasysym}
% For thicker lines in tables
\usepackage{booktabs}
\usepackage{ulem}
%\usepackage{minipage}
\usepackage{tikz,makecell}
\usetikzlibrary{arrows,decorations.pathmorphing,decorations.footprints,
fadings,calc,trees,mindmap,shadows,decorations.text,patterns,positioning,shapes,matrix,fit,backgrounds}
\input{graphical_settings}


\usepackage{titlesec}
\addtocounter{chapter}{1}
\addtocounter{part}{2}

\makeatletter
\@addtoreset{section}{part}
\makeatother
\renewcommand{\thepart}{\arabic{part}}
\renewcommand*\thesection{\thepart.\thechapter.\arabic{section}}

% Different font size in captions
\usepackage{ccaption}
% \captionnamefont{\bf \footnotesize}
% \captiontitlefont{\footnotesize}
% \captionwidth{150mm}
% \changecaptionwidth
% \author{Bjarki {\TH}{\'o}r Elvarsson \\ \\ {\small Demersal Division} \\
% {\small Marine and Freshwater Research Institute, Reykjav\'ik, Iceland}\\ {\small (\texttt{bjarki.elvarsson@hafogvatn.is})}
% \\ \\ \textbf{\color{red}{Do not cite without authors permission}}}
% \title{\Large \textbf{A Gadget assessment of Ling in 5a}}
% %\\ {\Large \textbf{-Draft-}}

\usepackage[ bookmarks, colorlinks=true, citecolor=blue,
linkcolor=blue, pdftitle={}, pdfauthor={Bjarki Elvarsson}, pdfsubject={}, 
pdfkeywords={}]{hyperref}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%
%%%%            Begin DOCUMENT
%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
<<echo=FALSE,message=FALSE,warning=FALSE>>=
library(Rgadget)
library(tidyverse)
library(mfdb)
mdb <- mfdb('Iceland',db_params = list(host='hafgeimur.hafro.is'))
load('../11-age12plus/WGTS_v2/WGTS.Rdata')
fit <- out
fit$sidat <- 
  fit$sidat %>% 
  mutate(name=forcats::fct_reorder(name,lower))

load('../11-age12plus/retroFit.Rdata')
load('../11-age12plus/ling_adv_res.Rdata')
load('../11-age12plus/ling_adv_res0.Rdata')
load('../11-age12plus/ling_res_quick.Rdata')

load('bootfit.Rdata')
bootfit$sidat <- 
  bootfit$sidat %>% 
#  filter(!(model %in% c(59))) %>% 
  mutate(name=forcats::fct_reorder(name,lower))

#bootfit$params <- 
#  bootfit$params %>% 
#  filter(!(model %in% c(59))) 

ref.cm <- 75

SS <- read.gadget.lik.out('../11-age12plus/WGTS_v2/lik.final')

bootres <- 
  bootfit$res.by.year %>% 
  group_by(year,model) %>%
  summarise(total.biomass = sum(total.biomass),
            catch = sum(catch),
            #harv.biomass = sum(harv.biomass),
            recruitment = sum(recruitment,na.rm=TRUE)) %>% 
  left_join(bootfit$stock.full %>%
              filter(length>ref.cm) %>% 
              group_by(year,model) %>%
              summarise(harv.biomass=sum(number*mean.weight))) %>% 
  group_by(year) %>% 
  summarise(mtb=median(total.biomass),
            utb=quantile(total.biomass,0.95),
            ltb=quantile(total.biomass,0.05),
            uutb=quantile(total.biomass,0.75),
            lltb=quantile(total.biomass,0.25),
            cvtb=sd(total.biomass)/mean(total.biomass),
            mr=median(recruitment,na.rm=TRUE),
            ur=quantile(recruitment,na.rm=TRUE,0.95),
            lr=quantile(recruitment,na.rm=TRUE,0.05),
            uur=quantile(recruitment,na.rm=TRUE,0.75),
            llr=quantile(recruitment,na.rm=TRUE,0.25),
            cvr=sd(recruitment,na.rm=TRUE)/mean(recruitment,na.rm=TRUE),
            mhb=median(harv.biomass),
            uhb=quantile(harv.biomass,0.95),
            lhb=quantile(harv.biomass,0.05),
            uuhb=quantile(harv.biomass,0.75),
            llhb=quantile(harv.biomass,0.25),
            cvhb=sd(harv.biomass)/mean(harv.biomass),
            mhr=median(catch/harv.biomass),
            uhr=quantile(catch/harv.biomass,0.95),
            lhr=quantile(catch/harv.biomass,0.05),
            uuhr=quantile(catch/harv.biomass,0.75),
            llhr=quantile(catch/harv.biomass,0.25),
            cvhr=sd(catch/harv.biomass)/mean(catch/harv.biomass)) %>% 
  left_join(bootfit$res.by.year %>% 
              filter(grepl('mat',stock)) %>% 
              group_by(year) %>% 
              summarise(mssb=median(total.biomass),
                        ussb=quantile(total.biomass,0.95),
                        lssb=quantile(total.biomass,0.05),
                        uussb=quantile(total.biomass,0.75),
                        llssb=quantile(total.biomass,0.25),
                        cvssb=sd(total.biomass)/mean(total.biomass),
                        mF=median(F),
                        uF=quantile(F,0.95),
                        lF=quantile(F,0.05),
                        uuF=quantile(F,0.75),
                        llF=quantile(F,0.25),
                        cvF=sd(F)/mean(F))) %>% 
  left_join(fit$res.by.year %>% 
              group_by(year) %>% 
              summarise(ftb = sum(total.biomass),
                        catch = sum(catch),
                        fssb = sum(total.biomass[grepl('mat',stock)]),
                        frec = sum(recruitment,na.rm=TRUE),
                        fF = max(F))) %>% 
  left_join(fit$stock.full %>%
              filter(length>ref.cm) %>% 
              group_by(year) %>%
              summarise(fhb=sum(number*mean.weight))) %>%
  mutate(fhr=catch/fhb)

@

<<eval=FALSE,echo=FALSE>>=
tmp <- 
   list.dirs('../11-age12plus/BS.WGTS/',recursive = FALSE) %>% 
  purrr::map(function(x){
    load(sprintf('%s/WGTS/WGTS.Rdata',x))
    out
  }) 
bootfit <- 
  list.dirs('../11-age12plus/BS.WGTS/',recursive = FALSE) %>% 
  purrr::map(function(x){
    load(sprintf('%s/WGTS/WGTS.Rdata',x))
    out
  }) %>% 
  purrr::transpose() %>% 
  purrr::map(~purrr::map_if(.,is.null,data.frame)) %>% 
  purrr::map(~purrr::map_if(.,is.factor,as.character)) %>% 
  purrr::map(purrr::safely(~dplyr::bind_rows(.,.id='model'))) %>% 
  purrr::map('result') 
class(bootfit) <- c('gadget.fit',class(bootfit))

bootfit$likelihoodsummary <- tmp %>% purrr::map('likelihoodsummary') %>% 
  purrr::map(. %>% mutate(area=1)) %>% bind_rows(.id='model') 

save(bootfit,file='bootfit.Rdata')  
@




\begin{document}

\newcommand{\mcol}{\multicolumn}
\newcommand{\me}{\mathrm{e}}    % mathematical e (e^{a+bx})
\newcolumntype{d}{D{.}{.}{2}}
% 
% \newenvironment{MYlist}%
% {\begin{list}{}%
% {
% \setlength{\topsep}{0pt}%
% \setlength{\parskip}{0pt}%
% \setlength{\itemsep}{0pt}%
% \setlength{\parsep}{0pt}%
% \setlength{\leftmargin}{20mm}%
% }
% }
% {\end{list}}
 %\maketitle
% \thispagestyle{fancy}
% 

% \begin{abstract}
% This document describes a Gadget stock assessment of Ling in 5a and the development of precautionary reference points.  The model
% is able to follow trends in the tuning data and the fit to other
% data-sets is good.  Bootstrap runs indicate that the CV of reference biomass (>75cm)
% estimates in the time series is around 0.15 on average but around 0.28
% in the terminal years to to high variability in survey indices in that period and little other data on the incoming year classes. 
% 
% The reference points were determined following the ICES technical guidelines but instead of fishing mortality harvest rate in terms of biomass of fish larger that 75 cm was used. The estimates were obtained based on stochastic forward projections on the stock status under wide range of harvest rates. The projections considered factors such as assessment error and recruitment variations. 
% %This document describes a Gadget stock assessment of Ling in 5a.  The model
% %is able to follow trends in the tuning data and the fit to other
% %data-sets is good.  Bootstrap runs indicate that the CV of biomass
% %estimates in the time series is aroun 12\% on average but around 22\%
% %in the terminal years to to high variability in survey indices in that period. 
% \end{abstract}


\part{blu}
\chapter{A Gadget assessment of Tusk in 5a and 14}

\newpage

\section{A Gadget assessment of Ling in 5a}
Gadget is a shorthand for the "Globally applicable  Area
Dis-aggregated  General  Ecosystem  Toolbox", which is a statistical
model of marine ecosystems (previously known as BORMICON
\citep{stefansson1997bormicon} and 
Fleksibest \citet{guldbrandsen2002fleksibest}). Gadget is an age-length structured forward-simulation
modeling framework, where models can be coupled with an extensive set of data comparison and
optimisation routines. Processes are generally modeled as dependent
on length, but age is tracked in the models, and data can be compared
on either a length and/or age scale. The framework allows for the creation of
multi-area, multi-fleet models, capable of including
predation and mixed fisheries issues, however it can also be used on a
single species basis. Gadget  models can be both very data- and
computationally- intensive, with optimisation in particular taking a
large amount of time. Worked examples, a detailed manual and further
information on  Gadget  can be found on \texttt{www.github.com/hafro/gadget}. In
addition the structure of the model is described in
\citet{begley2004overview}, and a formal mathematical description is
given in \citet{guldbrandsen2002fleksibest}.

The Gadget framework is essentially three things, an \textbf{ecosystem simulator}, a
\textbf{likelihood} function that takes the output from the ecosystem simulator
and compares to data, and a \textbf{function mininimizer}. Gadget's \textbf{ecosytem simulator}
allows for a fairly configurable ecosystem simulation. Its
fundamental unit, a \textbf{stock} (or more accurately substock),
represents a group of individuals that is homogenous with respect to
various processes. These processes include growth, predation
(including commercial fisheries) and migration. In this setup
different stages of the life history of a particular species would be
represented as separate stocks and individuals ``moved'' between
stocks when required. The simulation takes place in a set number of
\textbf{years}  and \textbf{time-steps} within
a year. The time-steps within the year allow for the
emulation of the annual cycles of the ecosystem, such as recruitment
and stock migrations.

The stock unit within Gadget is simply a representation of the total
number of individuals in a certain age range and length group range 
within certain areas. The stocks live in an area, or areas, where they
optionally migrate to and from. In this setup processes such as fleet
harvest or recruitment can be restricted to take place only in certain (or all)
areas. Harvesting of the substocks is defined through fleets that fish
according to harvest rate and (length--based) selection functions.


%The state of the ecosystem that is simulated in Rgadget is observed
%through the stock abundance and harvest. The abundances of the
%substocks in the simulation are observed through a number of
%individuals $N_{sralt}$ of that particular stock $s$, area $r$, age
%group $a$, length group $l$ and time $t$. Similarly the harvesting is
%observed through the number of individuals caught $C_{fralt}$ by fleet
%$f$ and $r$, $a$, $l$ and $t$ as before. 
%Further description on how
%processes can be defined can be found in \cite{begley2005gadget}. 

%\subsection{Gadget likelihood module}
Gadget's \textbf{likelihood} module processes the output from the ecosystem
simulation based on aggregate dimensions. Within the likelihood module
a number of datasets can be compared to the model output. In addition
to a suite of functions designed to work with different types of
survey indices, length distributions, tagging data, age and length
distribution and maturity data, to name a few, can be contrasted to
the model output. Each data set is included at its own aggregation
level, with missing data handled in a robust manner.

%\section{The iterative likelihood reweighting scheme}
In contrast with Gadget, age based or stock production type stock
assessments require data in a fairly processed form. For instance when
using VPA one requires the total catch in numbers of individuals by
age. However, apart from catches of fin whales in the North Atlantic
\citep{iwcistfin2015}, one rarely has all catches by numbers at
age. Therefore the age distribution of catches needs to be
approximated using some combination of age readings, length
distributions, total catches in tons and weight at age \citep[as noted
in][]{hirst2005estimating}. In essence using a typical VPA requires a two-step modelling process, whereas Gadget models combines these two steps. 



Gadget's \textbf{function minimizer}, based on the negative log--likelihood, varies the
model parameters, runs a full simulation, and calculates a new
output. This process is repeated until a minimum is obtained. The total objective function to be minimised is a weighted sum of the
different components.  The estimation could be difficult due to groups
of correlated parameters or multiple local optima. To address these issues Gadget has three alternative optimising algorithms built in, a wide
area search \texttt{simulated annealing} \citep{corana1987minimizing},
a local search \texttt{Hooke and Jeeves algorithm}
\citep{HookeJeeves1961} and finally one based on the
Broyden-Fletcher-Goldfarb-Shanno algorithm, hereafter termed
\texttt{BFGS}, described in \citet{bertsekas1999nonlinear}. The
optimisation procedure often involves a combination of these three procedures.

%   Therefore the
% optimisation procedure often involves a combination of the more robust
% simulated annealing, to make the results less sensitive to the initial
% (starting) values, and to the local search algorithms (Hooke and
% Jeeves and BFGS) in the neighborhood of the global optima.


%The model is able to use all three algorithms in a single
%optimisation run, attempting to utilise the strengths of all. Simulated
%annealing is used first to attempt to reach the general area of a
%solution, followed by Hooke and Jeeves to rapidly home in on the local
%solution and finally BFGS is used for fine-tuning the optimisation.
%This procedure is repeated several times to attempt to avoid
%converging to a local optimum.

\subsection{Setup of a gadget run}
There is a separation of model and data within Gadget. The simulation
model runs with defined functional forms and parameter values, and
produces a modeled population, with modeled surveys and
catches. These surveys and catches are compared against the available
data to produce a weighted likelihood score. Optimisation routines
then attempt to find the best set of parameter values. Fig. \ref{fig:setup} 
illustrates how this is implemented in Gadget's input file structure. 


\begin{figure}[h]
 \centering
\begin{adjustbox}{max width=0.99\textwidth}
  \begin{tikzpicture}[xscale = .9,yscale = .9]
    \node (main)[shape=ellipse,style=dashed,draw] at (-7,-2){main};
    \node (time) at (-2,2){time};
    \node (area) at (-2,1){area};
    \node (print) at (-2,0){printfile};
    \node (out)[shape=rectangle,draw] at (2.5,2) {output};
    \node (stock)[GenericNodeStyle] at (-2,-1){stockfiles};
    \node (refw) at (4,0){reference weights};
    \node (initpop) at (4,-0.5){initial population};
    \node (rec) at (4,-1){recruitment};
    \node (mat) at (4,-1.5){maturation};
    \node (mig) at (4,-2){migration};
    \node (spw) at (4,-2.5){spawning};
    \node (str) at (4,-3){straying};
    \node (tagf)[GenericNodeStyle] at (-2,-2.5){tagfiles};
    \node (tagd) at (2.5,-4){tag data};
    \node (oth)[GenericNodeStyle] at (-2,-4){otherfoodfiles};
    \node (othd) at (2.5,-5){otherfood data};
    \node (fleet)[GenericNodeStyle] at (-2,-5.5){fleetfiles};
    \node (fleetd) at (2.5,-6){fleet data};
    \node (lik)[GenericNodeStyle] at (-2,-7){likelihoodfiles};
    \node (likd) at (2.5,-7){likelihood data};
   
    \node (param)[shape=ellipse,style=dashed,draw] at (-7,-4){parameters};
    \node (opt)[shape=ellipse,style=dashed,draw] at (-7,-7){optimisation};
    
    \draw[->] (main) to (time);
    \draw[->] (main) to (area);
    \draw[->] (main) to (print);
    \draw[->] (main) to (stock);
    \draw[->] (main) to (tagf);
    \draw[->] (main) to (oth);
    \draw[->] (main) to (fleet);
    \draw[->] (main) to (lik);
    
    \draw[->] (print) to (out);
    
    \draw[->] (stock) to (refw);
    \draw[->] (stock) to (initpop);
    \draw[->] (stock) to (rec);
    \draw[->] (stock) to (mat);
    \draw[->] (stock) to (mig);
    \draw[->] (stock) to (spw);
    \draw[->] (stock) to (str);
    
    \draw[->] (tagf) to (tagd);
    
    \draw[->] (oth) to (othd);
    \draw[->] (fleet) to (fleetd);
    \draw[->] (lik) to (likd);
    \end{tikzpicture}
\end{adjustbox}

 \caption[]{Schematic description of the file structure in a Gadget model}\label{fig:setup}
\end{figure}

\subsection{Simulation model}
In a typical Gadget model the simulated quantity is the number of
individuals, $N_{alsyt}$, at age $a=a_{min}\ldots a_{max}$, in a length-group $l$,
representing lengths ranging between $l_{min}$ and $l_{max}$ cm in $\Delta l$ cm
length-groups, at year $y$ which is divided into timesteps, usually quarters, $t = 1\ldots T$. The
length of the time-step is denoted $\Delta t$. 
The population is governed by the following equations:
{\footnotesize
\begin{equation}\label{eq:stock}
\begin{aligned}
  N_{alsy,t+1} = &\sum_{l'}G^{l}_{l'} \left[(N_{al'syt} -
    \sum_f C_{fal'st})e^{-M_a \Delta t }  + I_{al'lsyt}\right] &\textup{if $t < T$}\\ 
  N_{a,ls,y+1,1} = &\sum_{l'}G^{l}_{l'} \left[(N_{a-1,l'sy,T} -
    \sum_f C_{fa-1,l's,T})e^{-M_{a-1} \Delta t }  + I_{a-1,l'lsy,T}\right] &\textup{if $t
    = T$ and $a < a_{max}$} \\
  N_{a,ls,y+1,1} = &\sum_{l'}G^{l}_{l'} (N_{al'sy,T} -
    \sum_f C_{fal'sy,T} + \\
    &\qquad N_{a-1,l'sy,T} - \sum_f C_{f,a-1,l'sy,T})e^{-M_a \Delta t }
    & \textup{if $t = T$ and $a = a_{max}$}  
\end{aligned}
\end{equation}
}
where $G^{l}_{l'}$ is the proportion in length-group $l$ that 
has grown $l - l'$ length-groups in $\Delta t$, $C_{falsyt}$ denotes the
catches by fleet $f \in \{S, L, G, T, F\}$, i.e. the survey\footnote{The survey 
fleet catches are given a nominal catch to allow for survey age and
length distribution predictions.}, longliner, gillnetters, trawlers and foreign vessels\footnote{In the case of ling foreign vessels are assumed to have the same suitability function as the commercial fleet, however this does however simplifies the data entry.}, $M_a$ the
natural mortality at age $a$ and $I_{al'lsyt}$ denotes the movement of fish at length $l'$ from
the immmature to the mature stock component at length $l$ \footnote{A short note on
notation, here $l$ is used interchangeably as either the length-group or the
midpoint of the length interval for that particular length-group,
depending on the context.}.



\subsubsection{Growth}
Growth in length is modeled as a two--stage process, an average length
update in $\Delta t$ and a growth dispersion around the mean
update \citep[as described in ][]{stefansson05bbin}.
Average length update is modeled by calculating the mean growth for each length
group for each time step, using a parametric
growth function. In the current 
model a simplified form of the Von Bertanlanffy function has been
employed to calculate this mean length update. 
\begin{equation}\label{eq:vonB}
\Delta l = (l_\infty -l) (1 - e^{-k\Delta t})
\end{equation}
where $l_\infty$ is the terminal length and $k$ is the annual growth rate.

Then the length distributions are updated
according to the calculated mean growth by allowing some portion of
the fish to have no growth, a proportion to grow by one length group
and a proportion two length groups etc.  How these proportions are
selected affects the spread of the length distributions but these two
equations must be satisfied:
\begin{equation}\nonumber
\sum_i p_{il} = 1
\end{equation}
and
\begin{equation}\nonumber
\sum_i i p_{il} = \Delta l
\end{equation}  
Here $\Delta l$ is the calculated mean growth and $p_{il}$ is the
proportion of fish in length group $l$ growing $i$ length groups.
Here the growth is dispersed according to a beta--binomial
distribution parametrised by the following equation: 
\begin{equation}\label{eq:betabinom}
G^{l'}_l = \frac{\Gamma(n+1)}{\Gamma((l'-l)+1)}
\frac{\Gamma((l'-l)+\alpha)\Gamma(n-(l'-l)+\beta)}{\Gamma(n-(l'-l)+1)\Gamma(n+\alpha+\beta)}
\frac{\Gamma(\alpha+\beta)}{\Gamma(\alpha)\Gamma(\beta)} 
\end{equation}
where $\alpha$ is subject to
\begin{equation}
\alpha = \frac{\beta \Delta l}{n - \Delta l}
\end{equation}
where $n$ denotes the maximum length group growth and $(l'-l)$ the
number of length-groups grown. 


The weight, $W_{sl}$, at length-group $l$ is calculated according to
the following stock component specific length -- weight relationship: 
\begin{equation}\label{eq:lw}
W_{sl} = \mu_s l^{\omega_s}
\end{equation} 



\subsubsection{Recruitment and initial abundance}
Gadget allows for a number of relationships between stock recruitment
and the size of the spawning stock to be defined. However in this
model the number of recruits each year, $R_y$, is estimated
within the model as a. 

Recruitment enters the population according to:
\begin{equation}\label{eq:rec}
  N_{a_{min}l0yt'} = R_{y} p_l
\end{equation}
where $t'$ denotes the recruitment time-step and  $p_l$ is the proportion
in length-group $l$ that is recruited. $p_l$ is determined by a normal
density with mean length set according to eq. \ref{eq:vonB} where the initial length $l_0$ at age 1 \footnote{$l_0$ as a one to one mapping with $t_0$ used in 
a typical von Bertalanffy growth model} and variance $\sigma^2_{3}$. 

A simple formulation of initial abundance in numbers is used for
each age group in length-group $l$: 
\begin{equation}\label{eq:init}
N_{als11} = \nu_{as} q_{al}    
\end{equation}
where $\nu_{as}$ is the initial number at age $a$ in the initial
year of stock $s$ and $q_l$ the proportion at length-group $l$ which is determined
by a normal density with a mean according to the growth model in
equation \ref{eq:vonB} and variance $\sigma_a^2$, with a starting length according as $l_0$ (length at age 1). 

\subsubsection{Maturation}
Two stage maturity is modeled and represented by the two stock
components. First the movement between the two components is formulated as 
\begin{equation}\label{eq:mat}
  I_{al'lsyt} = \left\{ \begin{matrix}
      N_{al'0y,t-1}\times m_{l'}^{l} & \textup{if s
      = 1 and t > 1} \\
    N_{al'0y-1,T}\times m_{l'}^{l} & \textup{if s
      = 1 and t = 1} \\
    
    - N_{al'0y,t-1}\times m_{l'}^{l} & \textup{if s
      = 0 and t > 1}\\
    - N_{al'0y-1,T}\times m_{l'}^{l} & \textup{if s
      = 0 and t = 1}

 
\end{matrix}\right.
\end{equation}
where $s=0$, as noted above, denotes the immature stock component.  and
$m_{l'}^{l}$ is the proportion of immatures that mature between the
lengths $l$ and $l'$ defined as:
\begin{equation}
m_{l'}^l = \frac{\lambda (l-l')}{1 + e^{-\lambda (l - l_{50})}}
\end{equation}
The second when individuals of the immature stock component reach a 
certain age those individuals are all moved to the mature stock component.

\subsubsection{Fleet operations}
Catches are simulated based on reported total landings and a length
based suitability function for each of the fleets (commercial
fleets and surveys). Total landings are assumed to
be known and the total biomass is simply offset by the landed
catch. The catches for length-group $l$ , fleet $f$ at year $y$ and
time-step $t$ are calculated as  
\begin{equation}
C_{falsyt} = E_{ft} \frac{S_{f}(l)N_{alsyt}W_{ls}}{\sum_{s'} \sum_{l'}\sum_{a'} S_{f}(l')N_{al's'yt}W_{l's'}} 
\end{equation}
where $E_{ft}$ is the landed biomass at time $t$ and $S_{f}(l)$ is the suitability of length-group $l$ by fleet $f$ defined as\footnote{Other functional forms for the selection are defined in Gadget}:
\begin{equation}\label{eq:suit}
S_f(l) = \frac{1}{1 + e^{(-b_f(l-l_{50,f})}}
\end{equation}

The effective fishing mortality at age and at time step $t$ is calculated according to the following equation:

\begin{equation}\label{eq:Feq}
F_{asyt} = \frac{-\log(1.0 - \frac{C_{asyt}}{N_{asyt}})}{\Delta t}
\end{equation}

where $C_{asyt} =\sum_{fl} C_{falsyt}$ and $N_{asyt} = \sum_l N_{alsyt}$. For ling the reported $F_y$ is the average $F_a$ for fully recruited ages, i.e. age 12 and above, for that year. 

Harvest rate in terms of the reference biomass is calulated as:
\begin{equation}
H_y = \frac{C_y}{B_{ref,y}}
\end{equation}
where $C_y = \sum_{falst} C_{falsyt} W_{s,l}$ and $B_{ref,y} = \sum_{alst} N_{alsyt} W_{s,l}$. For ling the reported reference biomass is the biomass of fish larger than or equal to 75cm, denoted $B_{75cm^+,y}$.



\subsection{Observation model}
A significant advantage of using an age-length structured model is
that the modeled output can be compared directly against a wide
variety of different data sources. It is not necessary to convert
length into age data before comparisons. Gadget can use various types
of data that can be included in the objective function. Length
distributions, age length keys/distributions, survey indices by length or age (both abundance or biomass), CPUE
data, mean length and/or weight at age, tagging data and stomach
content data can all be used. 

Importantly this ability to handle length data directly means that the model can be used for stocks such
as ling in 5a where age data is sparse and/or are unrelible. Length data 
can be used directly for model comparison. The model is able to
combine a wide selection of the available data by using a maximum
likelihood approach to find the best fit to a weighted sum of the
data-sets.

In Gadget, data are assimilated using a weighted log--likelihood
function. Here four types of data enter the likelihood, length based
survey indices, maturity at length from the survey, length distributions from survey and commercial
fleets and age -- length distribution from from the survey and commercial
fleets.  


In formulations below it is assumed that the compositional data are sampled at random, both from the fishery and surveys, as this is how the sampling protocol is Icelandic waters is set up. Other forms of likelihoods are implemented in Gadget that can be used to address other types of sampling, e.g. length stratified sampling of maturity. 


\begin{figure}[h]
 \centering
\begin{adjustbox}{max width=0.99\textwidth}
  \begin{tikzpicture}[xscale = .9,yscale = .9]
    \node (fleet) at (0,5){Fleets}; 
    \node (fleet) at (0,6){Model components}; 
    \node (fleet) at (7,6){Likelihood};       
    \node (obs)[GenericNodeStyle] at (11,1.5){Observations};
    \node (ALK)[GenericNodeStyle] at (7,4){Age--length};
    \node (LK)[GenericNodeStyle] at (7,2.5){Length};
  %  \node (AB)[GenericNodeStyle] at (7,1){Abundance};
    \node (ind)[GenericNodeStyle] at (7,-1){Indices};
    \node (mat)[GenericNodeStyle] at (7,0.6){Maturity};
    \node (foreign)[GenericNodeStyle] at (-2.7,1.6){Foreign fleets};
    \node (comm)[GenericNodeStyle] at (-2,3){Trawlers};
     \node (lln)[GenericNodeStyle] at (0,4.2){Longliners};
      \node (gil)[GenericNodeStyle] at (2,3){Gilnetters};
  
  %  \draw[->,color=red](Whaling)--(LK);
    \node (surv)[GenericNodeStyle] at (3,1.6){Survey};
    \node (Minke)[GenericNodeStyle] at (-1.8,-0.5){Ling--mature};  
    \node (Cod)[GenericNodeStyle] at (2,-2){Ling--immature};
  %  \node (Otherfood)[GenericNodeStyle] at (-3,-2){Other food};
  %  \draw[->,color=red](Whaling)--(ALK);
 
 \begin{scope}[on background layer]
     \draw [fill=blue!10!white,fill opacity=0.5] (-4.5,-3)
    rectangle (5,6.5);
    \draw [fill=blue!10!white,style=dashed] (-4.4,1)
    rectangle (4.9,5.5);
    \draw [fill=yellow!10!white] (5.1,6.5) rectangle (9,-3);

   \draw[->,color=red](comm)--(LK);
    \draw[->,color=red](comm)--(ALK);
    \draw[->,color=red](gil)--(ALK);
      \draw[->,color=red](lln)--(ALK);
    \draw[->,color=red](surv)--(ALK);
    \draw[->,color=red](surv)--(LK);
    \draw[->,color=red](lln)--(LK);
    \draw[->,color=red](gil)--(LK);
    
    \draw[->,color=red](surv)--(mat);
    
    \draw[<-,color = green](Minke)--(Cod);
  %  \draw[<-](Minke)--(Otherfood);
  %  \draw[->](Minke)--(Whaling);
    \draw[<-](surv)--(Minke);
    \draw[<-](comm)--(Minke);
     \draw[<-](lln)--(Minke);
      \draw[<-](gil)--(Minke);
    \draw[<-](surv)--(Cod);
    \draw[<-](comm)--(Cod);
    \draw[<-](foreign)--(Minke);
    \draw[<-](foreign)--(Cod);
    \draw[<-](lln)--(Cod);
    \draw[<-](gil)--(Cod);


  %  \draw[->,color=red](Minke)--(AB);
  %  \draw[->,color=red](Minke)--(con);
    \draw[->,color=red](Cod)--(ind);    
    \draw[->,color=red](Minke)--(ind);    
    \draw[->,color=red](obs)--(ALK);
    \draw[->,color=red](obs)--(LK);
    \draw[->,color=red](obs)--(mat);
  %  \draw[->,color=red](obs)--(con);
    \draw[->,color=red](obs)--(ind);
     \end{scope}
  \end{tikzpicture}
\end{adjustbox}

 \caption[]{Schematic description of the Gadget model for Ling in 5a. Lines indicated flow from one model component to the other. Black lines indicate consumption by predators (fleets), red lines the modelled predictions/observations sent to the likelihood and green lines movement between stock components. }\label{fig:overview}
%\label{fig:Aggrind}
\end{figure}


\subsubsection{Survey indices}
For each length range $g$ the survey index is compared to the modeled
abundance at year $y$ and time-step $t$ using: 
\begin{equation}\label{eq:SSSI}
  l_{g}^{\textup{SI}} = \sum_{y} \sum_t (\log I_{gy} - (\log q_g + b_g \log \widehat{N_{gyt}}))^2 
\end{equation}
where $$\widehat{N_{gyt}} = \sum_{l\in g} \sum_a \sum_s N_{alsyt}$$

\subsubsection{Fleet data}
Length distributions are compared to predictions using
\begin{equation}\label{eq:SSldist}
  l_f^{\textup{LD}} = \sum_y \sum_t \sum_l (\pi_{flyt} - \hat{\pi}_{flyt})^2
\end{equation}
where $f$ denotes the fleet where data was sampled from and 
$$\pi_{flyt} = \frac{\sum_a\sum_s O_{falsyt}}{\sum_{a'}  \sum_{l'}\sum_sO_{fa'l'syt}}$$ 
and 
$$\hat{\pi}_{lyt} = \frac{\sum_a  \sum_s C_{falsyt}}{\sum_{a'}
  \sum_{l'}\sum_s C_{fa'l'syt}}$$ 
i.e the observed and modeled proportions in length-group $l$ respectively
at year $y$ and time-step $t$. Similarly age -- length data are
compared:  
\begin{equation}\label{eq:SSalk}
  l_f^{\textup{AL}} = \sum_y \sum_t \sum_a \sum_l  (\pi_{falyt} - \hat{\pi}_{falyt})^2
\end{equation}
where 
$$\pi_{falyt} = \frac{\sum_s O_{falsyt}}{\sum_a  \sum_{l'}\sum_s O_{fal'syt}}$$ 
and 
$$\hat{\pi}_{falyt} = \frac{\sum_s C_{falsyt}}{\sum_{a'}
  \sum_{l'}\sum_s C_{fa'l'syt}}$$ 
  
Length at maturity comparison uses the number fish of which maturity status has been assigned that are observed in a given fishery or a survey. The observed
proportions are compared to the modelled proportion using sum of
squares: 
\begin{equation}\label{eq:SSmat}
  l^{\textup{M}}_f = \sum_y \sum_t \sum_l  (\pi_{flyt} -
  \hat{\pi}_{flyt})^2 
\end{equation}
where 
$$\pi_{flyt} = \frac{\sum_a O_{fal1yt}}{\sum_{a'}  \sum_{l'}\sum_sO_{fa'l'syt}}$$ 
and 
$$\hat{\pi}_{flyt} = \frac{\sum_a  C_{fal1yt}}{\sum_{a'}
  \sum_{l'}\sum_sC_{fa'l'syt}}$$ 
  
i.e. the observed and modelled proportions of ling in length group $l$ and and mature, in year $y$ and timestep $t$, and where the fleet $f$ corresponds to the survey.

  
\subsection{Order of calculations}
The order of calulations is as follows:
\begin{enumerate}
\item \textbf{Printing}: model output at the beginning of the time-step
\item \textbf{Consumption}: mainly fleet harvesting
\item \textbf{Natural mortality}: Natural mortality is applied after consumption
\item \textbf{Growth and maturation}: length update is applied and maturing fish moved from one stock component to the other.
\item \textbf{Spawning and recruitment}: New individuals enter the immature stock component
\item \textbf{Likelihood comparison}: likelihood score is calculated here, note that the comparison is based on the modeled processes in previous steps
\item \textbf{Printing}: model output at the end of the time-step
\item \textbf{Ageing}: if this is the end of year the age is increased
\end{enumerate}
  

\subsection{Iterative re--weighting}\label{iterRW}
The total objective function used the modeling process combines
equations \ref{eq:SSSI} to \ref{eq:SSalk} using the following formula:

\begin{equation}\label{eq:loglik}
l^{\textup{T}} = \sum_g  w_{gf}^{\textup{SI}}
l_{g,S}^{\textup{SI}} + \sum_{f\in \{S,T,G,L\}} \left(
  w_{f}^{\textup{LD}}  l_{f}^{\textup{LD}} + w_{f}^{\textup{AL}}
  l_{f}^{\textup{AL}}\right) + w^{\textup{M}}l^{\textup{M}}
\end{equation}
where $f=S,T,G,L$ or $C$ denotes the spring survey, trawl, gillnet and
longline fleets respectively (See subsection \ref{subsec:FleetSel})
and $w$'s are the weights assigned to each likelihood components. 

The weights, $w_i$, are necessary for several reasons. First of all it
is used to to prevent some components from dominating the likelihood
function. Another would be to reduce the effect of low quality
data. It can be used as an a priori estimates of the variance in each
subset of the data. 


Assigning likelihood weights is not a trivial matter, has in the past
been the most time consuming part of a Gadget model. Commonly this has
been done using some form of 'expert judgement'. General heuristics
have recently been developed to estimated these weights
objectively. Here the iterative re--weighting heuristic introduced by
\cite{stefansson2003issues}, and subsequently implemented in
\cite{taylor2007simple}, is used. 


The general idea behind the iterative re-weighing is to assign the
inverse variance of the fitted residuals as component weights. The
variances, and hence the final weights, are calculated according the
following algorithm: 
\begin{enumerate}
\item Calculate the initial sums of squares (SS) given the initial
  parametrization for all likelihood components. Assign the inverse SS
  as the initial weight for all likelihood components, resulting in a total initial score of 1 for each component. 
\item For each likelihood component, do an optimization run with
  the initial weighted SS for that component set to 10000. Then estimate the
  residual variance using the resulting SS of that component divided
  by the degrees of freedom ($df^*$), i.e. $\hat{\sigma}^2 = \frac{SS}{df^*}$.
\item  After the optimization set the final weight for that all
  components as the inverse of the estimated variance from the step above
  (weight $=1/\hat{\sigma}^2$). 
\end{enumerate}


The number of non-zero data-points ($df^{*}$) is used as a proxy
for the degrees of freedom.
While this may be a satisfactory proxy for larger data-sets it could be
a gross overestimate of the degrees of freedom for smaller data-sets. 
In particular, if the survey indices are weighed on their own while the
yearly recruitment is estimated they could be over-fitted. In general 
problem such as these can be solved with component grouping, that is
in step 2 the likelihood components that should behave similarly, such
as survey indices representing similar age ranges, should be upweighted and optimized 
together. This kind of grouping is used in the present model (See
subsection \ref{subsec:ItW}). 



\subsection{Optimisation}
The total objective function to be minimised is a weighted sum of the
different components, as described in eq. \ref{eq:loglik}.  The estimation could be difficult due to groups
of correlated parameters, multiple local optima or flat surfaces of the objective function in the search neighbourhood.  Therefore the
optimisation procedure often involves a combination of the more robust
simulated annealing, to make the results less sensitive to the initial
(starting) values, and to the local search algorithms (Hooke and
Jeeves and BFGS) in the neighborhood of the global optima.



The model has three alternative optimising algorithms linked to it, a
wide area search \texttt{simulated annealing} \citep{corana1987minimizing}, a local
search \texttt{Hooke and Jeeves algorithm} \citep{HookeJeeves1961} and
finally one based on the Boyden-Fletcher-Goldfarb-Shanno algorithm
hereafter termed \texttt{BFGS}. 

The simulated annealing and Hooke-Jeeves algorithms are not gradient based,
and there is therefore no requirement on the likelihood surface being
smooth. Consequently neither of the two algorithms returns estimates
of the Hessian matrix. Simulated annealing is more robust than Hooke
and Jeeves and can find a global 
optima where there are multiple optima but needs about 2-3 times the
order of magnitude number of iterations than the Hooke and Jeeves
algorithm.

BFGS is a quasi-Newton optimisation method that
uses information about the gradient of the function at the current
point to calculate the best direction to look for a better point.
Using this information the BFGS algorithm can iteratively calculate a
better approximation to the inverse Hessian matrix.  In comparison to
the two other algorithms implemented in Gadget, BFGS is very local
search compared to simulated annealing and more computationally
intensive than the Hooke and Jeeves.  However the gradient search in
BFGS is more accurate than the step-wise search of Hooke and Jeeves and
may therefore give a more accurate estimation of the optimum.  The
BFGS algorithm used in Gadget is derived from that presented by
\citet{bertsekas1999nonlinear}.


The model is able to use all three algorithms in a single
optimisation run, attempting to utilise the strengths of all. Simulated
annealing is used first to attempt to reach the general area of a
solution, followed by Hooke and Jeeves to rapidly home in on the local
solution and finally BFGS is used for fine-tuning the optimisation. 
This procedure is repeated several times to attempt to avoid
converging to a local optimum. 

The total objective function to be minimised is a weighted sum of the
different components. 
The estimation can be difficult because of some or groups of
parameters are correlated and therefore the possibility of multiple
optima cannot be excluded.  The optimisation was started with
simulated annealing to make the results less sensitive to the initial
(starting) values and then the optimisation was changed to Hooke and
Jeeves when the 'optimum' was approached and then finally the BFGS was
run in the end. The settings for the miniizers are listed in annex \ref{Ann:Optinfo}.

\subsection{Bootstrap}
\begin{figure}
<<echo=FALSE,results='asis',fig.width=10, fig.height=5,cache=TRUE,warning=FALSE,message=FALSE>>=
fish.pos <- 
  mfdb_dplyr_sample(mdb) %>% 
  filter(species=='LIN',year==2015,data_source=='iceland-ldist') %>% 
  left_join(mfdb_dplyr_division(mdb)) %>%
  left_join(mfdb:::mfdb_dplyr_table(mdb,'tow',"all_cols") %>% 
              select(tow=name,tow_length=length,tow_depth=depth,
                     lat=latitude,lon=longitude)) %>% 
  collect(n=Inf) 



## read mapping

bcareas <- c(1015, 1014, 1018, 1011, 1012, 1023, 1023, 1021, 1032, 1031,
             1042, 1041, 1052, 1053, 1051, 1054, 1061, 1071, 1081, 1082)

reitmapping <- 
  read.table(
        system.file("demo-data", "reitmapping.tsv", package="mfdb"),
        header=TRUE,
        as.is=TRUE) %>%
  mutate(sr=as.numeric(GRIDCELL)) %>% 
  mar:::sr2d() %>% 
  filter(SUBDIVISION %in% c(bcareas,fish.pos$division))



test <- 
  plyr::ddply(reitmapping, 'SUBDIVISION',
        function(x){
          ##   2
          ## 1 x 3
          ##   4
          sides <- rep(10*x$GRIDCELL,each=4) + 1:4
          up <- geo::d2sr(x$lat + 0.125, x$lon)
          down <- geo::d2sr(x$lat - 0.126, x$lon)
          left <- geo::d2sr(x$lat, x$lon - 0.25)
          right <- geo::d2sr(x$lat, x$lon + 0.26)
          
          for(i in 1:nrow(x)){
            ## up
            if(up[i] %in% x$GRIDCELL){
              sides[4*(i-1)+2] <- NA
              sides[sides==(10*up[i]+4)] <- NA
            }
            ## down
            if(down[i] %in% x$GRIDCELL){
              sides[4*(i-1)+4] <- NA
              sides[sides==(10*down[i]+2)] <- NA
            }
            ## left
            if(left[i] %in% x$GRIDCELL){
              sides[4*(i-1)+1] <- NA
              sides[sides==(10*left[i]+3)] <- NA
            }
            ## right
            if(right[i] %in% x$GRIDCELL){
              sides[4*(i-1)+3] <- NA
              sides[sides==(10*right[i]+1)] <- NA
            }
          }
          sides <- sides[!is.na(sides)]
          corners <- plyr::ddply(data.frame(side=rep(sides,each=2)),
                       'side',
                       function(x){
                         loc <- geo::sr2d(floor(x$side[1]/10))
                         loc <- c(loc$lat,loc$lon)
                         if((x$side[1] %% 10) == 1){
                           up.loc <- loc+c(0.125,-0.25)
                           down.loc <- loc+c(-0.125,-0.25)
                         }
                         if((x$side[1] %% 10) == 3){
                           up.loc <- loc+c(0.125,0.25)
                           down.loc <- loc+c(-0.125,0.25)
                         }
                         if((x$side[1] %% 10) == 2){
                           up.loc <- loc+c(0.125,-0.25)
                           down.loc <- loc+c(0.125,0.25)
                         }
                         if((x$side[1] %% 10) == 4){
                           up.loc <- loc+c(-0.125,-0.25)
                           down.loc <- loc+c(-0.125,0.25)
                         }
                         tmp <- as.data.frame(rbind(up.loc,down.loc))
                         names(tmp) <- c('lat','lon')
                         return(tmp)                        
                       })
          corners$order <- NA
          corners$order[1:2] <- 1:2
          counter <- 1:nrow(corners)
          i <- 2
          for(order in 3:(length(sides))){
            tmp <- counter[is.na(corners$order) &
                           corners$lat == corners$lat[i] &
                           corners$lon == corners$lon[i]][1]
            corners$order[corners$side == corners$side[tmp]] <- order
            corners <- corners[-tmp,]
            i <- which(corners$order == order)
            
          }
          corners$side <- NULL
          return(arrange(corners,order))
          
        })




 ggplot(data.frame(lat=0,lon=0), aes(lon,lat)) +
#  ggplot(subset(dat,ar==2011),aes(lon,lat)) +
#  stat_density2d(aes(fill=..level..),geom='polygon') +
#  scale_fill_gradient(limits = c(0,0.2), low='yellow',high='red') +
  geom_point(col='yellow') +  
  geom_path(data=geo::gbdypi.100,lty=2,size = 0.3) +
  geom_path(data=geo::gbdypi.800,lty=2,size = 0.3) +
  #  geom_polygon(alpha=0.5,data=geo::gbdypi.100,fill='gray90') +
  geom_path(data=geo::gbdypi.200,lty=2,size = 0.3) + #alpha=0.5,fill='gray90',
  geom_path(data=geo::gbdypi.500,lty=3,size = 0.3) +
  geom_path(data=geo::gbdypi.1000,lty=4,size = 0.3) +
  geom_path(aes(lon,lat,group=SUBDIVISION),
            data=test, #
            #subset(test,SUBDIVISION %in% bcareas),
            size = 0.3) +
  # geom_polygon(aes(lon,lat,group=SUBDIVISION),
  #           data=test %>% 
  #             filter(SUBDIVISION %in% c(1061,1143,1142)), #
  #           #subset(test,SUBDIVISION %in% bcareas),
  #           size = 0.3,fill='gold',alpha=0.5) +

  geom_polygon(data=geo::island, col = 'black' ,fill = 'gray70',size = 0.3) +
#  geom_polygon(data=geo::greenland, col = 'black', fill = 'gray70') +
  geom_polygon(data=geo::eyjar, col = 'black', fill = 'gray70',size = 0.3) +
  geom_polygon(data=geo::faeroes, col = 'black', fill = 'gray70') +
  coord_map('mercator', xlim=c(-30,-10),ylim=c(62,68)) +
#     geom_label(aes(lon,lat,label=SUBDIVISION),
#            data=ddply(test,~SUBDIVISION, summarise, lat=mean(lat),
#              lon=mean(lon))) +
#  coord_map('mercator', xlim=c(-28,-9.5),ylim=c(62.5,68)) +
  xlab('Longitude') +
  ylab('Latitude') + 
  theme_light() +
  geom_point(data=fish.pos%>% select(tow,lat,lon) %>% distinct()) +
  geom_path(data = geo::twohmiles, lty = 2) #+
#  geom_path(data=icelandrivers,size=0.1,col='blue') +
#  geom_path(data=glaciers,size=0.5)





@


\caption{Ling in 5a. Locations of Ling catches in 5a by commercial and survey fleets in 2015 relative to the spatial subdivision on the Icelandic continental shelf area. }\label{map2}
\end{figure}
To estimate the uncertainty in the model parameters and derived quantities a 
specialised boostrap for disparate datasets is used. The approach is based on 
spatial subdivisions that can be considered to be i.i.d. Refer to 
\cite{Elvarsson2014} and \cite{mfdb} for further implementation details. The bootstrapping approach consists of the following:

\begin{itemize}
\item The base data are stored in a standardized data base:
\begin{itemize}
\item Time aggregation: 3 months
\item Spatial aggregation: subdivision
\item Further dis-aggregation is based on a range of categories
  including fishing gear, fishing vessel class, sampling type
  (e.g. harbour, sea and survey). A full listing of data types used in the
  case study can be found in table \ref{tbl:data}, these data are
  stored subdivision dis-aggregated to allow for use in a bootstrap. 
\end{itemize}
\item To bootstrap the data, the list of subdivisions, depicted in
  fig. \ref{map2}, required for the
  model is sampled (with replacement) and stored. For a multi--area
  model one would conduct the re-sampling of subdivisions within each
  area of the model.  
\item The list of re-sampled subdivisions is then used to extract
  data (with replacement so the same data set may be repeated several times
  in a given bootstrap sample).
\item For a single bootstrap Gadget model, the same list of re-sampled
  subdivisions is used to extract each likelihood data set i.e.
  length distributions, survey indices and age--length frequencies are
  extracted from the same spatial definition.
\item A Gadget model is fitted to the extracted bootstrap data set
  using the estimation procedure described above. 
\item The re-sampling process is repeated until the desired number of bootstrap
  samples are extracted, which in this case the total sample size is 100.
%\item The full dataset is extracted and 1000 bootstrap datasets created.
\end{itemize}

When re-sampling, data are forced to remain in the correct year and
time--step so re-sampling is based on sampling spatially the elementary
data units within a given modeled unit of time and space.
Thus, within a modeled spatial unit the bootstrap is a re-sampling of
subdivisions. This implicitly assumes data contained within each area
of the model to be independent and identically distributed. Independence
is justified by the definition of subdivisions. Furthermore treating them
as they were from the same distribution, i.e. bootstrap replicates,
appears to have little negative effect when compared to more
traditional methods \citep{lornahaddock}. 


The entire estimation procedure is repeated for each
bootstrap sample.  In particular, since the estimation procedure
includes an iterative re-weighting scheme, this re-weighting is repeated
for every bootstrap sample.  The point of this is that the bootstrap
procedure is no longer conditional on the weights.  The procedure as a
whole is quite computationally intensive but can easily be run in
parallel, e.g. on a computer cluster. 

\section{Model settings}
Ling in 5a is assumed to be fairly long lived and the maximum age is set at
15 with 15 acting also as a plus group and simulation goes back to 1982, 
maturing at age 10 the latest. Recruitment to the immature stock component 
occurs at age 3, in the $1^{st}$ quarter. The length range in the model was between 20 and 160, in 4 cm length intervals. 
Recruitment is set to occur at the end of the first time-step. 
An overview of the data-sets and model parameters used in the model
study is shown in Tables \ref{tbl:data} and \ref{tbl:parameters}
respectively. 





\begin{table}[ht]
\caption{Ling in 5a. Overview of the likelihood data used in the model. Survey
  indices are calculated from the length distributions and are dis-aggregated (``sliced'') into seven
  groups (Table \ref{Tab:si.agg}). Number of data-points refer to aggregated data  
  used as inputs in the Gadget model and represent the original
  data-set. All data can obtained from the Marine and Freshwater Research Institute,
  Iceland.} \label{tbl:data}
\vspace{0.2cm}
\resizebox{\columnwidth}{!}{%
\begin{tabular}{l|p{4cm}p{2cm}p{2cm}p{2.5cm}p{2cm}}
\toprule
Origin &  Time-span & Length group size & Num. data-points & Likelihood
\-function & Weight group \\ \hline

<<echo=FALSE,results='asis',message=FALSE,error=FALSE,warning=FALSE>>=
# mfdb_dplyr_sample(mdb) %>% 
#    filter(sampling_type %in% c('SEA','IGFS'),
#           species =='USK',
#           year>1981,
#           !is.na(age)) %>% 
#    group_by(sampling_type,data_source,gear) %>% 
#    summarise(num.fish=n(),num.samples=n_distinct(tow),min_year=min(year),max_year=max(year))
 wgr <- 
   fit$resTable %>% 
   select(-.id) %>% 
   names() %>%
   set_names(.,.) %>% 
   map(function(x){
     data_frame(group=grep(paste0('^',x,paste0('|\\.',x)),fit$resTable$.id,value=TRUE))
   }) %>% 
   bind_rows(.id="name") %>% 
   mutate(group=ifelse(grepl('si.20-50',group),'sind1',
                       ifelse(grepl('si.70-80',group),'sind2',
                              ifelse(grepl('gil.ldist',group),'comm',group))))
 
 fit$catchdist.fleets %>%
   filter(!is.na(number.x)) %>% 
   group_by(name) %>% 
   dplyr::summarise(quarters=step %>% unique() %>% sort() %>% paste(collapse=','),
             year.range=paste(min(year),max(year),sep='--'),n=n(),
             deltal = paste(median(upper-lower),'cm')) %>% 
   mutate(type = ifelse(grepl('aldist',name),'Age--length distributions','Length distributions'),
          origin = gsub('[a-z]+\\.([a-z]+)','\\1',name),
          lik.ref = ifelse(grepl('aldist',name),'eq:SSalk','eq:SSldist')) %>% 
   bind_rows(fit$stockdist %>% 
               group_by(name) %>% 
               dplyr::summarise(quarters=step %>% unique() %>% sort() %>% paste(collapse=','),
                         year.range=paste(min(year),max(year),sep='--'),n=n(),
                         deltal = paste(median(upper-lower),'cm')) %>% 
               mutate(type = 'Ratio of immature:mature by length group',
                      origin = gsub('[a-z]+\\.([a-z]+)','\\1',name),
                      lik.ref = 'eq:SSmat'),
             fit$sidat %>% 
               group_by(name) %>% 
               dplyr::summarise(quarters=step %>% unique() %>% sort() %>% paste(collapse=','),
                         year.range=paste(min(year),max(year),sep='--'),n=n(),
                         deltal = paste(lower,'--',upper,'cm')[1]) %>% 
               mutate(type = 'Survey indices',
                      origin = 'igfs',
                      lik.ref = 'eq:SSSI')) %>% 
   mutate(origin = ifelse(origin == 'igfs','March Survey','Commercial catches'),
          quarters = ifelse(quarters == '1,2,3,4','All quarters',
                            ifelse(quarters == '1','$1^{\\textup{st}}$','$2^{\\textup{nd}}$'))) %>%
   left_join(wgr) %>% 
   split(.$type) %>% 
   map(function(x){
     header <-"  & \\multicolumn{3}{l}{\\textbf{%s:}} \\\\" %>% sprintf(x$type[1])
     body <- "%s &  %s, %s & %s & %s  & See eq. \\ref{%s} & %s\\\\" %>% 
       sprintf(x$origin,x$quarters,x$year.range,x$deltal,x$n,x$lik.ref,x$group) %>% 
       paste(collapse='\n')
     paste(header,body,sep='\n')
   }) %>% 
   unlist() %>% 
   paste(collapse='\n') %>% 
   cat()
@

\bottomrule
\end{tabular}
}
\end{table}

\begin{table}
\caption{Ling in 5a. An overview of the estimated parameters in the
  model. }\label{tbl:parameters} 
\vspace{0.2cm}
\resizebox{\columnwidth}{!}{%
\begin{tabular}{p{5cm}|lp{5cm}p{2.5cm}}
Description & Notation & Comments & Formula\\ \hline  
Natural mortality & $M_a$ & Fixed at 0.15 for ages 3 to 15 & See eq. \ref{eq:stock}\\
Growth function & $k, L_\infty$ & Estimated from age--length
frequencies & See eq. \ref{eq:vonB}\\
Growth implementation & $\beta$ & $n$ is fixed at 15 length-groups &
See eq. \ref{eq:betabinom}\\
Fleet selection & $b_f$, $l_{50,f}$ & One set for each of the fleets
(Survey, Trawl, Longline, Gillnet and Foreign). The longline and foreign fleets have the same selection&  See eq. \ref{eq:suit} \\
Maturity ogive & $\lambda$, $l_{50}$ &  & See eq. \ref{eq:mat}\\
Length at recruitment & $l_0, \sigma_3$ &  Mean length (at age 1) and std. deviation in recruitment length. & See eq. \ref{eq:rec}\\
Number of recruits by year & $R_y$ & $y \in [1982,
2016]$. $\sigma_0$, i.e. std. deviation in recruitment length, based on
length distributions obtained in the autumn survey. & See eq. \ref{eq:rec}\\
Initial abundance at ages 3 -- 15 in 1982 by  & $\eta_{sa}$ & $a \in [3,
15^+]$. $\sigma_a^2$, i.e. variance in initial length at age $a$, based on
length distributions obtained in the spring survey.  & See eq. \ref{eq:init} and table \ref{tbl:sigmas}\\  
Survey catch-ability & $q_f$ & Intercept term in a log--linear relationship with
abundance. The slope term, $b_g$, is estimated for groups si.20-50 and si.50-60. Fixed to 1 for all other indices. & See eq. \ref{eq:SSSI}\\   
Length--weight relationship & $\mu_s, \omega_s $ & Estimated outside of the model & See eq. \ref{eq:lw}\\ \hdashline
Scalars & $R_c$, $I_{c,s}$, $F_0$ & Recruiment, initial numbers at age and initial fishing mortality (applied to all age groups) & \\
\hline
\end{tabular}
}
\end{table}


\begin{table}[ht]
\caption{Ling in 5a. Initial standard deviation in length by age, see eq. \ref{eq:init} for further details} \label{tbl:sigmas}
\vspace{0.2cm}
%\resizebox{\columnwidth}{!}{%
\begin{tabular}{l|r|l|r|l|r}
\toprule
Age &  $\sigma_a$ & Age &  $\sigma_a$ & Age &  $\sigma_a$  \\ \hline
<<sigmas,echo=FALSE,results='asis',message=FALSE,error=FALSE,warning=FALSE>>=
  mfdb_dplyr_sample(mdb) %>% 
  dplyr::filter(species == 'LIN',age >2,age < 16,!is.na(length))  %>% 
  dplyr::select(age,length) %>% 
  dplyr::collect(n=Inf) %>% 
  dplyr::group_by(age) %>% 
  dplyr::summarise(ms=sd(length,na.rm=TRUE)) %>% 
  dplyr::mutate(ms=ifelse(age>17,24.14,ms),
                ms=sprintf('%s & %.2f',age,ms),
                split = (age-3)%/%5,
                id = (age-3)%%5) %>% 
   dplyr::select(-age) %>% 
   tidyr::spread(split,ms,fill='') %>% 
   dplyr::select(-id) %>% 
  tidyr::unite(col,matches("."),sep=' & ') %>% 
   (function(x){
     paste(x$col,collapse = '\\\\ \n')
   }) %>% 
   paste0('\\\\') %>% 
   cat()
@
\hline
\end{tabular}
%}
\end{table}


\subsection{Natural mortality}
Choice of natural mortality ($M$) is problematic as is normally the
case in stock assessments.   Here $M$ is assumed to be constant with
age at 0.15. %except for the plus group where it is set at 0.45.

\subsection{Weight length relationship}
The parameters of the weight--length relationship used in eq. \ref{eq:lw} were estimated through the means of log-linear regression. Fig. \ref{fig:lw} shows the observed length-weight relation compared with the fitted values. 

<<lw,echo=FALSE,results='asis',fig.width=5, fig.height=3,cache=TRUE,warning=FALSE,message=FALSE,fig.cap='Ling in 5a. Observed length-weight relationship from the Icelandic Groundfish Survey. Estimated length weight relationship shown as a solid line.',fig.lp='fig:',cache=TRUE>>=
 lw.constants <- 
  mfdb_dplyr_sample(mdb) %>% 
  filter(species == 'LIN',
         sampling_type == 'IGFS',
         !is.na(weight)) %>% 
   select(length,weight) %>% 
   collect(n=Inf) 
 
 lw.constants %>% lm(log(weight/1e3)~log(length),.) %>% 
   broom::tidy() %>% 
   select(estimate) -> x
 
 x$estimate[1] <- exp(x$estimate[1])
 
 
 lw.constants %>% 
   mutate(p=x$estimate[1]*length^x$estimate[2]) %>% 
   ggplot(aes(length,weight/1e3,group=round(length,4))) + 
   geom_boxplot() + geom_line(aes(y=p,group=1)) + 
   ylim(c(0,40)) +
   theme_light() + labs(y='Weight (kg)', x='Length')
 
 
 @


\subsection{Fleets and selection}\label{subsec:FleetSel}
In the model there are four commercial fleets and one survey fleet.
The commercial fleets are the Icelandic longline and foreign--fleets, trawl and gillnet fleets.  The selection
is described by a logistic function and total catch in tonnes is
specified for each time-step.

\subsection{Iterative re-weighting, initial parameter- and
  optimisation settings}\label{subsec:ItW}
In order to assign weights to the individual likelihood components
the iterative re-weighting process described in \ref{iterRW} on page
\pageref{iterRW} was used.  The data-sets were grouped when
over-weighting them, the rationale was that similar data-sets should
contain similar information.  The grouping the likelihood
components, which is shown in table \ref{tbl:data}, was applied 
all survey indices together to prevent issues related to overfitting.


All runs (base and bootstrap) were started from the same initial
values.  The values and the boundaries are in Annex \ref{Ann:Par.base}
on page \pageref{Ann:Par.base}.  Settings for the optimising
algorithms are shown in Annex \ref{Ann:Optinfo} on page
\pageref{Ann:Optinfo}.  All runs, both individual weighting and final
runs converged.

Three types of scaling parameters were applied to the model parameters 
during the optimisation. First the recruitment level was scaled according 
to a common parameter, $R_c$, to allow the model to find the correct placement 
of the recruitment parameters. Similarly the intitial number at age for each 
stock component was scaled with common parameters, first a plain scalar $I_{c,s}$ 
and secondly by a common fishing mortality, $F_0$. These parameters were estimated.
\cleardoublepage


\section{Input data}
\subsection{Commercial catches}
\subsubsection{Landings}
In the model there are three commercial fleets, namely commercial longlines, gillnets, trawl and foreign vessels, and a survey fleet.
The longline and the foreign fleets have the same selection curve as the foreign catches,
mostly from the Faroe Islands and Norway, are assumed to be caught with
longlines (Table \ref{Tab:CommCatch}). The sources of landings of ling in 5a are four. For the period between 1993 to the present all landings of Icelandic vessels were recorded by the Directorate of Fisheries, and all landings in 5a after 2013. Prior to 1993 landings data from Icelandic vessel were recorded by Fiskifélagið, and foreign vessel prior to 2014 were obtained from Statlant and distributed to quarters in equal proportions.    

\begin{table}[!h]
\vspace{1mm}
\caption[]
{Ling in 5a.  Commercial catches in tonnes by 
  fleets, steps (3 month) and years.}\label{Tab:CommCatch}
\vspace{2mm}
\rotatebox{90}{\centering% \tiny
\scriptsize
\begin{tabular}{l | r r r r  |  r r r r | r r r r | r r r r  | r}
\toprule
Year & \mcol{4}{l}{Bottom trawl}& \mcol{4}{l}{Gilnets}& \mcol{4}{l}{Longline}& \mcol{4}{l}{Foreign} &Total\\ 
     &1 &2 &3 &4 &1 &2 &3 &4 &1 &2 &3 &4 &1 &2&3 &4 &  \\ \midrule
<<echo=FALSE,results='asis'>>=
mfdb_dplyr_sample(mdb) %>% 
   filter(species == 'LIN',
          sampling_type=='LND'|sampling_type=='FLND'&data_source%in% c('lods.foreign.landings','statlant.foreign.landings'),
          year %in% 1982:2016) %>% 
   mutate(quarter = floor((month-1)/3)+1,
          sampling_type = ifelse(sampling_type=='FLND','xforeign',
                                 ifelse(gear %in%  c('LLN','HLN'), 'lln',
                                        ifelse(gear %in% c('BMT','NPT','DSE','PSE','PGT','SHT'),'bmt','gil')))) %>% 
   group_by(year,quarter,sampling_type) %>% 
   summarise(lnd = sum(weight)/1e3) %>%
   arrange(year,quarter) %>% 
   collect(n=Inf) %>% 
   mutate(lnd=round(lnd,1),
          sampling_type = ifelse(sampling_type=='igfs',
                                 'survey',sampling_type)) %>% 
   unite(col,sampling_type,quarter) %>% 
   spread(col,lnd,fill=0) %>% 
   by_row(sum,.collate='rows',.to='total') %>%
   mutate(total = total - year) %>% 
   unite(col,year:total,sep=' & ') %>% 
   (function(x){
     paste(x$col,collapse = '\\\\ \n')
   }) %>% 
   paste0('\\\\') %>% 
   cat()
@


\bottomrule
\end{tabular}
\par}
\end{table}


\cleardoublepage

\subsubsection{Length distributions}
The data available for ling in 5a can be seen in
table \ref{Tab:CommCatchLD} which lists the number of available length
measurements from the Icelandic fleets by years and time steps.  Also
length distributions from the spring survey are included in the
model.  Length distributions for all fleets are on four cm basis. 
Entries were removed from the length distribution prior to model fitting as it was deemed likely that they would have undesirable effect on the fitting process. These entries were the samples from trawls in 1982 (q4), 1984 (q1), 1989 (q3), 1992 (q4) and 1998 (q3) as these had few than 20 fish sampled that year. From longlines all samples from 1993 (q3) were removed, as the data from that quarter originates from a single fishing trip and most likely the species was incorrectly assigned to the samples. From gillnets 1 sample from 2005 (q2) was remove as it only contained a single fish.  

\begin{table}[!h]
\vspace{1mm}
\caption[]
{Ling in 5a:. Number of available length measurements from
  from the three commercial fleets used as
  input data into the Gadget model by 
  years and steps (3 month). Numbers in brackets indicate the number of port- or towsamples.}\label{Tab:CommCatchLD}
\vspace{2mm}
\rotatebox{90}{\centering \tiny
\scriptsize
\begin{tabular}{l| r r r r |r r r r |r r r r | r  }
\toprule
Year & \mcol{4}{l}{Bottom trawl}& \mcol{4}{l}{Gilnets}& \mcol{4}{l}{Longlines}& \mcol{1}{l}{Survey}\\ 
     &1 &2 &3 &4 &1 &2 &3 &4 &1 &2 &3 &4&2  \\ \midrule
<<echo=FALSE,results='asis',cache=TRUE>>=
mfdb_dplyr_sample(mdb) %>% 
   filter(year %in% 1982:2016,
          sampling_type %in% c('IGFS','SEA'),
          data_source =='iceland-ldist',
          species == 'LIN') %>% 
   mutate(step = floor((month-1)/3)+1,
          sampling_type = ifelse(sampling_type=='IGFS','igfs',
                                 ifelse(gear %in%  c('LLN','HLN'), 'lln',
                                        ifelse(gear %in% c('BMT','NPT','DSE','PSE','PGT','SHT'),'bmt','gil')))) %>% 
   group_by(sampling_type,year,step) %>% 
   summarise(ntow=n_distinct(tow),n=sum(count)) %>% 
   collect(n=Inf) %>%
   ungroup() %>% 
   mutate(n=sprintf('%s (%s)', n, ntow),
          sampling_type = ifelse(sampling_type=='igfs','survey',sampling_type)) %>% 
   select(-ntow) %>% 
   unite(col,sampling_type,step) %>% 
   spread(col,n,fill='0 (0)')   %>% 
   unite(col,matches("."),sep=' & ') %>% 
   (function(x){
     paste(x$col,collapse = '\\\\ \n')
   }) %>% 
   paste0('\\\\') %>% 
   cat()
 
#  
# fit$catchdist.fleets %>% 
#    filter(grepl('^ldist',name)) %>% 
#    group_by(year,step,name) %>% 
#    summarise(n=round(sum(number.x,na.rm=TRUE))) %>% 
#    unite(col,name,step) %>% 
#    spread(col,n,fill=0)   %>% 
#    unite(col,matches("."),sep=' & ') %>% 
#    (function(x){
#      paste(x$col,collapse = '\\\\ \n')
#    }) %>% 
#    paste0('\\\\') %>% 
#    cat()
@

%\input{../Graphs/LDnoMes.tex}
\bottomrule
\end{tabular}
\par}
\end{table}

\subsection{Tuning data}
The tuning data used comes from the Icelandic spring survey.  The
spring survey abundance indices are aggregated into seven length
intervals (Table \ref{Tab:si.agg}, figures \ref{fig:siAggExpl} and
\ref{fig:BootInd}). The survey indices are defined as the total number
of fish caught in a survey within a certain length interval. 8 to 12 cm intervals are used for
the indices, except the smallest and the largest length intervals where larger intervals are used.  
The reason for these larger length intevals is to avoid getting a zero value
for these length groups in the bootstrap replicates.

\begin{table}[!h]
\vspace{1mm}
\caption[]
{Ling in 5a: Length aggregation of survey indices used for tuning the model.}\label{Tab:si.agg}
\vspace{2mm}
{\centering \tiny
\scriptsize
\begin{tabular}{l r r}
\toprule
Name& min& max \\ \midrule
<<echo=FALSE,results='asis',cache=TRUE>>=
fit$sidat %>% 
   group_by(name) %>%
   summarise(min=min(lower),
             max=max(upper)) %>% 
   unite(col,matches("."),sep=' & ') %>% 
   (function(x){
     paste(x$col,collapse = '\\\\ \n')
   }) %>% 
   paste0('\\\\') %>% 
   cat()
@



\bottomrule
\end{tabular}
\par}
\end{table}



 
 
 
\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=5,cache=TRUE,warning=FALSE,message=FALSE>>=
fit$catchdist.fleets %>% 
   filter(name=='ldist.igfs',year %in% 2010:2013) %>% 
   ggplot(aes(lower,number.x))+
   geom_rect(fill='gold',alpha=0.01,xmin=20,xmax=52,ymin=-Inf,ymax=Inf)+
   geom_rect(fill='gold',alpha=0.01,xmin=60,xmax=72,ymin=-Inf,ymax=Inf)+
   geom_rect(fill='gold',alpha=0.01,xmin=80,xmax=92,ymin=-Inf,ymax=Inf)+
   geom_rect(fill='gold',alpha=0.01,xmin=100,xmax=160,ymin=-Inf,ymax=Inf)+
   geom_line() + facet_wrap(~year) + xlim(c(20,120)) +
   theme_light() + labs(x='Length', y='Number observed') +
   geom_label(data=data_frame(year=2010:2013),
              aes(label=year,group=1),x=-Inf,y=Inf,size=3, vjust = 1.1,hjust=-0.1) +
   theme(strip.background = element_blank(),strip.text=element_blank())
@


%\includegraphics[width=0.9\linewidth]{../Graphs/SIaggExplainGraph.pdf}
\caption{Ling in 5a. Length distributions from the Icelandic Groundfish Survey and the yellow and white polygon represent the division into length aggregated abundance indices.}\label{fig:siAggExpl}
\end{figure}

\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=5,cache=TRUE,warning=FALSE,message=FALSE>>=
#load('../00-setup/bootstrap-data.Rdata')
# SI <- bind_rows(igfs.SI1a %>% bind_rows(.id='iter'),
#                 igfs.SI1b %>% bind_rows(.id='iter'),
#                 igfs.SI1c %>% bind_rows(.id='iter'),
#                 igfs.SI2a %>% bind_rows(.id='iter'),
#                 igfs.SI2b %>% bind_rows(.id='iter'),
#                 igfs.SI2c %>% bind_rows(.id='iter'),
#                 igfs.SI3a %>% bind_rows(.id='iter'))

 bootfit$sidat %>% 
   group_by(year,name) %>% 
   summarise(l=quantile(number.x,0.05),
             ll=quantile(number.x,0.25),
             m = median(number.x),
             uu=quantile(number.x,0.75),
             u=quantile(number.x,0.95)) %>% 
   ggplot(aes(year,m)) + 
   geom_ribbon(aes(ymin=l,ymax=u),alpha=0.3,fill='gold') +
   geom_ribbon(aes(ymin=ll,ymax=uu),alpha=0.7,fill='gold') +
   geom_line() +
   facet_wrap(~name,scale='free_y') + 
   geom_line(data=fit$sidat,aes(y=number.x,group=1),col='red') + 
   theme_light() + labs(x='Year',y='Index') +
   geom_label(data=fit$sidat %>%
              select(name) %>%
              distinct() %>% 
              mutate(label=name),
            aes(label=label,group=1),x=-Inf,y=Inf,size=3, vjust = 1.1,hjust=-0.1) +
  theme(strip.background = element_blank(),strip.text=element_blank())
 
@


%\includegraphics[width=0.9\linewidth]{../Graphs/BootInd.pdf}
\caption{Ling in 5a.  Time series of length aggregated indices used for
tuning (red line), black lines and shaded regions represents bootstrap median and 90\% intervals, respectively, of the
indices by year.}\label{fig:BootInd}
\end{figure}

\cleardoublepage
\subsection{Age data}\label{subsec:AgeData}
In table \ref{Tab:CommCatchALK} the available age data is listed by
fleet, year and time-step (quarter). Due to observed in length at age 
for ling above the age of 10, individuals that have been 
observed to be older than 11 are classified as 11 years and older. All available age data prior to 2001 was considered to be unreliable as the method of age determination changed. Age samples from longlines in quarter 2 of years 2002 and 2003 were omitted as there were only 20 otoliths aged from a single sample.  

\begin{table}[!h]
\vspace{1mm}
\caption[]
{Ling in 5a. Number of available aged otoliths 
  from the three commercial fleets  and the spring survey used as
  input data into the Gadget model by 
  years and steps (3 month).}\label{Tab:CommCatchALK}
\vspace{2mm}
\rotatebox{90}{\centering \tiny
\scriptsize
\begin{tabular}{l| r r r r | r r r r | r r r r  | r}
\toprule
Year & \mcol{4}{l}{Bottom trawl}& \mcol{4}{l}{Gilnets}& \mcol{4}{l}{Longlines}& \mcol{1}{l}{Survey}\\ 
     &1 &2 &3 &4&1 &2 &3 &4&1 &2 &3 &4&2 \\ \midrule
<<echo=FALSE,results='asis'>>=
mfdb_dplyr_sample(mdb) %>% 
   filter(year %in% 1999:2016,
          sampling_type %in% c('IGFS','SEA'),
          data_source =='iceland-aldist',
          species == 'LIN',
          !is.na(age)) %>% 
   mutate(step = floor((month-1)/3)+1,
          sampling_type = ifelse(sampling_type=='IGFS','igfs',
                                 ifelse(gear %in%  c('LLN','HLN'), 'lln',
                                        ifelse(gear %in% c('BMT','NPT','DSE','PSE','PGT','SHT'),'bmt','gil')))) %>% 
   group_by(sampling_type,year,step) %>% 
   summarise(ntow=n_distinct(tow),n=sum(count)) %>% 
   collect(n=Inf) %>%
   ungroup() %>% 
   mutate(n=sprintf('%s (%s)', n, ntow),
          sampling_type = ifelse(sampling_type=='igfs','survey',sampling_type)) %>% 
   select(-ntow) %>% 
   unite(col,sampling_type,step) %>% 
   spread(col,n,fill='0 (0)')   %>% 
   unite(col,matches("."),sep=' & ') %>% 
   (function(x){
     paste(x$col,collapse = '\\\\ \n')
   }) %>% 
   paste0('\\\\') %>% 
   cat() 
 
#  
# fit$catchdist.fleets %>% 
#    filter(grepl('^ldist',name)) %>% 
#    group_by(year,step,name) %>% 
#    summarise(n=round(sum(number.x,na.rm=TRUE))) %>% 
#    unite(col,name,step) %>% 
#    spread(col,n,fill=0)   %>% 
#    unite(col,matches("."),sep=' & ') %>% 
#    (function(x){
#      paste(x$col,collapse = '\\\\ \n')
#    }) %>% 
#    paste0('\\\\') %>% 
#    cat()
@
\bottomrule
\end{tabular}
\par}
\end{table}
\cleardoublepage
% 
%  \subsection{Maturity data}\label{subsec:MatData}
%  In table \ref{tbl:maturity} the available maturation data is listed by
%  year. 
%  \begin{table}[!h]
%  \vspace{1mm}
%  \caption[]
%  {Ling in 5a. Number of available maturity measurements the spring survey used as
%    input data into the Gadget model by 
%    year.}\label{Tab:matAtL}
%  \vspace{2mm}
%  {\centering
%  \scriptsize
%  \begin{tabular}{l|  r}
%  \toprule
%  Year &  Survey\\ \midrule
% <<echo=FALSE,results='asis'>>=
% mfdb_dplyr_sample(mdb) %>% 
%     filter(year %in% 1982:2016,
%            sampling_type =='IGFS',
%            data_source =='iceland-aldist',
%            species == 'LIN',
%            !is.na(maturity_stage)) %>% 
%     group_by(sampling_type,year) %>% 
%     summarise(ntow=n_distinct(tow),n=sum(count)) %>% 
%     collect(n=Inf) %>%
%     ungroup() %>% 
%     mutate(n=sprintf('%s (%s)', n, ntow)) %>% 
%     select(-c(ntow,sampling_type)) %>% 
%     #unite(col,sampling_type,step) %>% 
%     #spread(col,n,fill='0 (0)')   %>% 
%     unite(col,matches("."),sep=' & ') %>% 
%     (function(x){
%       paste(x$col,collapse = '\\\\ \n')
%     }) %>% 
%     paste0('\\\\') %>% 
%     cat() 
%   
% @
% \bottomrule
%  \end{tabular}
% \par}
% \end{table}

\section{Results}
\subsection{Iterative re-weighting}
Gadget allows for an extensive comparison to the fitted data-set. An
overall picture of the model fit is provided in table
\ref{Tab:SiW}. Overall the model is seen to fit the data relatively
well, compared to the best possible fit. In the final run the squared
residuals are seldomly larger than an order of 3
larger than the optimal fit. In no case is the final run the worst fit
to individual likelihood component. There are some indications of conflicts between the individual datasets, as can be read from the ratio between the best score and score when other components were upweighted. This is particularly notable between the survey indices and the compositional data and between index groups \texttt{sind1} and \texttt{sind2}. This is however more likely to be related to the fact that the model is able to fit the survey indices freely when the survey indices are upweigthed as illustrated by the final score ratios.  

Fig. \ref{fig:bootlik} shows the bootstrap distribution of contribution of individual datasets by time to the overall score, calculated using eq. \ref{eq:loglik}. Overall few outliers can be observed from the likelihood, the fit on age length distributions in the survey appears to be gradually improving from the first year of available age data (from 2001), which may be attributed to fewer samples in those years relative to the more recent years. The survey indices representing the smallest and third smallest length groups appear to have worse fit relative to their optimal fits that other indices, which is also apparent from table \ref{Tab:SiW}.  

Five bootstrap replicates exhibited a negliable amount of overcomsumption (between 4 to 9 grams) in 1993, a period of high fishing mortality, the effect of which is considered minimal.
\begin{table}[!h]
\vspace{1mm}
\caption[]
{Ling in 5a. Diagnostic from the iterative reweighing procedure. The
  lines denotes the likelihood component that was heavily weighted.
  Upper part is the value for each likelihood component, but the lower
  part denote the ratio of that component score to the score when it was upweighted.}\label{Tab:SiW}
\vspace{2mm}
\rotatebox{90}{%\tiny

<<echo=FALSE,results='asis',cache=TRUE>>=
header <- paste0(sprintf('\\begin{tabular}{l%s}',rep('p{0.7cm}',ncol(fit$resTable)-3) %>% paste(collapse='')),
                 '\\toprule \n',
                 'Component & ',
                 paste(head(names(fit$resTable)[-1],-2) %>% gsub('\\.','.\\\\-',.),collapse = ' & '),
                 "\\\\ \\midrule \n")
body1 <- 
  fit$resTable %>% 
  mutate(.id=ifelse(grepl('si.20-50',.id),'sind1',
                       ifelse(grepl('si.70-80',.id),'sind2',
                              ifelse(grepl('gil.ldist',.id),'comm',.id)))) %>% 
  select(-c(understocking,bounds)) %>% 
  mutate_all(function(x) if(is.numeric(x)) round(x,3) else x) %>% 
  unite(col,matches("."),sep=' & ') %>% 
   (function(x){
     paste(x$col,collapse = '\\\\ \n')
   }) %>% 
   paste0('\\\\')

body2 <- 
  fit$nesTable %>% 
  mutate(.id=ifelse(grepl('si.20-50',.id),'sind1',
                       ifelse(grepl('si.70-80',.id),'sind2',
                              ifelse(grepl('gil.ldist',.id),'comm',.id)))) %>% 
  select(-c(understocking,bounds)) %>% 
  mutate_all(function(x) if(is.numeric(x)) round(x,3) else x) %>% 
  unite(col,matches("."),sep=' & ') %>% 
  (function(x){
    paste(x$col,collapse = '\\\\ \n')
  }) %>% 
  paste0('\\\\')

paste(header,body1,
      '\\midrule\n \\\\ \n \\midrule\n', 
      body2,
      '\\bottomrule',
      sep = '\n') %>% 
  cat()

@



\end{tabular}
\par}
\end{table}


\begin{figure}
<<echo=FALSE,results='asis',fig.width=10, fig.height=15,cache=TRUE,warning=FALSE,message=FALSE>>=
gridExtra::grid.arrange(
bootfit$likelihoodsummary %>%
  filter(component!='understocking') %>% 
  #filter(!(model %in% c(22,70,73,24,56,64)))%>%
  left_join(SS$weights, by=c("component"="Component"),copy=TRUE) %>%
  filter(!grepl('si\\.',component)) %>% 
  mutate(year = as.numeric(year),
         step = as.numeric(step),
         t = year + (step-1)/4,
         score = likelihood.value*Weight) %>% 
  ggplot(aes(t,score,group=interaction(round(year)))) + geom_boxplot() +
  facet_wrap(~component,ncol=3) + theme_light() + ylim(c(0,750))+
  labs(x='Year',y='Weighted scored') +
   geom_label(data=fit$likelihoodsummary %>% 
                filter(!grepl('si\\.',component)) %>% 
                select(component) %>% 
                distinct(),
              aes(label=component,group=1),x=-Inf,y=Inf,size=3, vjust = 1.1,hjust=-0.1) +
   theme(strip.background = element_blank(),strip.text=element_blank()), 
bootfit$likelihoodsummary%>% 
  #filter(!(model %in% c(22,70,73,24,56,64))) %>%
  left_join(SS$weights, by=c("component"="Component"),copy=TRUE) %>%
  filter(grepl('si\\.',component)) %>% 
  mutate(score = likelihood.value*Weight,
         component = forcats::fct_reorder(component,gsub('si.([0-9]+)-*','\\1',component) %>% 
                                            as.numeric())) %>% 
  ggplot(aes(component,score))+ geom_boxplot() + theme_light() +
  labs(x='Component',y='Weighted scored'),ncol=1)

@

\caption{Ling in 5a. Boxplot of the bootstrap distribution of the weigthed likelihood component scores by time and component from the final model fits. } \label{fig:bootlik}

\end{figure}

\cleardoublepage 
\subsection{Parameter estimates}\label{subsec:ParEst}
In the base and bootstrap runs the estimates rarely hit the
boundaries. In figure \ref{fig:BSparHist} the
distributions of the bootstrap estimates for the growth, maturity and selection
parameters is shown.  For most of them the histogram indicates a nice
spread of the estimates. Two parameters, $\l_0$ and $\sigma_0$ which are related to the estimated growth, were estimated at the boundary in a substantial portion of the bootstrap trials, suggesting that these are illdetermined. The effect of this can be considered minimal as these have little effect on the estimated biomass and fishing mortality and are effectively fixed. $L_\infty$ was in the bulk of the bootstrap replicates estimated at the largest fish observed (or close). $L_\infty$ and $k$ are, as illustrated in fig. \ref{fig:VonBcorr}, fairly negatively correlated. 

Estimates of recruitment parameters are shown in figure
\ref{fig:RecruitParEst}.  In no case did they hit the boundaries and
the estimates show a fairly symmetric spread.  The spread in after 2013 large uncertainty, as is to be expected given the data available than can inform on recruitment.  The base run follows the median of the bootstrap
estimates closely. The estimated initial population is illustrated in fig. \ref{fig:AgeParEst}. As in the case of the estimated recruitment little concernable bias was observed in the based compared with the bootstrap medians. 


The bootstrap distribution of the catchability estimates, described in eq. \ref{eq:SSSI}, is illustrated in fig. \ref{fig:sislope}. The figure illustrates that the mode of the catchability is on centered around the 60 to 70 cm length group and starts to taper off for larger fish. 
\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=10,cache=TRUE,warning=FALSE,message=FALSE>>=
bootfit$params %>% 
  #filter(!(model %in% c(22,70,73,24,56,64)))%>% 
  filter(optimise==1, 
         !grepl('rec\\.[0-9]',switch),
         !grepl('init\\.[0-9]',switch),
         !grepl('scalar',switch)) %>%
  mutate(switch = gsub('^[A-Za-z]+\\.','',switch),
         value = ifelse(grepl('k$|mat1$',switch),0.001*value,value),
         label = forcats::fct_recode(switch,
                                     'beta' = "bbin",
                                     'alpha[g]' = 'gil.alpha',
                                      'l[50][g]' ='gil.l50',
                                     'alpha[l]' = 'lln.alpha',
                                      'l[50][l]' ='lln.l50',
                                     'alpha[t]' = 'bmt.alpha',
                                      'l[50][t]' ='bmt.l50',
                                     'alpha[s]' = 'igfs.alpha',
                                      'l[50][s]'='igfs.l50',
                                     'F[0]'='init.F',
                                     'L[infinity]'='Linf',
                                     'lambda'='mat1',
                                     'l[50]'='mat2',
                                     'sigma[0]'='rec.sd',
                                      'l[0]'='recl'  )) %>% 
  ggplot(aes(value)) + geom_histogram(fill='gray')+
  facet_wrap(~label,scale='free',labeller = label_parsed) +
  geom_vline(aes(xintercept=value),
             col='red',
             data=fit$params %>% 
               filter(optimise==1, 
                      !grepl('rec\\.[0-9]',switch),
                      !grepl('init\\.[0-9]',switch),
                      !grepl('scalar',switch)) %>% 
              mutate(switch = gsub('^[A-Za-z]+\\.','',switch),
                     value = ifelse(grepl('k$|mat1$',switch),0.001*value,value),
                     label = forcats::fct_recode(switch,
                                     'beta' = "bbin",
                                     'alpha[g]' = 'gil.alpha',
                                      'l[50][g]' ='gil.l50',
                                     'alpha[l]' = 'lln.alpha',
                                      'l[50][l]' ='lln.l50',
                                     'alpha[t]' = 'bmt.alpha',
                                      'l[50][t]' ='bmt.l50',
                                     'alpha[s]' = 'igfs.alpha',
                                      'l[50][s]'='igfs.l50',
                                     'F[0]'='init.F',
                                     'L[infinity]'='Linf',
                                     'lambda'='mat1',
                                     'l[50]'='mat2',
                                     'sigma[0]'='rec.sd',
                                      'l[0]'='recl' ))) +
  theme_light() +
  labs(x='Parameter value',y='% iterations')

#bootfit$params %>% filter(grepl('\\.Linf|\\.k',switch)) %>% select(model,switch,value) %>% spread(switch,value) %>% ggplot(aes(ling.k, ling.Linf))+ geom_point(alpha=0.5)
@


%\includegraphics[width=0.9\linewidth]{../Graphs/BSparHist.pdf}
\caption{Ling in 5a. Histogram of parameter estimates from 100
  bootstrap samples, the red line indicates the estimate from the base
run}\label{fig:BSparHist}
\end{figure}


\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=5,cache=TRUE,warning=FALSE,message=FALSE>>=
bootfit$params%>% 
  #filter(!(model %in% c(22,70,73,24,56,64))) %>% 
  filter(grepl('k$|Linf',switch)) %>% 
  mutate(switch = gsub('^[A-Za-z]+\\.','',switch),
         value = ifelse(grepl('k$|mat1$',switch),0.001*value,value)) %>% 
  select(model,switch,value) %>% 
  tidyr::spread(switch, value) %>% 
  ggplot(aes(k,Linf)) + geom_point() +
  geom_point(col='red',
             data=fit$params %>% 
               filter(grepl('k$|Linf',switch)) %>% 
               mutate(switch = gsub('^[A-Za-z]+\\.','',switch),
                      value = ifelse(grepl('k$|mat1$',switch),0.001*value,value)) %>% 
               select(switch,value) %>% 
               tidyr::spread(switch, value),
             pch='+',size=10) +
  theme_light() +
  labs(x='k',y=expression(L[infinity]))

#bootfit$params %>% filter(grepl('\\.Linf|\\.k',switch)) %>% select(model,switch,value) %>% spread(switch,value) %>% ggplot(aes(ling.k, ling.Linf))+ geom_point(alpha=0.5)
@


%\includegraphics[width=0.9\linewidth]{../Graphs/BSparHist.pdf}
\caption{Ling in 5a. X-Y scatterplot of the bootstrap estimates of $L_\infty$ and $k$. The red cross indicates the base run estimate.}\label{fig:VonBcorr}
\end{figure}

\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=12,cache=TRUE,warning=FALSE,message=FALSE>>=
bootfit$params %>% 
  filter(optimise==1, 
         !grepl('rec\\.[0-9]',switch),
         !grepl('init\\.[0-9]',switch),
         !grepl('scalar',switch)) %>%
  mutate(switch = gsub('^[A-Za-z]+\\.','',switch),
         value = ifelse(grepl('k$|mat1$',switch),0.001*value,value),
         label = forcats::fct_recode(switch,
                                     'beta' = "bbin",
                                     'alpha[c]' = 'comm.alpha',
                                     'l[50][c]' ='comm.l50',
                                     'alpha[s]' = 'igfs.alpha',
                                     'l[50][s]'='igfs.l50',
                                     'F[0]'='init.F',
                                     'L[infinity]'='Linf',
                                     'lambda'='mat1',
                                     'l[50]'='mat2',
                                     'sigma[0]'='rec.sd',
                                     'l[0]'='recl' )) %>%
  select(model,switch,value) %>% spread(switch,value) %>% select(-model) %>% 
  GGally::ggpairs() + 
  theme_light()
@

\caption{Ling in 5a. Pairs-plot of all parameters except those related to the number of recruits and initial number at age.}\label{fig:pairs}
\end{figure}


\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=5,cache=TRUE,warning=FALSE,message=FALSE>>=
bootfit$res.by.year %>% 
  #filter(!(model %in% c(22,70,73,24,56,64))) %>% 
  filter(grepl('imm',stock)) %>% 
  mutate(recruitment = recruitment/1e6) %>% 
  ggplot(aes(year,recruitment,group=round(year))) + geom_boxplot()+#geom_ribbon(aes(ymin=l,ymax=u),fill="gold") + geom_line() +
  geom_line(data=fit$res.by.year %>% filter(stock=='lingimm'),aes(y=recruitment/1e6,group=1),col='red') + 
  labs(y='Recruitment (in millions)',x='Year') + 
  theme_light()
@


%\includegraphics[width=0.9\linewidth]{../Graphs/RecruitParEst.pdf}
\caption{Ling in 5a. Boxplots of annual recruitment (age 3) bootstrap
  estimates, the red line indicates the estimate from the base
run.}\label{fig:RecruitParEst}
\end{figure}

\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=5,cache=TRUE,warning=FALSE,message=FALSE>>=
bootfit$stock.std%>% 
  #filter(!(model %in% c(22,70,73,24,56,64))) %>% 
  filter(year == 1982) %>% 
  group_by(model,age) %>% 
  summarise(number=sum(number)) %>% 
  ggplot(aes(age,number/1e6,group=round(age))) + geom_boxplot() +
  geom_line(data=fit$stock.std %>% 
              filter(year == 1982)%>% 
              group_by(age) %>% 
              summarise(number=sum(number)),aes(group=1),col='red') + 
  labs(y='Initial age structure (in millions)',x='Age') + 
  theme_light()
@
\caption{Ling in 5a. Boxplots of initial age structure bootstrap
  estimates, the red line indicates the estimate from the base
run.}\label{fig:AgeParEst}
\end{figure}



\begin{figure}[h]

<<echo=FALSE,results='asis',fig.width=10, fig.height=5,cache=TRUE,warning=FALSE,message=FALSE>>=
bootfit$sidat %>% 
  select(model,name,intercept) %>% 
  distinct() %>% 
  ggplot(aes(name,exp(intercept))) + geom_boxplot() + 
  geom_line(aes(group=1),col='red',
            data=fit$sidat %>% 
              select(name,intercept) %>% 
              distinct()) + 
  theme_light() + 
  labs(x='Survey index',y=expression(q[g]))
@


\caption{Ling in 5a. Boxplot of estimated catchability parameters, $q_g$, as a function of the survey index length group. }\label{fig:sislope}
\end{figure}
\clearpage

\subsection{Fit to individual data sets}
\subsubsection{Abundance indices}
The fit to the abundance indices is shown in fig.
\ref{fig:sifit} and as X-Y scatter plot on a log-scale in fig. \ref{fig:sixy}.    
For all length-group the fit is fairly good, as the model appears to follow the trends of the survey indices. For the larger length groups the model appears to be a tendency to predict a larger biomass than that was observed. When looking at the X-Y scatter plot the assumption of a slope of 1 (i.e. a linear relationship between index and abundance) appears to be fair for the larger length groups, combined with estimating the slope for the smallest two groups. 
\cleardoublepage
\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=10,cache=TRUE,warning=FALSE,message=FALSE>>=
bootfit$sidat %>% 
  #filter(!(model %in% c(22,70,73,24,56,64)))%>% 
  group_by(year,name) %>% 
  summarise(om=median(number.x,na.rm=TRUE),
            ou=quantile(number.x,0.975,na.rm=TRUE),
            ol=quantile(number.x,0.025,na.rm=TRUE),
            pm=median(predict,na.rm=TRUE),
            pu=quantile(predict,0.975,na.rm=TRUE),
            pl=quantile(predict,0.025,na.rm=TRUE)) %>% 
  ggplot(aes(year,om)) + geom_ribbon(aes(ymin=ol,ymax=ou),fill="gold") + geom_line() +
  geom_line(aes(y=pm),col='blue') +
  geom_line(aes(y=pu),col='blue',lty=2) +
  geom_line(aes(y=pl),col='blue',lty=2) +
  geom_line(aes(y=predict),col='red',data=fit$sidat) +
  geom_point(aes(y=number.x),data=fit$sidat) +
  facet_wrap(~name,scale='free_y',ncol=2) + theme_light() + 
  labs(y='Survey index',x='Year')+
  geom_label(data=fit$sidat %>%
              select(name,slope,sse) %>%
              distinct() %>% 
              mutate(label=paste(name,paste0('sse:',sse),sep='\n')),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1.1,hjust=-0.1) +
  theme(strip.background = element_blank(),strip.text=element_blank())
@

%\includegraphics[width=0.99\linewidth]{../Graphs/BSindfit.pdf}
\caption{Ling in 5a. Bootstrap distribution of the length aggregated abundance indices from the spring survey compared with the predicted survey indices. The black line is the bootstrap median and the yellow area is the 5 and 95\%
  percentiles of the bootstrapped indices, while the black points indicate the survey index.  
  The blue solid line is the median of the predicted indices from the
  bootstrap runs and the blue dotted line the 5 and 95\% percentile.  The red
  line is the predicted indices from the base model. }\label{fig:sifit}
  
  \end{figure}
  \begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=10,cache=TRUE,warning=FALSE,message=FALSE>>=
fit$sidat %>% 
  ggplot(aes(log(predict),log(number.x))) + 
  geom_line(aes(log(number.x),log(number.x)),lty=2) + 
  geom_line(aes(log(predict),log(predict)),lty=2) + 
  facet_wrap(~name, scale='free') + 
  geom_text(aes(label=year),size=3) + 
  #scale_x_log10() +
  #scale_y_log10() + 
  theme_light() +
  labs(y='log(Observed)',x='log(Predicted)')+
  geom_label(data=fit$sidat %>%
              select(name,slope,sse) %>%
              distinct() %>% 
              mutate(label=paste(name,paste0('sse:',sse),paste0("slope:",slope),sep='\n')),
            aes(label=label),x=Inf,y=-Inf,size=3, vjust = -0.1,hjust=1.1) +
  theme(strip.background = element_blank(),strip.text=element_blank())

@
  \caption{Ling 5a. Predicted survey index as a function of the observed values on the log-scale. The panels indicate the index length group, the dashed line denotes a line with slope 1 and the labels denote the year.}\label{fig:sixy}

\end{figure}

<<eval=FALSE,echo=FALSE>>=
bootfit$sidat %>% group_by(year,name) %>% dplyr::mutate(d=(number.x - predict)/predict) %>% dplyr::summarise(u=quantile(d,0.975),l=quantile(d,0.025),m=median(d)) %>% ggplot(aes(year,m)) + geom_ribbon(aes(ymin=l,ymax=u),fill='gold') + geom_line() + facet_wrap(~name) + geom_hline(yintercept=0,lty=2)
@


\subsubsection{Length distributions}
In figure \ref{fig:BootLd} examples of the bootstrapped data and their
data from the spring survey and commercial samples in the second quarter of 1996 and 2015 is shown. In general it is observed that the fit to the length distributions is fairly good. Notably the examples from 2015 contain cells that have a lot of samples/measurements (with the exception of the gillnet samples) which is apparent from the smoother empirical length distributions. In contrast fewer samples were taken in 1996, where only 218 measurements (2 samples) from the trawl fishery are available, and the survey samples are considerably fewer.  

Length distributions from the spring survey and commercial catches and
their respective fits are illustrated in figures \ref{fig:SurLdFit}
to \ref{fig:bubbleldist}, from the base model and all data. The fit to samples from the trawl and longline fishery is seen to improve in the terminal years, as data becomes more readily available, while the fit to gillnet samples is acceptable given the amount of available data. In comparison the fit to the survey length distributions is good. 

\begin{figure}[h]
 <<echo=FALSE,fig.width=12, fig.height=12,warning=FALSE,message=FALSE,eval=FALSE>>=
bootfit$catchdist.fleets%>% 
  #filter(!(model %in% c(22,70,73,24,56,64))) %>%
  filter(year==2015,step==2) %>%
  mutate(groupy=ifelse(grepl('aldist',name),age,lower)) %>% 
  group_by(name,groupy,model) %>% 
  dplyr::summarise(o=sum(observed,na.rm=TRUE),
                   p=sum(predicted)) %>% 
  group_by(name,groupy) %>% 
  dplyr::summarise(om=median(o),
                   pm=median(p),
                   ou=quantile(o,0.975),
                   pu=quantile(p,0.975),
                   ol=quantile(o,0.025),
                   pl=quantile(p,0.025)) %>% 
  ungroup() %>% 
  mutate(groupy=gsub('age','',groupy) %>% as.numeric()) %>% 
  ggplot(aes(groupy,om)) + 
  geom_ribbon(aes(ymin=pl,ymax=pu),fill='gold') + 
  geom_point(col='darkgreen') + 
  geom_segment(aes(xend=groupy,yend=ou,y=ol),col='darkgreen') + 
  facet_wrap(~name,scale='free') + theme_light() + 
  geom_line(aes(y=pm)) + #xlim(c(25,55)) + 
#  geom_label(x=70,y=0.065,aes(label=year),size=3) + 
#  geom_text(x=95,y=0.04,angle=90,aes(label=paste0('n = ',round(total.catch))),size=3) +
  theme(strip.background = element_blank(),strip.text=element_blank()) + 
  xlab('Length') + ylab('Proportion') + 
  #theme(axis.text.y = element_blank()) +
  geom_label(data=fit$catchdist.fleets %>% select(name) %>% distinct(),
            aes(label=name),x=-Inf,y=Inf,size=3, vjust = 2,hjust=-0.1) 
@

 <<echo=FALSE,fig.width=12, fig.height=8,warning=FALSE,message=FALSE>>=
bootfit$catchdist.fleets%>% 
  #filter(!(model %in% c(22,70,73,24,56,64))) %>%
  filter(year %in% c(1996,2015),step==2,
         grepl('^ldist',name)) %>%
  #mutate(groupy=ifelse(grepl('aldist',name),age,lower)) %>% 
  group_by(name,lower,model,year) %>% 
  dplyr::summarise(o=sum(observed,na.rm=TRUE),
                   p=sum(predicted)) %>% 
  group_by(name,lower,year) %>% 
  dplyr::summarise(om=median(o),
                   pm=median(p),
                   ou=quantile(o,0.975),
                   pu=quantile(p,0.975),
                   ol=quantile(o,0.025),
                   pl=quantile(p,0.025)) %>% 
  ungroup() %>% 
#  mutate(groupy=gsub('age','',groupy) %>% as.numeric()) %>% 
  ggplot(aes(lower,om)) + 
  geom_ribbon(aes(ymin=pl,ymax=pu),fill='gold') + 
  geom_point(col='darkgreen') + 
  geom_segment(aes(xend=lower,yend=ou,y=ol),col='darkgreen') + 
  facet_wrap(~name+year,scale='free') + theme_light() + 
  geom_line(aes(y=pm)) +
  geom_line(aes(y=predicted),col='red', 
            data= fit$catchdist.fleets %>% 
                filter(year %in% c(1996,2015),step==2,
                       grepl('^ldist',name)))  +
  
  #xlim(c(25,55)) + 
#  geom_label(x=70,y=0.065,aes(label=year),size=3) + 
#  geom_text(x=95,y=0.04,angle=90,aes(label=paste0('n = ',round(total.catch))),size=3) +
  theme(strip.background = element_blank(),strip.text=element_blank()) + 
  xlab('Length') + ylab('Proportion') + 
  #theme(axis.text.y = element_blank()) +
  geom_label(data=fit$catchdist.fleets %>% 
               filter(year %in% c(1996,2015),step==2,
                      grepl('^ldist',name)) %>% 
               select(name,year) %>% distinct() %>% 
               mutate(label = paste(name,year,sep=' - ')),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 2,hjust=-0.1) 
@


\caption{Bootstrap length distribution from both survey and commercial samples compared with model estimates. Green points and vertical bars denote the median and 90\% interval of the bootsrap distribution of observed values, while the solid lines and golden ribbon the median and 90\% intevals of the bootstrapped estimates by the model. The solid red line indicates the fit from the baseline model.}\label{fig:BootLd}
\end{figure}




\begin{figure}[h]
 <<echo=FALSE,fig.width=12, fig.height=12,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  filter(name=='ldist.igfs') %>% 
  ggplot(aes(lower,observed)) + geom_point(col='green') + 
  geom_segment(aes(xend=lower,yend=0),col='green') + 
  facet_wrap(~year) + theme_light() + 
  geom_line(aes(y=predicted)) + #xlim(c(25,55)) + 
#  geom_label(x=70,y=0.065,aes(label=year),size=3) + 
#  geom_text(x=95,y=0.04,angle=90,aes(label=paste0('n = ',round(total.catch))),size=3) +
  theme(strip.background = element_blank(),strip.text=element_blank()) + 
  xlab('Length') + ylab('Proportion') + 
  #theme(axis.text.y = element_blank()) +
  geom_label(data=data_frame(year=1985:2016),
            aes(label=year),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.1) 
@
%\caption{Length distribution from survey. Points denote the observed values,
%  solid lines the predictions by the base model.}\label{fig:BootLd}
%\vspace{1cm}

%\begin{figure}[h]
  %\includegraphics[width=0.99\linewidth]{../Graphs/SurLdBaseFit.pdf}
\caption{Length distribution from survey. Points denote the observed values,
  solid lines the predictions by the base model.}\label{fig:SurLdFit}
\end{figure}
\cleardoublepage

\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=15,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  filter(name=='ldist.lln') %>% 
  #unite(year,year,step,sep = ', q') %>% 
  ggplot(aes(lower,observed)) + geom_point(col='green',size=0.5) + 
  geom_segment(aes(xend=lower,yend=0),col='green') + 
  facet_wrap(~year+step,drop=FALSE,ncol=8) + theme_light() + 
  geom_line(aes(y=predicted)) + xlim(c(25,160)) + 
#  geom_label(x=50,y=0.12,aes(label=sprintf('%s, q%s',year,step))) + 
#  geom_text(x=140,y=0.07,angle=90,aes(label=paste0('n = ',round(total.catch)))) +
  xlab('Length') + ylab('Proportion') + 
  theme(strip.background = element_blank(),strip.text = element_blank()) + 
  geom_label(data=expand.grid(year=1994:2016,step=1:4) %>% mutate(label=paste(year,step,sep=', ')),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.)
@
\caption{Length distribution from the longline fleet. Points denote the observed values,
  solid lines the predictions by the base
  model.}\label{fig:llnBaseFit}
\end{figure}



\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=15,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  filter(name=='ldist.bmt') %>% 
  #unite(year,year,step,sep = ', q') %>% 
  ggplot(aes(lower,observed)) + geom_point(col='green',size=0.5) + 
  geom_segment(aes(xend=lower,yend=0),col='green') + 
  facet_wrap(~year+step,drop=FALSE,ncol=8) + theme_light() + 
  geom_line(aes(y=predicted)) + xlim(c(25,160)) + 
#  geom_label(x=50,y=0.12,aes(label=sprintf('%s, q%s',year,step))) + 
#  geom_text(x=140,y=0.07,angle=90,aes(label=paste0('n = ',round(total.catch)))) +
  xlab('Length') + ylab('Proportion') + 
  theme(strip.background = element_blank(),strip.text = element_blank()) + 
  geom_label(data=expand.grid(year=c(1982:1987,1995:2016),step=1:4) %>% 
               mutate(label=paste(year,step,sep=', ')),
             aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.)
@
\caption{Length distribution from the bottom trawl fleet. Points denote the observed values,
  solid lines the predictions by the base
  model.}\label{fig:bmtBaseFit}
\end{figure}


\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=15,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  filter(name=='ldist.gil') %>% 
  #unite(year,year,step,sep = ', q') %>% 
  ggplot(aes(lower,observed)) + geom_point(col='green',size=0.5) + 
  geom_segment(aes(xend=lower,yend=0),col='green') + 
  facet_wrap(~year+step,drop=FALSE,ncol=8) + theme_light() + 
  geom_line(aes(y=predicted)) + xlim(c(25,160)) + 
#  geom_label(x=50,y=0.12,aes(label=sprintf('%s, q%s',year,step))) + 
#  geom_text(x=140,y=0.07,angle=90,aes(label=paste0('n = ',round(total.catch)))) +
  xlab('Length') + ylab('Proportion') + 
  theme(strip.background = element_blank(),strip.text = element_blank()) + 
  geom_label(data=expand.grid(year=c(1982:1983,1992:2016),step=1:4) %>% 
                                mutate(label=paste(year,step,sep=', ')),
            aes(label=label),x=-Inf,y=Inf,size=2, vjust = 1,hjust=-0.)
@
\caption{Length distribution from the gillnet fleet. Points denote the observed values,
  solid lines the predictions by the base
  model.}\label{fig:gilBaseFit}
\end{figure}


\begin{figure}[h]

<<bubbleplot,fig.width=10, fig.height=7,warning=FALSE,message=FALSE,cache=TRUE,echo=FALSE>>=
fit$catchdist.fleets %>% 
  left_join(SS$weights %>% rename(name=Component)) %>% 
  filter(!grepl('aldist',name)) %>% 
  ggplot(aes(year+(step-1)/4,avg.length,size=abs((observed-predicted)*sqrt(Weight)), 
             col=as.factor(sign((observed-predicted))))) + 
  geom_point() + facet_wrap(~name)  + 
  theme_light() + scale_color_manual(values=c('darkblue','red')) + 
  scale_size_area() + theme(legend.position = 'none') + 
  labs(x='Year',y='Length')
@
\caption{Ling in 5.a. Standardised residual plots for the fitted length distribution from the commercial and survey fleets. Red points denot a model underestimate and blue points an overestimated. The size of the points denote the scale of the standardised residual.}\label{fig:bubbleldist}
\end{figure}


\clearpage
\subsection{Age--length distributions}
In fig. \ref{fig:BootALd} examples of the bootstraped proportions at age compared with model estimates from commercial and survey age samples. In general the model appears to capture the proportions at in the commercial catches (fig. \ref{fig:aldist.lln} to \ref{fig:aldist.gil}), while some discrepancy is observed within quarters of the same year. Fig. \ref{fig:BootALd} illustrates this where samples within the same quarters exhibit different proportion at age, but overall the central tendency within year and/or gear is captured. 


Growth in the model estimated based on the age-length distribution. The model fit to the available information on growth can be observed from figures \ref{fig:igfs.gr} to \ref{fig:gil.gr} from survey to gillnet samples respectively. In general the model appears to fit the observed growth quite well until the age of 11 where the average length of the samples 11 years and older appears to be higher than the model predicts. 

\begin{figure}[h]

 <<echo=FALSE,fig.width=12, fig.height=8,warning=FALSE,message=FALSE>>=
bootfit$catchdist.fleets%>% 
  #filter(!(model %in% c(22,70,73,24,56,64))) %>%
  filter(year %in% c(2008:2016),step==2,
         grepl('aldist',name)) %>%
  #mutate(groupy=ifelse(grepl('aldist',name),age,lower)) %>% 
  group_by(name,age,model,year) %>% 
  dplyr::summarise(o=sum(observed,na.rm=TRUE),
                   p=sum(predicted)) %>% 
  group_by(name,age,year) %>% 
  dplyr::summarise(om=median(o),
                   pm=median(p),
                   ou=quantile(o,0.975),
                   pu=quantile(p,0.975),
                   ol=quantile(o,0.025),
                   pl=quantile(p,0.025)) %>% 
  ungroup() %>% 
  mutate(age=gsub('age','',age) %>% as.numeric()) %>% 
  ggplot(aes(age,om)) + 
  geom_ribbon(aes(ymin=pl,ymax=pu),fill='gold') + 
  geom_point(col='darkgreen') + 
  geom_segment(aes(xend=age,yend=ou,y=ol),col='darkgreen') + 
  facet_grid(name~year,scale='free') + theme_light() + 
  geom_line(aes(y=pm)) +
  geom_line(aes(y=predicted),col='red', 
            data= fit$catchdist.fleets %>%
              filter(year %in% c(2008:2016),step==2,
                     grepl('aldist',name)) %>% 
              mutate(age=gsub('age','',age) %>% as.numeric()) %>%
              group_by(year,age,name) %>% 
              dplyr::summarise(predicted=sum(predicted)))  +
  
  #xlim(c(25,55)) + 
#  geom_label(x=70,y=0.065,aes(label=year),size=3) + 
#  geom_text(x=95,y=0.04,angle=90,aes(label=paste0('n = ',round(total.catch))),size=3) +
#  theme(strip.background = element_blank(),strip.text=element_blank()) + 
  xlab('Age') + ylab('Proportion')# + 
  #theme(axis.text.y = element_blank()) +
#  geom_label(data=fit$catchdist.fleets %>% 
#               filter(year %in% c(2008:2016),step==2,
#                      grepl('aldist',name)) %>% 
#               select(name,year) %>% distinct() %>% 
#               mutate(label = paste(name,year,sep='\n')),
#            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 2,hjust=-0.1) 
@


\caption{Bootstrap age distribution from both survey and commercial samples compared with model estimates from 2008 onwards in quarter 2. Green points and vertical bars denote the median and 5 and 95\% percentiles of the bootsrap distribution of observed values, while the solid lines and golden ribbon the median and 5 and 95\% percentiles of the bootstrapped estimates by the model. The solid red line indicates the fit from the baseline model. Note that age 11 is a plus group.}\label{fig:BootALd}
\end{figure}





\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=7,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  dplyr::filter(name=='aldist.igfs') %>%
  dplyr::mutate(age=as.numeric(gsub('age','',age)), 
                length=as.numeric(gsub('len','',length))) %>% 
  dplyr::group_by(year,age,step,total.catch) %>% 
  dplyr::summarise(o=sum(observed,na.rm=TRUE),
                   p=sum(predicted)) %>% 
  dplyr::mutate(o=ifelse(o==0,NA,o)) %>% 
  ggplot(aes(age,o)) + geom_point(col='green',size=0.5) + 
  geom_segment(aes(xend=age,yend=0),col='green') + 
  facet_wrap(~year) + 
  theme_bw() + geom_line(aes(y=p)) + 
#  geom_label(x=50,y=0.12,aes(label=sprintf('%s, q%s',year,step))) + 
#  geom_text(x=140,y=0.07,angle=90,aes(label=paste0('n = ',round(total.catch)))) +
  theme(strip.background = element_blank(),strip.text = element_blank()) + 
  xlab('Age') + ylab('Proportion') + 
  geom_label(data=fit$catchdist.fleets %>% 
              filter(name=='aldist.igfs') %>% 
              select(year) %>% 
              distinct() %>% 
              mutate(label=year),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.) + 
  scale_x_continuous(breaks = seq(0,100,by=2))


@
\caption{Age distribution from the March survey. Points denote the observed values,
  solid lines the predictions by the base
  model. }\label{fig:aldist.igfs}
\end{figure}

\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=10,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  dplyr::filter(name=='aldist.lln') %>%
  dplyr::mutate(age=as.numeric(gsub('age','',age)), 
                length=as.numeric(gsub('len','',length))) %>% 
  dplyr::group_by(year,age,step,total.catch) %>% 
  dplyr::summarise(o=sum(observed,na.rm=TRUE),
                   p=sum(predicted)) %>% 
  dplyr::mutate(o=ifelse(o==0,NA,o)) %>% 
  ggplot(aes(age,o)) + geom_point(col='green',size=0.5) + 
  geom_segment(aes(xend=age,yend=0),col='green') + 
  facet_wrap(~year+step) + 
  theme_bw() + geom_line(aes(y=p)) + 
#  geom_label(x=50,y=0.12,aes(label=sprintf('%s, q%s',year,step))) + 
#  geom_text(x=140,y=0.07,angle=90,aes(label=paste0('n = ',round(total.catch)))) +
  theme(strip.background = element_blank(),strip.text = element_blank()) + 
  xlab('Age') + ylab('Proportion') + 
  geom_label(data=fit$catchdist.fleets %>% 
              filter(name=='aldist.lln') %>% 
              select(year,step) %>% 
              distinct() %>% 
              mutate(label=paste(year,step,sep=', ')),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.)+ 
  scale_x_continuous(breaks = seq(0,100,by=2))
@
\caption{Age distribution from the longline fleet. Points denote the observed values,
  solid lines the predictions by the base
  model.  Note that age 11 is a plus group.}\label{fig:aldist.lln}
\end{figure}

\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=10,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  dplyr::filter(name=='aldist.bmt') %>%
  dplyr::mutate(age=as.numeric(gsub('age','',age)), 
                length=as.numeric(gsub('len','',length))) %>% 
  dplyr::group_by(year,age,step,total.catch) %>% 
  dplyr::summarise(o=sum(observed,na.rm=TRUE),
                   p=sum(predicted)) %>% 
  dplyr::mutate(o=ifelse(o==0,NA,o)) %>% 
  ggplot(aes(age,o)) + geom_point(col='green',size=0.5) + 
  geom_segment(aes(xend=age,yend=0),col='green') + 
  facet_wrap(~year+step) + 
  theme_bw() + geom_line(aes(y=p)) + 
#  geom_label(x=50,y=0.12,aes(label=sprintf('%s, q%s',year,step))) + 
#  geom_text(x=140,y=0.07,angle=90,aes(label=paste0('n = ',round(total.catch)))) +
  theme(strip.background = element_blank(),strip.text = element_blank()) + 
  xlab('Age') + ylab('Proportion') + 
  geom_label(data=fit$catchdist.fleets %>% 
              filter(name=='aldist.bmt') %>% 
              select(year,step) %>% 
              distinct() %>% 
              mutate(label=paste(year,step,sep=', ')),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.)+ 
  scale_x_continuous(breaks = seq(0,100,by=2))
@
\caption{Age distribution from the bottom trawl fleet. Points denote the observed values,
  solid lines the predictions by the base
  model.  Note that age 11 is a plus group.}\label{fig:aldist.bmt}
\end{figure}


\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=10,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  dplyr::filter(name=='aldist.gil') %>%
  dplyr::mutate(age=as.numeric(gsub('age','',age)), 
                length=as.numeric(gsub('len','',length))) %>% 
  dplyr::group_by(year,age,step,total.catch) %>% 
  dplyr::summarise(o=sum(observed,na.rm=TRUE),
                   p=sum(predicted)) %>% 
  dplyr::mutate(o=ifelse(o==0,NA,o)) %>% 
  ggplot(aes(age,o)) + geom_point(col='green',size=0.5) + 
  geom_segment(aes(xend=age,yend=0),col='green') + 
  facet_wrap(~year+step) + 
  theme_bw() + geom_line(aes(y=p)) + 
#  geom_label(x=50,y=0.12,aes(label=sprintf('%s, q%s',year,step))) + 
#  geom_text(x=140,y=0.07,angle=90,aes(label=paste0('n = ',round(total.catch)))) +
  theme(strip.background = element_blank(),strip.text = element_blank()) + 
  xlab('Age') + ylab('Proportion') + 
  geom_label(data=fit$catchdist.fleets %>% 
              filter(name=='aldist.gil') %>% 
              select(year,step) %>% 
              distinct() %>% 
              mutate(label=paste(year,step,sep=', ')),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.)+ 
  scale_x_continuous(breaks = seq(0,100,by=2))
@
\caption{Age distribution from the gillnet fleet. Points denote the observed values,
  solid lines the predictions by the base
  model.  Note that age 11 is a plus group.}\label{fig:aldist.gil}
\end{figure}




\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=8,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  filter(name=='aldist.igfs') %>% 
  group_by(year,step,age) %>% 
  mutate(o=observed/sum(observed,na.rm=TRUE),p=predicted/sum(predicted)) %>% 
  select(year,step,age,length,observed,o,predicted,p) %>% 
  ungroup() %>% 
  mutate(age=as.numeric(gsub('age','',age)), 
         length=as.numeric(gsub('len','',length))) %>% 
  group_by(year,step,age) %>% 
  summarise(o.ml=sum(o*length,na.rm=TRUE),
            o.sl=sqrt(sum(o*(length - o.ml)^2,na.rm=TRUE)),
            p.ml=sum(p*length),
            p.sl=sqrt(sum(p*(length - p.ml)^2))) %>% 
  mutate(o.ml=ifelse(o.ml==0,NA,o.ml),
         o.sl=ifelse(o.sl==0,NA,o.sl),
         upper = p.ml+1.96*p.sl,
         lower = p.ml-1.96*p.sl,
         o.upper = o.ml+1.96*o.sl,
         o.lower = o.ml-1.96*o.sl) %>% 
  ggplot(aes(age,o.ml)) + 
  geom_ribbon(fill='gold',aes(ymax=upper,ymin=lower))+
  geom_point(size=0.5) + 
  geom_line(aes(y=p.ml),col='red')  + 
  geom_linerange(aes(ymax=o.upper,ymin=o.lower))+
  geom_label(data=data_frame(year=2001:2016),
            aes(label=year),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.) +
  facet_wrap(~year) + 
  theme_light() + labs(x='Age',y='Average length') +
  theme(strip.background = element_blank(),strip.text=element_blank())+ 
  scale_x_continuous(breaks = seq(0,100,by=2))

# 
# mfdb_dplyr_sample(mdb) %>% 
#   filter(species == 'LIN',data_source=='iceland-aldist',!is.na(age)) %>% 
#   collect(n=Inf)->tmp
# 
# tmp2 <- 
# bootfit$catchdist.fleets %>% 
#   filter(grepl('aldist',name)) %>% 
#     group_by(year,step,age,model,name) %>% 
#   mutate(o=observed/sum(observed,na.rm=TRUE),p=predicted/sum(predicted)) %>% 
#   select(year,step,age,length,observed,o,predicted,p) %>% 
#   ungroup() %>% 
#   mutate(age=as.numeric(gsub('age','',age)), 
#          length=as.numeric(gsub('len','',length))) %>% 
#   group_by(year,step,age,model,name) %>% 
#   summarise(o.ml=sum(o*length,na.rm=TRUE),
#             o.sl=sqrt(sum(o*(length - o.ml)^2,na.rm=TRUE)),
#             p.ml=sum(p*length),
#             p.sl=sqrt(sum(p*(length - p.ml)^2))) %>% 
#   mutate(o.ml=ifelse(o.ml==0,NA,o.ml),
#          o.sl=ifelse(o.sl==0,NA,o.sl),
#          upper = p.ml+1.96*p.sl,
#          lower = p.ml-1.96*p.sl,
#          o.upper = o.ml+1.96*o.sl,
#          o.lower = o.ml-1.96*o.sl) %>% 
#   ggplot(aes(age,o.ml,group=interaction(age,name),fill=name)) + 
#   geom_boxplot() + #facet_wrap(~year) +
#   geom_boxplot(aes(y=p.ml),alpha=0.1)
@
\caption{Ling in 5a. Fitted length at age by year compared to observed values from the Icelandic spring survey. The black point and vertical bar denotes the observed mean and 95\% confidence intervals  of length at age, while the golden ribbon and red line indicates the model estimates.  Note that age 11 is a plus group and empty panels indicates lack of measurements.}\label{fig:igfs.gr}
\end{figure}



\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=8,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  filter(name=='aldist.lln') %>% 
  group_by(year,step,age) %>% 
  mutate(o=observed/sum(observed,na.rm=TRUE),p=predicted/sum(predicted)) %>% 
  select(year,step,age,length,observed,o,predicted,p) %>% 
  ungroup() %>% 
  mutate(age=as.numeric(gsub('age','',age)), 
         length=as.numeric(gsub('len','',length))) %>% 
  group_by(year,step,age) %>% 
  summarise(o.ml=sum(o*length,na.rm=TRUE),
            o.sl=sqrt(sum(o*(length - o.ml)^2,na.rm=TRUE)),
            p.ml=sum(p*length),
            p.sl=sqrt(sum(p*(length - p.ml)^2))) %>% 
  mutate(o.ml=ifelse(o.ml==0,NA,o.ml),
         o.sl=ifelse(o.sl==0,NA,o.sl),
         upper = p.ml+1.96*p.sl,
         lower = p.ml-1.96*p.sl,
         o.upper = o.ml+1.96*o.sl,
         o.lower = o.ml-1.96*o.sl) %>% 
  ggplot(aes(age,o.ml)) + geom_ribbon(fill='gold',aes(ymax=upper,ymin=lower))+geom_point(size=0.5) + 
  geom_line(aes(y=p.ml),col='red')  + geom_linerange(aes(ymax=o.upper,ymin=o.lower))+
  facet_wrap(~year+step) + 
  theme_light() + xlab('Age') + ylab('Average length') +
  geom_label(data=fit$catchdist.fleets %>% 
              filter(name=='aldist.lln') %>% 
              select(year,step) %>% 
              distinct() %>% 
              mutate(label=paste(year,step,sep=', ')),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.) +
  theme(strip.background = element_blank(),strip.text=element_blank())+ 
  scale_x_continuous(breaks = seq(0,100,by=2))
@
\caption{Ling in 5a. Fitted length at age by year compared to observed values from the longline samples. The black point and vertical bar denotes the observed mean and 95\% confidence intervals of length at age, while the golden ribbon and red line indicates the model estimates.}\label{fig:lln.gr}
\end{figure}


\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=8,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  filter(name=='aldist.bmt') %>% 
  group_by(year,step,age) %>% 
  mutate(o=observed/sum(observed,na.rm=TRUE),p=predicted/sum(predicted)) %>% 
  select(year,step,age,length,observed,o,predicted,p) %>% 
  ungroup() %>% 
  mutate(age=as.numeric(gsub('age','',age)), 
         length=as.numeric(gsub('len','',length))) %>% 
  group_by(year,step,age) %>% 
  summarise(o.ml=sum(o*length,na.rm=TRUE),
            o.sl=sqrt(sum(o*(length - o.ml)^2,na.rm=TRUE)),
            p.ml=sum(p*length),
            p.sl=sqrt(sum(p*(length - p.ml)^2))) %>% 
  mutate(o.ml=ifelse(o.ml==0,NA,o.ml),
         o.sl=ifelse(o.sl==0,NA,o.sl),
         upper = p.ml+1.96*p.sl,
         lower = p.ml-1.96*p.sl,
         o.upper = o.ml+1.96*o.sl,
         o.lower = o.ml-1.96*o.sl) %>% 
  ggplot(aes(age,o.ml)) + geom_ribbon(fill='gold',aes(ymax=upper,ymin=lower))+geom_point(size=0.5) + 
  geom_line(aes(y=p.ml),col='red')  + geom_linerange(aes(ymax=o.upper,ymin=o.lower))+
  facet_wrap(~year+step) + 
  theme_light() + xlab('Age') + ylab('Average length') +
  geom_label(data=fit$catchdist.fleets %>% 
              filter(name=='aldist.bmt') %>% 
              select(year,step) %>% 
              distinct() %>% 
              mutate(label=paste(year,step,sep=', ')),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.) +
  theme(strip.background = element_blank(),strip.text=element_blank())+ 
  scale_x_continuous(breaks = seq(0,100,by=2))
@
\caption{Ling in 5a. Fitted length at age by year compared to observed values from the bottom trawl samples. The black point and vertical bar denotes the observed mean and  95\% confidence intervals of length at age, while the golden ribbon and red line indicates the model estimates.  Note that age 11 is a plus group.}\label{fig:bmt.gr}
\end{figure}


\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=8,warning=FALSE,message=FALSE,cache=TRUE>>=
fit$catchdist.fleets %>% 
  filter(name=='aldist.gil') %>% 
  group_by(year,step,age) %>% 
  mutate(o=observed/sum(observed,na.rm=TRUE),p=predicted/sum(predicted)) %>% 
  select(year,step,age,length,observed,o,predicted,p) %>% 
  ungroup() %>% 
  mutate(age=as.numeric(gsub('age','',age)), 
         length=as.numeric(gsub('len','',length))) %>% 
  group_by(year,step,age) %>% 
  summarise(o.ml=sum(o*length,na.rm=TRUE),
            o.sl=sqrt(sum(o*(length - o.ml)^2,na.rm=TRUE)),
            p.ml=sum(p*length),
            p.sl=sqrt(sum(p*(length - p.ml)^2))) %>% 
  mutate(o.ml=ifelse(o.ml==0,NA,o.ml),
         o.sl=ifelse(o.sl==0,NA,o.sl),
         upper = p.ml+1.96*p.sl,
         lower = p.ml-1.96*p.sl,
         o.upper = o.ml+1.96*o.sl,
         o.lower = o.ml-1.96*o.sl) %>% 
  ggplot(aes(age,o.ml)) + geom_ribbon(fill='gold',aes(ymax=upper,ymin=lower))+geom_point(size=0.5) + 
  geom_line(aes(y=p.ml),col='red')  + geom_linerange(aes(ymax=o.upper,ymin=o.lower))+
  facet_wrap(~year+step) + 
  theme_light() + xlab('Age') + ylab('Average length') +
  geom_label(data=fit$catchdist.fleets %>% 
              filter(name=='aldist.gil') %>% 
              select(year,step) %>% 
              distinct() %>% 
              mutate(label=paste(year,step,sep=', ')),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.) +
  theme(strip.background = element_blank(),strip.text=element_blank())
@
\caption{Ling in 5a. Fitted length at age by year compared to observed values from the gillent samples. The black point and vertical bar denotes the observed mean and 95\% confidence intervals of length at age, while the golden ribbon and red line indicates the model estimates.  Note that age 11 is a plus group.}\label{fig:gil.gr}
\end{figure}
\begin{figure}[h]
<<agebubbleplot,fig.width=10, fig.height=7,warning=FALSE,message=FALSE,cache=TRUE,echo=FALSE>>=
fit$catchdist.fleets %>% 
  dplyr::filter(grepl('aldist',name)) %>%
  dplyr::mutate(age=as.numeric(gsub('age','',age)), 
                length=as.numeric(gsub('len','',length))) %>% 
  dplyr::group_by(name,year,age,step,total.catch) %>% 
  dplyr::summarise(o=sum(observed,na.rm=TRUE),
                   p=sum(predicted)) %>% 
  dplyr::mutate(o=ifelse(o==0,NA,o)) %>% 
  left_join(SS$weights %>% rename(name=Component)) %>% 
  ggplot(aes(year+(step-1)/4,age,size=abs((o-p)*sqrt(Weight)), 
             col=as.factor(sign((o-p))))) + geom_point() + 
  facet_wrap(~name)  + theme_light() + 
  scale_color_manual(values=c('darkblue','red'))+ theme(legend.position = 'none')
@
\caption{Ling in 5.a. Standardised residual plots for the fitted age distribution from the commercial and survey fleets. Red points denot a model underestimate and blue points an overestimated. The size of the points denote the scale of the standardised residual.}\label{fig:bubbleadist}
\end{figure}


\clearpage
\subsection{Maturity}
The estimated maturity at length and the observed values from the spring survey are contrasted in fig. \ref{fig:matp.igfs}. Some discrepancy can be observed from from the figure, notably in 1991 and 2001 where model predicts a lower and higher maturity proportion, respectively, than observed.  Overall the model appears to capture the general structure of the data.  

\begin{figure}[h]
<<echo=FALSE,fig.width=10, fig.height=8,warning=FALSE,message=FALSE,cache=TRUE>>=
bootfit$stockdist %>% 
  mutate(pred.ratio= ifelse(is.nan(pred.ratio),0,pred.ratio)) %>% 
  #filter(!(model %in% c(22,70,73,24,56,64)))%>%
  filter(stock=='lingmat') %>% 
  ggplot(aes((upper+lower)/2,obs.ratio,group=round(upper+lower)/2)) + 
  geom_ribbon(aes(x=avg.length,y=mp,ymin=lp,ymax=up,group=1), 
              data = bootfit$stockdist%>% 
  #filter(!(model %in% c(22,70,73,24,56,64))) %>%
                filter(stock=='lingmat') %>% 
                mutate(avg.length=(upper+lower)/2) %>% 
                group_by(year,avg.length) %>% 
                summarise(mp=median(pred.ratio,na.rm=TRUE),
                          lp=quantile(pred.ratio,0.025,na.rm=TRUE),
                          up=quantile(pred.ratio,0.975,na.rm=TRUE)),
              fill='gold') +
  geom_boxplot() + 
  geom_line(aes(x=avg.length,y=mp,group=1),
            data = bootfit$stockdist %>% 
  #filter(!(model %in% c(22,70,73,24,56,64)))%>%
                filter(stock=='lingmat') %>% 
                mutate(avg.length=(upper+lower)/2) %>% 
                group_by(year,avg.length) %>% 
                summarise(mp=median(pred.ratio,na.rm=TRUE),
                          lp=quantile(pred.ratio,0.025,na.rm=TRUE),
                          up=quantile(pred.ratio,0.975,na.rm=TRUE))) +
  geom_line(aes(y=pred.ratio,group=1),data=fit$stockdist %>% filter(stock=='lingmat'),col='red')+
  facet_wrap(~year) + theme_light() + 
  labs(y='Prop. mature',x='Length') +
  geom_label(data= fit$stockdist %>% 
              ungroup() %>% 
              select(year) %>% 
              distinct()%>% 
              mutate(label=year),
            aes(label=label,group=1),x=-Inf,y=Inf,size=3, vjust = 2,hjust=-0.1) +
  theme(strip.background = element_blank(),strip.text=element_blank())
@
\caption{Ling in 5a. A boxplot of the bootstrap distribution of the maturity at length from the Icelandic spring survey compared to the bootstrap confidence and median of model estimates, indicated by a gold ribbon and a solid black line. Base model estimates are shown as a red line.}\label{fig:matp.igfs}
\end{figure}


% 
% \begin{figure}[h]
% <<echo=FALSE,fig.width=10, fig.height=8,warning=FALSE,message=FALSE,cache=TRUE>>=
% fit$stockdist %>% 
%   group_by(year) %>% 
%   dplyr::mutate(o=number.x/sum(number.x,na.rm=TRUE),
%                 p=number.y/sum(number.y),
%                 upper=ifelse(grepl('mat',stock),upper+8,upper)) %>% 
%   ggplot(aes((upper+lower)/2,o,col=stock)) + geom_point(size=0.5) + 
%   geom_segment(aes(xend=(upper+lower)/2,yend=0)) + 
%   facet_wrap(~year,drop=FALSE) + 
%   theme_light() + 
%   geom_line(aes(y=p)) + xlim(c(25,160)) + 
%   xlab('Length') + ylab('Proportion') + 
%   theme(strip.background = element_blank(),
%         strip.text = element_blank(),
%         legend.position = 'none') + 
%   geom_label(data=data_frame(year=c(unique(fit$stockdist$year))) %>% 
%                                 mutate(label=year),
%             aes(label=label),x=-Inf,y=Inf,size=2, vjust = 1,hjust=-0.,col='black')
%   @
% \caption{Ling in 5a. Base model fit to the maturity disaggregated length distributions from the spring surveys. The red line and points indicates the observed and predicted immmature component respective. The mature component are present as blue points and lines for observed and predicted respectively.}\label{fig:matp.igfs.alt}
% \end{figure}



\cleardoublepage

\section{Estimates}
\subsection{Growth}
In the model, information on growth of ling is obtained from the aged
otoliths (see subsection \ref{subsec:AgeData}).  In figure
\ref{fig:GrEstimates} examples of the growth estimates are presented.
In the model $L_\infty$ and $k$ are estimated. In figure
\ref{fig:GrEstimates}a predictions of the growth curve using the
bootstrap estimates of of the growth process pre-exploitation, i.e before any mortality occurs in the model, are plotted (black solid line and blue area).  On
top of that the bootstrap estimates of mean length at age in 2016 are
plotted (black dashed line and yellow area).  There is some difference between these two growth curves
which can be attributed to fishing mortality (size selective).  The
growth curves in figure \ref{fig:GrEstimates}a look plausible.  In figure
\ref{fig:GrEstimates}b the bootstrap estimates of the standard
deviation ($s$) of mean length at age in the population in 2016 are
presented.  The estimates of $s$ increase rapidly from the age of 3 to
age 5, after that the increase is slower.  For the oldest age
groups the estimates of $s$ decrease again slightly, due to the size
selectivity in the model, with a slight increase in the last age group due to the continued growth in the plus group.

\begin{figure}[h]

<<echo=FALSE,fig.width=10, fig.height=4,warning=FALSE,message=FALSE,cache=TRUE>>=
gridExtra::grid.arrange(
  bootfit$stock.std%>% 
  #filter(!(model %in% c(22,70,73,24,56,64))) %>% 
    filter(year %in% c(min(year),2016),
           age>2) %>% 
    group_by(model,year,age) %>% 
    dplyr::summarise(mean.length = sum(number*mean.length)/sum(number)) %>% 
    group_by(year,age) %>% 
    dplyr::summarise(ml = median(mean.length,na.rm=TRUE),
              ul=quantile(mean.length,0.975,na.rm=TRUE),
              ll=quantile(mean.length,0.025,na.rm=TRUE)) %>% 
    dplyr::mutate(ml = ifelse(year==2016,ml+3,ml),
                  ul = ifelse(year==2016,ul+3,ul),
                  ll = ifelse(year==2016,ll+3,ll)) %>% 
    ggplot(aes(age,ml)) + 
    geom_ribbon(alpha=0.5,aes(age,ymax=ul,ymin=ll,fill=as.factor(year))) + 
    theme_light() + 
    geom_line(aes(lty=as.factor(year))) + 
    scale_fill_manual(values=c('lightblue','gold')) +
    theme(legend.position = 'none') +
    labs(x='Age',y='Mean length') + 
    annotate(geom = 'text',x = 2,y=125,label = 'a)'),
  bootfit$stock.std %>% 
  #filter(!(model %in% c(22,70,73,24,56,64)))%>% 
    filter(year %in% c(2016),
           age>1) %>% 
    group_by(model,age) %>% 
    summarise(mean.length = sum(number*stddev.length)/sum(number)) %>% 
    group_by(age) %>% 
    summarise(ml = median(mean.length,na.rm=TRUE),
              ul=quantile(mean.length,0.975,na.rm=TRUE),
              ll=quantile(mean.length,0.025,na.rm=TRUE)) %>% 
    ggplot(aes(age,ml)) + 
    geom_ribbon(alpha=0.5,aes(age,ymax=ul,ymin=ll),fill='gold') + 
    theme_light() + 
    geom_line() + 
    #scale_fill_manual(values=c('gold')) +
    theme(legend.position = 'none') +
    labs(x='Age',y='Std.dev in length') + 
    annotate(geom = 'text',x = 2,y=14,label = 'b)'),
  ncol=2)

@


\caption{Ling in 5a: Estimates of growth from the gadget model. a)
  Predicted growth from bootstrap estimates of initial population mean length at age (median: black solid line) and 5-95\%
inter quantile range (blue area) and predicted mean length in stock in 2016
from the bootstrap estimates (median: black dashed line) and 5-95\%
inter quantile range (yellow area). b) Bootstrap estimates of standard
deviation of length at age in 2016 (black line: median, yellow area
5-95\% quantiles).}\label{fig:GrEstimates}

\end{figure}

\cleardoublepage
\subsection{Predicted age-structure}
Having a large plus group in the model can indicate either to low
natural mortality or to slow growth rate, or a combination of both.
The predicted catch in numbers (Figure \ref{fig:CN}) shows that the
main age groups in the catches according to the model are ages 5 to 12
and hardly any ling older than age 13 is caught.  Similarly, stock
abundance declines rapidly after the age of 9 and the plus group (15)
is very close to zero in most cases (Figure \ref{fig:logN}). Uncertainty 
in rectruitment in the terminal years of the model appears to have an 
effect on the abundance estimates in the final years.


\begin{figure}[h]

<<echo=FALSE,results='asis',fig.width=10, fig.height=5,cache=TRUE,warning=FALSE,message=FALSE>>=
fit$out.fit[grepl('prey',names(fit$out.fit))] %>% 
  bind_rows() %>% 
  filter(year>1997) %>% 
  group_by(year,age) %>%
  summarise(n=sum(number.consumed)/1e3) %>% 
  ggplot(aes(age,n)) + geom_line() + 
  facet_wrap(~year,scale='free_y') + 
  theme_light() + labs(x='Age',y='Catch in numbers (thousands)') +
  geom_label(data=data_frame(year=1998:2016) %>% 
              mutate(label=year),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.1) +
  theme(strip.background = element_blank(),strip.text=element_blank())
@

  %\includegraphics[width=1\linewidth]{../Graphs/CN.pdf}
\caption{Ling in 5a. Estimates of catch in numbers from the base-run.}\label{fig:CN}
\end{figure}

\cleardoublepage
\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=5,cache=TRUE,warning=FALSE,message=FALSE>>=
bootfit$stock.std %>% 
  #filter(!(model %in% c(22,70,73,24,56,64)))%>% 
  filter(year>1997) %>% 
  group_by(year,age,model) %>%
  summarise(n=log(sum(number)/1e6)) %>%
  mutate(n=pmax(n,-4)) %>% 
  ungroup() %>% 
  filter(age>min(age)) %>% 
  group_by(year,age) %>% 
  summarise(mn=median(n),
            un=quantile(n,0.975),
            ln=quantile(n,0.025)) %>% 
  ggplot(aes(age,mn)) + geom_ribbon(aes(ymin=ln,ymax=un),fill='gold')+
  geom_line() + 
  facet_wrap(~year) + 
  theme_light() + labs(x='Age',y='log(Abundance in millions)')+
  geom_label(data=data_frame(year=1998:2016) %>% 
              mutate(label=year),
            aes(label=label),x=-Inf,y=-Inf,size=3, vjust = -0.5,hjust=-0.1) +
  theme(strip.background = element_blank(),strip.text=element_blank())
@
\caption{Ling in 5a. Estimates of abundance by age and year, log transformed. Black solid line and golden ribbon indicate the bootstrap median and 95\% inter-quantile range. }\label{fig:logN}
\end{figure}



\subsection{Selectivity}
The estimated selection curves for model fleets are shown in fig. \ref{fig:sel} along with the respective bootstrap 95\% interquantile range.  The longline and trawl fleets selectivity were not substantially different, with median values of $l_50$ of 76.91 cm (72.93 -- 78.28) and 75.37 cm (69.96--77.55) respectively. The $l_{50}$ in the survey was estimated to be slightly lower, or 68.28 cm, but higher uncertainty ranging between 54.18 cm to 86.92 cm. The $l_{50}$ of the gillnet fleet was considerably higher or 101.62 cm (97.97 -- 101.62). 

\cleardoublepage
\begin{figure}[h]

<<echo=FALSE,results='asis',fig.width=8, fig.height=5,cache=TRUE,warning=FALSE,message=FALSE>>=
bootfit$suitability %>% 
  #filter(!(model %in% c(22,70,73,24,56,64)))%>% 
  filter(fleet != 'foreign',grepl('mat',stock)) %>% 
  mutate(fleet = ifelse(fleet=='igfs','Survey',
                        ifelse(fleet=='lln','Longliners',
                               ifelse(fleet == 'gil','Gilnetters','Trawlers'))))%>% 
  group_by(fleet,l) %>%
  summarise(ms=median(suit),
            us=quantile(suit,0.975),
            ls=quantile(suit,0.025)) %>% 
  ggplot(aes(l,ms)) + 
  geom_line(aes(l,suit),fit$suitability %>% filter(fleet != 'foreign',grepl('mat',stock)) %>% 
  mutate(fleet = ifelse(fleet=='igfs','Survey',
                        ifelse(fleet=='lln','Longliners',
                               ifelse(fleet == 'gil','Gilnetters','Trawlers')))) ,col='red') + 
  geom_ribbon(aes(ymax=us,ymin=ls),fill='gold',alpha=0.5) + 
  geom_line() + 
  theme_light() + 
  facet_wrap(~fleet) + 
  labs(y='Suitability',x='Length') + 
  theme(legend.position =c(0.8,0.2),
        legend.background = element_blank(),
        strip.background = element_blank(),
        strip.text = element_blank()) +
  geom_label(data=data.frame(fleet = c('Survey','Longliners','Gilnetters','Trawlers')),
             aes(label=fleet),x=-Inf,y=Inf,size=3, vjust = 1,hjust=-0.)#+ 
  #scale_fill_manual(values=c('lightblue','gold','green','gray')) +
  #guides(fill=guide_legend(title="Fleet"),lty=guide_legend(title="Fleet")) 
@


\caption{Ling in 5a. Bootstrap estimates of selection curves from the
  fleets in the model.  Black lines is the median and shaded area the
  5-95\% interquantile range. Red lines indicates estimate from the base model. }\label{fig:sel}
\end{figure}


\subsection{Population estimates}
The model predicts that total biomass is currently starting to decline from its peak level in 2014. Simlarly reference biomass and the spawning stock biomass SSB are starting to decline but still at a level considerably higher that ever observed (Figure\ref{fig:Estimates}).  The SSB reached its lowest point at 9.93 kt in 1991. The bootstrap runs indicate that uncertainty
about population estimates has been increasing in recent years, in
accordance with the increase in the variance of the survey indices and fewer datapoints behind those estimates. 

The coefficient of variation (CV) of the population estimates from the
bootstrap runs is on average around 0.15 for the SSB, 0.15 for the 
reference biomass (>75 cm), and 0.16 for recruitment.  However in
the assessment year the CV of SSB and reference biomass is around
0.25 and 0.28 respectively, the range for these two metrics is between 0.1 to 0.26 and 0.09 to 0.28.  For
recruitment the range is 0.08 to 0.4.

Catches of immature fish, in terms of total biomass caught, is estimated to have varied between 12.4 \% in 1982 to 26.5\% in 2011 and in 2016 the estimated proportion is 12.6\%. 

\cleardoublepage

\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=12,cache=TRUE,warning=FALSE,message=FALSE>>=
bio.plot <- 
  bootres %>%
  rename(yea=year) %>% 
  select(-matches('cv|r|ssb')) %>% 
  rename(year=yea) %>% 
  gather(col,value,-year) %>%
  mutate(stat=gsub('(^u+|^l+|^m|^f).*',("\\1"),col),
         col = str_sub(col,-2),
         value=value/1e6) %>%  
  filter((col %in% c('hb','tb'))) %>%
  spread(stat,value) %>%
  mutate(col=ifelse(col=='hb','Ref. biomass','Total biomass')) %>% 
  ggplot(aes(year,m,group=col)) + 
  geom_ribbon(aes(ymax=u,ymin=l,fill=col),alpha=0.5) + 
  geom_ribbon(aes(ymax=uu,ymin=ll,fill=col),alpha=0.5) +
  geom_line() + 
  geom_line(aes(y=f),col='red')+
  theme_light() +
  expand_limits(y=0) + 
  scale_fill_manual(name=NULL,values=c('gold','lightblue')) +
  labs(y='Biomass (in kt)',x='Year') +
  theme(legend.position = c(0.15,0.8)) 

ssb.plot <- 
  bootres %>%
  select(c(year,matches('ssb'))) %>% 
  gather(col,value,-year) %>%
  mutate(stat=gsub('(^u+|^l+|^m|^f).*',("\\1"),col),
         col = "ssb",
         value=value/1e6) %>% 
  spread(stat,value) %>% 
  ggplot(aes(year,m,group=col)) + 
  geom_ribbon(aes(ymax=u,ymin=l,fill=col),alpha=0.5) + 
  geom_ribbon(aes(ymax=uu,ymin=ll,fill=col),alpha=0.5) +
  geom_line() + 
  geom_line(aes(y=f),col='red')+
  theme_light() +
   scale_fill_manual(name=NULL,values=c('gold','lightblue')) +
  expand_limits(y=0) + 
  labs(y='SSB (in kt)',x='Year') +
  theme(legend.position = 'none')


F.plot <- 
  bootres %>% 
  select(year,matches('[a-z]F|[a-z]hr')) %>% 
  select(-matches('cv')) %>% 
  gather(col,value,-year) %>%
  dplyr::mutate(stat=gsub('(^u+|^l+|^m|^f).*',("\\1"),col),
         col = ifelse(grepl('hr',col),'Harvest rate','Fishing mortality')) %>% 
  spread(stat,value) %>% 
  ggplot(aes(year,m,group=col)) + 
  geom_ribbon(aes(ymax=u,ymin=l,fill=col),alpha=0.5) + 
  geom_ribbon(aes(ymax=uu,ymin=ll,fill=col),alpha=0.5) +
  geom_line() + 
  geom_line(aes(y=f),col='red')+
  theme_light() +
  expand_limits(y=0) +
  scale_fill_manual(name=NULL,values=c('gold','lightblue')) +
  labs(y='Fishing mortality/Harvest rate',x="Year")+
  theme(legend.position = c(0.6,0.8))

rec.plot <- 
  bootres %>% 
  select(year,matches('[a-z]r')) %>% 
  select(-matches('hr')) %>% 
  gather(col,value,-year) %>%
  mutate(stat=gsub('(^u+|^l+|^m|^f).*',("\\1"),col),
         col = str_sub(col,-1),
         value = value/1e6) %>%
  filter(stat!='c') %>% 
  spread(stat,value) %>% 
  ggplot(aes(year,m,group=col)) + 
  geom_ribbon(aes(ymax=u,ymin=l),alpha=0.5,fill='gold') + 
  geom_ribbon(aes(ymax=uu,ymin=ll),alpha=0.5,fill='gold') + 
  geom_line() + 
  geom_line(aes(y=f),col='red')+
  theme_light() +
  expand_limits(y=0) +
  labs(y='Recruitment (in millions)',x="Year")

catch.plot <- 
  fit$res.by.year %>% 
  mutate(stock=ifelse(grepl('mat',stock),'Mature','Immature')) %>% 
  ggplot(aes(year,catch/1e6,fill=stock)) +
  geom_bar(stat='identity') + 
  theme_light() +
  scale_fill_manual(name = NULL, values=c('gold','lightblue')) +
  labs(y='Landings (in kt)',x="Year") +
  theme(legend.position = c(0.8,0.15)) 

cv.plot <- 
  bootres %>%
  select(year,matches('cv')) %>% 
  gather(col,value,-year) %>%
  mutate(stat=str_sub(col,0,2),
         col = str_sub(col,3,5)) %>% 
  filter(col %in% c('hb','ssb','r','F')) %>% 
  spread(stat,value) %>% 
  mutate(col=case_when(.$col=='hb'~'Harv. biomass',
                       .$col=='ssb'~'SSB',
                       .$col=='r'~'Recruitment',
                       .$col=='F'~'F')) %>% 
  ggplot(aes(year,cv,lty=col)) + 
  geom_line() + 
  scale_linetype_manual(name=NULL,values=1:4) +
  theme_light() +
  expand_limits(y=0) + 
  labs(y='CV',x='Year') +
  theme(legend.position = c(0.5,0.8))

gridExtra::grid.arrange(bio.plot,ssb.plot,F.plot,rec.plot,catch.plot,cv.plot)

@



  %\includegraphics[width=0.9\linewidth]{../Graphs/BootRes.pdf}
\caption{Ling in 5a. Estimates of biomass, reference biomass (ling
  larger than 75 cm, knife-edge) and spawning stock biomass.  Estimates of
  recruitment in millions and fishing mortality (age $15^+$). Black line is the
  median of bootstrap estimates, yellow area is the range between the
  5-95\% quantiles of the bootstrap estimates and the red line is the
  results of the base-run.  Estimates of coefficient of variation (CV) for
  reference biomass, fishing mortality, recruitment and SSB.}\label{fig:Estimates}
\end{figure}


\cleardoublepage

\subsection{Analytic retrospective analysis}
In figure \ref{fig:Retro} the results of an analytical retrospective
analysis are presented.  The analysis indicates that there is a
downward revision of biomass (SSB and reference) in 2012 to 2014
and subsequently an upward revision of $F$.  Estimates of
recruitment in the years between 2007 to 2010 fluctuate wildly. 

Two things have to be considered when looking at figure
\ref{fig:Retro}.  First is that these fluctuations are roughly within the 95\% bootstrap interquantile range, although there appears to be a one way correction each consecutive year while 2015 and 2016 models appear roughly inline with one another. This is appears to be related to the discounting of peak values of the survey indices in the latter half of the first decade of this century (See figure
 \ref{fig:retrosi}) when more data on the subsequent decrease emerged. Therefore as the
 increase in the indices is discounted each year, as the signal
 (increase) does not transfer to the larger length groups, the biomass
 estimates are reduced. 

The second thing is that the tuning indices until very recently exhibited a "one-way" trend in addition of being fairly noisy. So under these circumstances, while the historical assessment is fairly stable, the uncertainty in the current (or contemporary) estimate of the stock status is likely exhibit a strong correlation with previous years assessment.  

It is also worth noting that the bulk of the age structured data is in the last 15 years, and the bulk after 2010, and therefore a very informative data is being
omitted, this specially affects the recruitment estimates. Also the lack of age data back in time, in contrast with traditional age based assessments appears to result in greater variation in historical estimates. 

\begin{figure}[h]

<<echo=FALSE,results='asis',fig.width=10, fig.height=8,warning=FALSE,message=FALSE>>=
retro.res <- 
  retro.fit$res.by.year %>% 
  bind_rows(fit$res.by.year %>% dplyr::mutate(model="0")) %>% 
  group_by(year,model) %>% 
  dplyr::summarise(tb=sum(total.biomass),
            ssb=sum(total.biomass[grepl('mat',stock)]),
            F = max(F),
            catch = sum(catch),
            #hb=sum(harv.biomass),
            rec=sum(recruitment,na.rm=TRUE)) %>% 
  left_join(retro.fit$stock.full %>%
              filter(length>ref.cm) %>% 
              group_by(year,model) %>%
              dplyr::summarise(hb=sum(number*mean.weight))) %>% 
  mutate(hr = catch/hb)

  
rbio.plot <- 
  bio.plot + 
  geom_line(data= retro.res %>% 
              select(year,tb,hb,model) %>% 
              gather(col,value,-c(year,model)) %>% 
              mutate(value=value/1e6),
            aes(year,value,lty=model,group=interaction(model,col)),col='red') +
  guides(linetype=FALSE)

rssb.plot <- 
  ssb.plot + 
  geom_line(data= retro.res %>% 
              select(year,value=ssb,model) %>% 
              #gather(col,value,-c(year,model)) %>% 
              mutate(value=value/1e6),
            aes(year,value,lty=model,group=model),col='red') 

  #ggplot(aes(year,value,lty=model,col=col)) + geom_line() + 
  #theme_light() + 
#  labs(y='Biomass (in kt)',x='Year')+
#  theme(legend.position = 'none')+ expand_limits(y=0)

rF.plot <- 
 F.plot + 
  geom_line(data=retro.res %>% 
              select(year,value=F,m=model),
            aes(y=value,lty=m,group=m),col='red') + 
    geom_line(data=retro.res %>% 
              select(year,value=hr,m=model),
            aes(y=value,lty=m,group=m),col='red') + 
  theme(legend.position = 'none')
  #gather(col,value,-c(year,model)) %>% 
  #mutate(value=value/1e6) %>% 
  #ggplot(aes(year,value,lty=model)) + geom_line() + 
  #theme_light() + 
  #labs(y='Fishing mortality',x='Year')+
  #theme(legend.position = 'none')+ expand_limits(y=0)


rrec.plot <- 
  rec.plot + 
  geom_line(data = retro.res %>% 
              select(year,value=rec,model) %>% 
              mutate(value=value/1e6),
            aes(year,value,lty=model,group=model),col='red')+ 
  theme(legend.position = 'none')

gridExtra::grid.arrange(rbio.plot,rssb.plot, rF.plot,rrec.plot,ncol=2)
@

\caption{Ling in 5a. Analytical retrospective analysis from the Gadget
model. Estimates of biomass, reference biomass (ling
  larger than 75 cm, knife-edge) and spawning stock biomass.  Estimates of
  recruitment in millions and fishing mortality (age $15^+$). Black line is the
  median of bootstrap estimates, yellow area is the range between the
  5-95\% quantiles of the bootstrap estimates and the red line is the
  results of the base-run.  The various dotted lines indicate the retrospective model estimates.}\label{fig:Retro}
\end{figure}

\begin{figure}[h]
<<echo=FALSE,results='asis',fig.width=10, fig.height=8,warning=FALSE,message=FALSE>>=
bootfit$sidat %>% 
  #filter(!(model %in% c(22,70,73,24,56,64)))%>% 
  group_by(year,name) %>% 
  summarise(om=median(number.x,na.rm=TRUE),
            ou=quantile(number.x,0.975,na.rm=TRUE),
            ol=quantile(number.x,0.025,na.rm=TRUE),
            pm=median(predict,na.rm=TRUE),
            pu=quantile(predict,0.975,na.rm=TRUE),
            pl=quantile(predict,0.025,na.rm=TRUE)) %>% 
  ggplot(aes(year,om)) + geom_ribbon(aes(ymin=ol,ymax=ou),fill="gold") + geom_line() +
  geom_line(aes(y=pm),col='blue') +
  geom_line(aes(y=pu),col='blue',lty=2) +
  geom_line(aes(y=pl),col='blue',lty=2) +
  geom_line(aes(y=predict),col='red',data=fit$sidat) +
  geom_line(aes(y=predict,lty=model),col='red',data=retro.fit$sidat) +
  
  facet_wrap(~name,scale='free_y') + theme_light() + 
  labs(y='Survey index',x='Year')+
  geom_label(data=fit$sidat %>%
              select(name,slope,sse) %>%
              distinct() %>% 
              mutate(label=name),
            aes(label=label),x=-Inf,y=Inf,size=3, vjust = 1.1,hjust=-0.1) +
  theme(strip.background = element_blank(),strip.text=element_blank(),
        legend.position = 'none')
@
\caption{Ling in 5a. Analytical retrospective analysis of the fit to the survey indices. }\label{fig:retrosi}

\end{figure}

\clearpage
\subsection{Changes since last benchmark}
For the 2017 benchmark the main changes to the assessment model are:
\begin{itemize}
\item The model building process is built up from scratch such that it would allow for it to be reproducible. The scripts that generate the assessment are currently available from github.com/fishvice/mfdb-hafro-etl and github.com/fishvice/gadget-models
\item The model now estimates explitly the maturity process by setting up two sub-stocks, immmature and mature, allowing for the direct estimate of the spawning stock biomass. In comparison, in previous iterations of the assessment model, the spawning stock biomass was estimated based on the combination of a maturity at length ogive and the model estimates of number at length. 
\item Age readings where fish have been assigned an age of 11 or older are now grouped together before comparing with the model output. This is done as age of ling is harder to determine after the age of 11 and number samples of old fish are fairly low.
\item Age readings prior to 2001 have been omitted from the input data as these ototliths were read using a different (older) method that is perceved to be incorrect.
\item The $q$ for the two survey indices representing the smallest length groups is now estimated, which appears to stabilise the retro, as suggested in fig. \ref{fig:Retro}.  
\item The lengthgroup size was increased from 1 cm to 4 cm  while at the same time the maximum size was decreased to 160 cm (from 180 cm previously). This resulted in a 50\% reduction in computing time.
\end{itemize}

Comparison between the contemporary assessment model and the updated assessment model is shown in fig. \ref{fig:oldvsnew}. Current assessment of the stock is more or less in-line with previous assessment, while historical biomass estimates are substantially lower from the contemporary assessment model when compared with the updated asseesment model. It is also worth noting that the historical retrospective, using this previous model, revealed a substantial revision between years.

These differences between the two models is considered to be related to changes done during the revision. For example the addition of the maturity at length data, can additionally inform on the level between the two stock components. The differences in the recruitment estimates can be attributed to the omission of age data prior to 2001. 
<<oldvsnew,echo=FALSE,fig.height=8,fig.width=8,fig.lp='fig:',fig.cap="Ling in 5a. Comparison with last year assement results. Estimates of biomass, reference biomass (ling larger than 75 cm, knife-edge) and spawning stock biomass.  Estimates of  recruitment in millions and fishing mortality (age $15^+$). Black line is the median of bootstrap estimates, yellow area is the range between the 5-95\\% quantiles of the bootstrap estimates and the red line is the results of the base-run.  The blue dashed lines denote last years assessment.",warning=FALSE,message=FALSE,cache=TRUE>>=
load('/u2/reikn/Tac/2016/06-Langa/04-Ed2015keyrsla/FIT/WGTS.Rdata')
fit.old <- out
bio.old <- 
fit.old$res.by.year %>% 
  filter(year<2016) %>% 
  group_by(year) %>% 
  dplyr::summarise(ftb = sum(total.biomass),
                   catch = sum(catch),
                   fssb = ssb,
                   frec = sum(recruitment,na.rm=TRUE),
                   fF = max(F)) %>% 
  left_join(fit.old$stock.full %>%
              filter(length>ref.cm) %>% 
              group_by(year) %>%
              dplyr::summarise(fhb=sum(number*mean.weight))) %>%
  mutate(fhr=catch/fhb) 

bio.old %>% 
  select(year,fhb,ftb) %>% 
  gather(type,value,-year) %>% 
  mutate(value=value/1e6)-> tmp
biocomp.plot <- bio.plot+ geom_line(aes(year,value,group=type),col='blue',lty=2,data=tmp)


bio.old %>% 
  select(year,fF) %>% 
  gather(type,value,-year) %>% 
  mutate(value=value/1e6)-> tmp

ssbcomp.plot <- ssb.plot + geom_line(aes(year,fssb/1e6,group=1),col='blue',lty=2,data=bio.old)
fcomp.plot <- F.plot+ geom_line(aes(year,fF,group=1),col='blue',lty=2,data=bio.old)+geom_line(aes(year,fhr,group=1),col='blue',lty=2,data=bio.old)
reccomp.plot <- rec.plot + geom_line(aes(year,frec/1e6,group=1),col='blue',lty=2,data=bio.old)

gridExtra::grid.arrange(biocomp.plot,ssbcomp.plot,fcomp.plot,reccomp.plot,ncol=2)
@

\cleardoublepage


\section{Reference points}
According ICES technical guidelines two types of reference points are referred to when giving advice for category 1 stocks: \textit{precautionary approach (PA) reference points and maximum sustainable yield (MSY) reference points. The PA reference points are used when assessing the state of stocks and their exploitation rate relative to the precautionary approach objectives. The MSY reference points are used in the advice rule applied by ICES to give advice consistent with the objective of achieving MSY}. Generally ICES derives these reference points based on fishing mortality, but for some stocks the reference points are determine in terms of harvest rate, i.e. the amount of catches relative to a reference biomass (s.a. spawning stock biomass, or biomass of fish larger than a minimum size or older than a minimum age). For ling in 5a the suggested management plan will be determined in terms of the harvest rate of the total biomass above 75 cm.  

The following sections describe the derivation of the management reference points both in terms of harvest rate ($H$) and fishing mortality ($F$). The model for the stock recruitment and assessment error which in combination with the bootstrap results is used to project the stock status stochastically in order to derive the PA and MSY reference points.  
% 
% 
% When considering uncertainty in the estimation of reference points
% four sources of error need to be considered \citep[eg. in][and
% references therein]{butterworth1999}. These are:
% \begin{enumerate}
% \item \textbf{Process error}, i.e. the natural variation in the stock under
%   managment.  Example process that is beyond the control of the
%   manager/modeller is variation in recruitment.
% \item \textbf{Observation error} is relatied to uncertainty in the way the
%   stock is sampled.
% \item \textbf{Implementation error} describes how well the management policies
%   are enforced, i.e. the extent of illegal landings and discards.
% \item \textbf{Model error} related to the form of the model, such as
%   stock definitions and variations in model parameters  
% \end{enumerate}
% 
% Observation error and to some degree model error are addressed by the
% bootstrap approach employed in here. Issues related to the
% stock structure have been discussed in WGDEEP-2007, which suggested 
% that ling in 5a and 14 should be assessed as single stock unit. Analytical 
% retrospetive analysis indicates some degree of model mispecification, or 
% autocorrelation in observation error,  while this is a concern it is caused by
% inconsistencies in the survey indices. 
% 
% Illegal landings and discards by Icelandic fishing vessels are considered to
% be neglible and it is assumed that foreign vessel catches are a part of the 
% management plan. It is assumed therefore implementation error would be virtually
% none. The largest source of error outstanding is the extent of process
% error, in particular variation in the stock recruitment relationship. 
% 
% The following sections describe the model for the stock recruitment and assessment error
% which in combination with the bootstrap results is used to project the
% stock status along with rationale for setting biomass reference points.


% 
% 
% \section{Explaining changes in recruitment}
% \subsection{Temporal changes in recruitment}
% The relationship between the estimated spawning stock and recruitment
% is shown in figure \ref{fig:ssbrec}. In the Gadget model for Ling in
% Va the annual recruitment, during the observation period, is estimated
% as a fixed effect without any consideration of the size of the
% spawning stock biomass. This means that no formal stock recruit
% relationship is defined. This is allowed by information on past
% recruitment such as age and length distributions and survey
% indices. It can be observed that for time periods where less data is
% available on recruitment, such as recruitment in the most recent
% years, have higher levels of uncertainty. 
% 
% 
% Ling in Va has experienced an unusual spike in recruitment, when
% compared to years prior to 2003. There could be two different reasons
% for this observation, impaired recruitment due to over exploitation or
% environmental changes.  In the following sub-subsections these theories
% will be explored.
% 
% 
% \subsubsection{Impaired recruitment}
% Catches in 1950 to the mid
%   seventies were around 10 thous. tonnes annually but in the eighties
%   and nineties fell to 3 to 4 thous tonnes.  After 2005 catches
%   increased again to similar levels as before (10 thous tonnes).  So
%   the decrease in recruitment would be the result of
%   over-exploitation.  This may certainly be the case
% when considering historical fishing mortality (Figure
% \ref{fig:catch}).  However there is no information available on
% fishing mortality or harvest rates for ling in Va before 1982, when
% catch levels were high for over 25 years.
% 
% \cleardoublepage

\begin{figure}

<<echo=FALSE,results='asis',fig.width=10, fig.height=6,cache=TRUE,warning=FALSE,message=FALSE>>=
bloss <- 
  bootfit$res.by.year %>% 
  filter(grepl('mat',stock)) %>%  
  group_by(model) %>% 
  summarise(bloss=min(total.biomass)/1e6)
tmp <- 
bootfit$res.by.year %>%
  group_by(year,model) %>% 
  dplyr::summarise(recruitment=sum(recruitment,na.rm=TRUE)/1e6,
                   ssb = total.biomass[grepl('mat',stock)]/1e6) %>% 
  ungroup()

tmp %>% 
  left_join(tmp %>% 
              select(model,year,ssb.5=ssb) %>% 
              dplyr::mutate(year=year+3)) %>% 
  group_by(year) %>% 
  summarise(mr=median(recruitment),
            ur=quantile(recruitment,0.975),
            lr=quantile(recruitment,0.025),
            ms=median(ssb.5,na.rm=TRUE),
            us=quantile(ssb.5,0.975,na.rm=TRUE),
            ls=quantile(ssb.5,0.025,na.rm=TRUE)) %>% 
  ggplot(aes(ms,mr)) + 
    
    geom_rect(ymin=-Inf,ymax=Inf,xmin=quantile(bloss$bloss,0.975),
              xmax=quantile(bloss$bloss,0.025),fill='gold')+
    geom_vline(xintercept = median(bloss$bloss),lty=2)+
    geom_vline(xintercept = fit$res.by.year %>% 
                 filter(grepl('mat',stock)) %>%
                 ungroup() %>% 
                 summarise(min(total.biomass)/1e6) %>% 
                 unlist(),col='red')+
    geom_errorbar(aes(ymax=ur,ymin=lr),col='grey') + 
    geom_errorbarh(aes(xmax=us,xmin=ls),col='grey') + 
    geom_path()+
    geom_point(col='red')+
    geom_text(aes(label=year-3),vjust=0.15,hjust=0.15) + 
   xlab('Spawning stock biomass (in \'000 tons) ') + 
  ylab('Recruitment (in millions)') + theme_light() +
  expand_limits(x=0,y=0) 
  

# grid.arrange(plot(fit,data='suitability'),
#              gr.plot,
#              ssb.rec,
#              prod.plot,
#              ncol=2)
@


\caption{Spawing stock biomass recruitment relationship for ling in
  5a. Uncertainty in recruitment and SSB is indicated with 95\%
  quantile intervals. The yellow vertical bar represents the
  distribution of $B_{loss}$.}\label{fig:ssbrec}
\end{figure}



\subsection{Setting $B_{lim}$ and $B_{pa}$}
$B_{lim}$ was considered from examination of the SSB--Recruitment (at age 3) scatterplot
based on the estimates from the stock assessment, as illustrated in fig. \ref{fig:ssbrec}. The figure shows a relatively narrow dynamic range of SSB and no evidence of impaired recruitment. Further discussion on the recruitment spike can be found in section \ref{sec:recdisc}. In this situation, according to the ICES technical guidelines, $B_{lim}$ can not be estimated from these data and that the lowest observed SSB during that period (i.e. $B_{loss}$ = SSB(1992) = 9.93 kt), which is the lowest observed biomass from the base--line model, is an appropriate value at which to set either as $B_{pa}$ or $B_{lim}$, depending on the the perception of the historical fishing mortality. As the fishing mortality is perceived to have since mid 1990s varied between 0.3 and 0.5 on fully recruited,  equivalent $F_{5-10}$ of 0.15 to 0.3 it is suggested that $B_{pa}=B_{loss}$.

In line with ICES technical guidelines, since $B_{pa}$ but not $B_{lim}$ can be estimated, a proxy
for $B_{lim}$ can be calculated based on the inverse of the standard factor, $e^{\sigma * 1.645}$ where $\sigma$ is 0.2, used for calculating $B_{pa}$ from $B_{lim}$. Therefore, a proxy for $B_{lim}$ could be set at $B_{pa}/e^{1.645*0.2} = 9.93/1.4 = 7.09 kt$. 

\subsection{Stock recruitment relationship}\label{subsec:SSBR}
A variety of approaches are common when estimating a stock
recruitment relationship. In the absence of a stock-recruitment signal from the available historical data (Fig. \ref{fig:ssbrec}), 
the ICES guidelines suggest that the ``hockey-stick'' recruitment function is used, i.e. 
\begin{equation}
  R_y = \bar{R}_y \min(1,S_y/B_{loss})
\end{equation}
where $R_y$ is annual recruitment, $S_y$ the spawning stock biomass,
$B_{loss}$ the break point in hockey stick function and $\bar{R_y}$ is the
recruitment when not impaired due to low levels of SSB. Here $\bar{R}_y$ is considered to be drawn from the historical distribution using a block-bootstrap, randomly drawn block starting years and including 6 consecutive years in the blocks. This is done to account for intra-correlation in the recruitment time--series, as illustrated in fig. \ref{fig:bootacf}. The timing of the recruitment in the model occurs at the end of the $1^{st}$ time-step, using the projected spawning stock biomass at the same time. 




\begin{figure}

<<echo=FALSE,results='asis',fig.width=10, fig.height=6,cache=TRUE,warning=FALSE,message=FALSE>>=
bootfit$res.by.year%>% 
  #filter(!(model %in% c(22,70,73,24,56,64))) %>% 
    filter(grepl('mat',stock)) %>% 
    group_by(model) %>% 
    dplyr::summarise(bloss = min(total.biomass)/1e6) %>% 
    ggplot(aes(bloss)) + geom_histogram() + 
    labs(x=expression(B[loss]),y='Num. replicates') + 
    theme_light() + 
    geom_vline(xintercept = fit$res.by.year %>% 
                 filter(grepl('mat',stock)) %>% 
                 ungroup() %>% 
                 summarise(min=min(total.biomass)/1e6) %>% 
                 unlist(),
               col='red')
@

%  \includegraphics[width=1.0\linewidth]{../Graphs/bloss}
  \caption{Histogram of the bootstrap distribution of $B_{loss}$ where the
    red line indicates the base model estimate.}\label{fig:blosshist}
\end{figure}


\subsection{Management procedure in forward projections}
Observation error and to some degree model error are addressed by the
bootstrap approach employed in here. Issues related to the
stock structure have been discussed in WGDEEP-2007, which suggested
that ling 5a should be assessed as single stock unit. Analytical
retrospetive analysis indicates a degree of autocorrelation in observation error,
while this is a concern it assumed that this is caused by
inconsistencies in the survey indices.

Illegal landings and discards by Icelandic fishing vessels are considered to
be negligible and it is assumed that foreign vessel catches will be part of the
management plan when implemented. It is assumed therefore implementation error would be virtually
none. The largest source of error outstanding is the extent of process
error, in particular variation in the stock recruitment relationship, and the assessment error.

The descision rule evaluated follows the methodology set out in
AGICOD2009. The rule evaluation framework can be classified as simulation without
an assessment feedback (ICES 2006), i.e. it is thus assumed that the simulation
within the operating model represents the true stock dynamics. Errors in the assessment
procedure that relate to harvest advice model are emulated as:
\begin{equation}\label{eq:asserr}
\hat{B}_y^{ref} = e^{E_y} B_{y}^{ref}
\end{equation}
where $B_y^{ref}$ is the reference biomass, $E_y = \sigma (\rho \epsilon_{y-1} + \sqrt{1-\rho^2}\epsilon_y)$ is the assessment error and $\sigma$ is CV of the reference biomass, $\rho$ the autocorrelation between assement years and $\epsilon_y\sim N(0,1)$. Then the decision which allocates catches to the fleets is simply a scalar applied to the estimate of the reference biomasss:
\begin{equation}\label{eq:mp}
TAC_{y+1} = H \hat{B}_y^{ref}
\end{equation}
where the evaluation assumes that 2 quarters elapse between the time at which the reference biomass is estimated and the beginning of the fishing year to which the TAC applies. This is to approximate the situation that will normally be encountered when providing advice in practice, where the stock assessment will cover until the end of quarter 1 and the fishing year goes from September 1 to August 31\footnote{In real applications the harvest rate will be scaled when SSB is below $B_{trigger}$ according to the ratio between SSB and $B_{trigger}$}.

For ling in 5a $B_y^{ref}$ is the biomass of fish larger than 75 cm at the assessment step, the corresponding CV set at 0.28 i.e the CV of the reference biomass. The autocorrelation in assessment error $\rho$ is set to $0.8$ which is perceived as the upper limit to potential correlation. Figure \ref{fig:asscomp} illustrates the deviation of the reference biomass as estimated in the last year of the analytical retrospective compared with the most recent assement.
%\subsection{Residual pattern}
\begin{figure}

<<echo=FALSE,results='asis',fig.width=10, fig.height=6,cache=TRUE,warning=FALSE,message=FALSE>>=
  bootacf <- 
    bootfit$res.by.year %>% 
  #filter(!(model %in% c(22,70,73,24,56,64)))%>%
    filter(grepl('imm',stock)) %>% 
    group_by(model) %>% 
    do(x=acf(.$recruitment,plot=FALSE)) %>% 
    broom::tidy(x) %>% 
    ggplot(aes(lag,acf,group=round(lag))) + geom_boxplot() + 
    theme_light() + 
    geom_hline(yintercept = c(-1,1)*qnorm((1 + 0.95)/2)/sqrt(35),lty=2) +
    labs(x='',y='') + 
    annotate('label',x=13,y=1,label='ACF') 

  bootpacf <- 
    bootfit$res.by.year %>%
    filter(grepl('imm',stock)) %>% 
    group_by(model) %>% 
    do(x=pacf(.$recruitment,plot=FALSE)) %>% 
    broom::tidy(x) %>% 
    ggplot(aes(lag,acf,group=round(lag))) + geom_boxplot() + 
    theme_light()+ 
    geom_hline(yintercept = c(-1,1)*qnorm((1 + 0.95)/2)/sqrt(35),lty=2) +
    labs(x='',y='') + 
    ylim(c(-0.5,1))+ 
    annotate('label',x=13,y=1,label='PACF') 
  
  bootacf2005 <- 
    bootfit$res.by.year %>% 
    filter(year < 2005) %>%       
    #filter(!(model %in% c(22,70,73,24,56,64)))%>%
    filter(grepl('imm',stock)) %>% 
    group_by(model) %>% 
    do(x=acf(.$recruitment,plot=FALSE)) %>% 
    broom::tidy(x) %>% 
    ggplot(aes(lag,acf,group=round(lag))) + geom_boxplot() + 
    theme_light() + 
    geom_hline(yintercept = c(-1,1)*qnorm((1 + 0.95)/2)/sqrt(35),lty=2) +
    labs(x='',y='') + 
    annotate('label',x=13,y=1,label='ACF') 
  
  bootpacf2005 <- 
    bootfit$res.by.year %>%
    filter(year < 2005) %>% 
    filter(grepl('imm',stock)) %>% 
    group_by(model) %>% 
    do(x=pacf(.$recruitment,plot=FALSE)) %>% 
    broom::tidy(x) %>% 
    ggplot(aes(lag,acf,group=round(lag))) + geom_boxplot() + 
    theme_light()+ 
    geom_hline(yintercept = c(-1,1)*qnorm((1 + 0.95)/2)/sqrt(35),lty=2) +
    labs(x='',y='') + 
    ylim(c(-0.5,1))+ 
    annotate('label',x=13,y=1,label='PACF') 

gridExtra::grid.arrange(bootacf,bootpacf,bootacf2005,bootpacf2005,ncol=2)  
@

%\includegraphics[width=1.0\linewidth]{../Graphs/bootacf}
\caption{Estimated autocorrelation (left panels) and partial autocorrelation (right panels) in recruitment. Top panels indicate the correlation including all estimates of recrutitment while the bottom panels recruitment exluding estimates after 2005. The dashed lines illustrate the standard 95\% uncertainty region.}\label{fig:bootacf}
\end{figure}

<<asscomp,echo=FALSE,results='asis',fig.width=10, fig.height=6,cache=TRUE,warning=FALSE,message=FALSE,fig.lp="fig:",fig.cap='ling in 5a. Current assement of the reference biomass of ling (> 75 cm) compared with assessment from the analytical retrospective estimate of the terminal biomass. The shaded yellow ribbon represents the uncertainty (CV = 0.28) at the terminal year.'>>=
fit$res.by.year %>% 
  select(year,stock,tru.bio=total.biomass,tru.F=F,tru.rec=recruitment) %>% 
  left_join(retro.fit$res.by.year %>% 
              filter(year+as.numeric(model)==2016) %>% 
              select(year,stock,
                     retro.bio = total.biomass,
                     retro.F = F,
                     retro.rec = recruitment)) %>%
  tidyr::gather(type,value,-(year:stock)) %>% 
  separate(type,c('source','type')) %>% 
  spread(type,value) %>%
  group_by(year,source) %>% 
  summarise(total.bio=sum(bio)/1e6,
            ssb = sum(bio[grepl('mat',stock)])/1e6,
            rec = sum(rec,na.rm=TRUE)/1e6) %>% 
  left_join(fit$stock.full %>% 
              filter(length>ref.cm) %>% 
              group_by(year) %>% 
              summarise(hb=sum(number*mean.weight)/1e6) %>% 
              mutate(source='tru')) %>% 
  left_join(retro.fit$stock.full %>% 
              filter(length>ref.cm,
                     year+as.numeric(model)==2016) %>% 
              group_by(year) %>% 
              summarise(hb.retro=sum(number*mean.weight)/1e6) %>% 
              mutate(source='retro')) %>% 
  mutate(hb=ifelse(source=='retro',hb.retro,hb)) %>% 
  select(-hb.retro) %>% 
  gather(type,value,-c(year:source)) %>% 
  filter(type=='hb') %>% 
  mutate(value=ifelse(year==2016,value[!is.na(value)&year==2016],value),
         source = ifelse(source=='tru','Current assessment','Analytical retrospective')) %>% 
  ggplot(aes(year,value,col=source)) + 
  geom_ribbon(aes(ymin=value*exp(qnorm(0.025)*0.2),
                  ymax=value*exp(qnorm(0.975)*0.2)),
              alpha=0.5,
              fill='gold',col='white',
              data=. %>% filter(source == 'Current assessment'))+
  geom_line() + 
  #facet_wrap(~type) +
  theme_light() + geom_point() + 
  theme(legend.position = c(0.5,0.8)) +
  scale_color_manual(name='Assessment',values=c('red','darkblue')) +
  labs(y='Reference biomass (in kt)',x ='Year') +
  expand_limits(y=0)
  
@

\cleardoublepage

\subsection{Setting $H_{lim}$ and $H_{pa}$}
According to the ICES guidelines, the precautionary reference points are set by simulating the stock using the stock-recruitment relationship described in section \ref{subsec:SSBR}, based on a wide range of harvest rates, (see eq. \ref{eq:mp}), 
ranging from 0 to 1 and setting $H_{lim}$ as the $H$ that, in equilibrium, gives a 50\% probability of SSB $> B_{lim}$ without assessment error, described in eq. \ref{eq:asserr}. 
From this $F_{lim}$ is set as the equilibrium fishing mortality when $H_{lim}$ is applied. $H_{pa}$ is then set as the harvest rate that would lead to the equilibrium fishing mortality of $F_{pa}$. $F_{pa}$ is defined as the $F_{lim}/e^{1.645\sigma}$ where $\sigma$ is the CV of the estimated fishing mortality in the assessment year. 

The simulation predicted the stock status was 
projected forward 300 years. For each bootstrap model estimate the stock
status was projected 10 times, resulting in a total of 1000 samples. 
The spawning stock biomass was calculated based on model output after 2060.
This is done to ensure that the stock had reached an equilibrium
under the new fishing mortality regime. 

The results from the long term simulations are shown in the top panels of fig. \ref{fig:fmsy}; the value of H, $H_{lim}$, resulting in 50\% long--term probability of SSB $>B_{lim}$ was estimated at 0.56 (an equivalent $F$ of 0.70). As the CV of $F$ in 2016 is 0.33, $F_{pa}$ is estimated as 0.71/1.72 = 0.41. The equivalent harvest rate is then $H_{pa}=0.35$. 


\subsection{Maximum sustainable yield}
An additional simulation experiment where, in addition to recruitment and bootstrap variations, assessment error was added the harvest rate that would lead to the maximum sustainable yield, $H_{msy}$, was estimated. From the simulation annual total landings $c_y$ were calculated after 2060. Average annual landings and
90\% quantiles were used to determine the yield by $H$. Figure
\ref{fig:ssbfor} shows the evolution of catches, SSB and fishing mortality for select values of $H$ are shown. The equilibrium yield curve is shown in figure
\ref{fig:fmsy}, where the maximum average yield, under the recruitment
assumptions, is 7.85 thousand tons with a 95\% interval of for the yield 3.64 and
15.00 thousand tons. Table \ref{tbl:prognres} shows the equilibrium results by harvest rate for select statistics.

$H_{msy}$ is estimated to be 0.24. The
evolution of the spawning stock biomass is shown in figure
\ref{fig:ssbfor}. Equilibrium spawning stock biomass is shown in
figure \ref{fig:fmsy}. The spawning stock biomass obtained at $H_{msy}$ is
estimated at 31.20 thousand tons at $H=0.24$ with an upper quantile
of 58.16 thousand tons and lower quantile of 14.32 thousand tons. 

In-line with ICES technical guidelines the MSY $B_{trigger}$ is set as $B_{pa}$, as the stock 
has not been managed according to $F_{msy}$, or equivalents thereof, for more than 5 years. 

 \begin{figure}
<<yield,echo=FALSE,results='asis',fig.width=10, fig.height=10,cache=TRUE,warning=FALSE,message=FALSE>>=
bpa <- 
  fit$res.by.year %>% 
  filter(grepl('mat',stock)) %>% 
  ungroup() %>% 
  filter(total.biomass==min(total.biomass)) %>% 
  transmute(total.biomass=total.biomass/1e6) %>% 
  unlist()

blim <- bpa/1.4
bpa <- blim*1.4
Hmsy <- 
  res2 %>% 
  filter(mlnd==max(mlnd)) %>% 
  select(rate,mF)

Hlim <- 
  res20 %>% 
  filter(mssb < blim) %>% 
  head(1) %>% 
  bind_rows(  res20 %>% 
                filter(mssb >= blim) %>% 
                tail(1)) %>%
  mutate(rate=as.numeric(rate)) %>% 
  summarise(rate = rate[2]*(blim-mssb[1])/abs(mssb[1]-mssb[2]) + rate[1]*(mssb[2]-blim)/abs(mssb[1]-mssb[2]),
            mF = mF[2]*(blim-mssb[1])/abs(mssb[1]-mssb[2]) + mF[1]*(mssb[2]-blim)/abs(mssb[1]-mssb[2]))

upper <- Hlim$mF/exp(1.645*0.33)
Hpa <- 
  res20 %>% 
  filter(mF < upper & mF > Hmsy$mF & rate < 0.7) %>% 
  tail(1) %>% 
  bind_rows(  res20 %>% 
                filter(mF >= upper & rate < 0.7) %>% 
                head(1)) %>%
  mutate(rate=as.numeric(rate)) %>% 
  summarise(rate = rate[2]*(upper-mF[1])/abs(mF[1]-mF[2]) + rate[1]*(mF[2]-upper)/abs(mF[1]-mF[2]),
            mF = upper)


yield.plot <- 
  res20 %>% 
  bind_rows(res2,.id='meth') %>% 
  #filter(!(rate %in%c(0.46,0.52))) %>% 
  ggplot(aes(as.numeric(rate),mlnd,group=1)) + 
#  geom_ribbon(aes(ymin=llnd,ymax=ulnd),fill='gold') + 
  geom_ribbon(aes(ymin=mlndq5,ymax=mlndq95),fill='gold',alpha=0.5) + 
  geom_line() +
  #xlim(c(0.01,1)) +
  geom_vline(xintercept = Hmsy$rate %>% as.numeric())+
  geom_vline(xintercept = Hpa$rate, lty=2) +
  geom_vline(xintercept = Hlim$rate, col='red')+
  theme_light() + 
  labs(x='Harvest rate (H)', y='',title='Avg. yield (in kt)') +
  scale_x_continuous(breaks = seq(0,0.5,by=0.1)) + 
  xlim(c(0,0.7)) + 
  facet_wrap(~meth,ncol=1) +
  theme(strip.background = element_blank(),strip.text=element_blank())
ssbmsy <- 
  res20 %>% 
  bind_rows(res2,.id='meth') %>% 
  #filter(!(rate %in%c(0.46,0.52))) %>% 
  ggplot(aes(as.numeric(rate),mssb,group=1)) +
  geom_hline(yintercept =blim,col='red') +
#  geom_ribbon(aes(ymin=lssb,ymax=ussb),fill='gold') + 
  geom_ribbon(aes(ymin=mssbq5,ymax=mssbq95),fill='gold',alpha=0.5) +
  geom_line() +
  #ylim(c(0,)) +
  geom_vline(xintercept = Hmsy$rate %>% as.numeric())+
  geom_vline(xintercept = Hpa$rate, lty=2) +
  geom_vline(xintercept = Hlim$rate, col='red')+
  theme_light() + 
  labs(x='Harvest rate (H)', y='',title='Avg. SSB (in kt)')+
  scale_x_continuous(breaks = seq(0,1,by=0.1)) +
  xlim(c(0,0.7)) + 
  facet_wrap(~meth,ncol=1)  +
  theme(strip.background = element_blank(),strip.text=element_blank())
  
gridExtra::grid.arrange(yield.plot,ssbmsy,ncol=2)
@

  \caption{Ling in 5a. Equilibrium catch (left) and SSB (right) curves as a function of $H$. Top panels show the results with process error while the bottom panels have furter added assessment uncertainty.  The black solid curves indicate the median projected catch and SSB and the shaded yellow region the 5\% -- 95\% percentiles. Vertical lines indicate $H_{lim}$ (red), $H_{pa}$ (dashed) and $H_{msy}$. The horizontal red line indicates $B_{lim}$.}\label{fig:fmsy}
\end{figure}




\begin{figure}
<<echo=FALSE,results='asis',fig.width=10, fig.height=15,cache=TRUE,warning=FALSE,message=FALSE>>=
rates <- c(0.18,0.2,0.22,0.24,0.3)

ssb_progn.plot <- 
res_by_year %>% 
#  bind_rows(.id='rate') %>% 
  filter(rate %in% rates,year < 2050) %>% 
  select(c(year,rate,matches("ssb"))) %>% 
  ggplot(aes(year,mssb/1e6)) + 
  geom_ribbon(aes(ymin=lssb/1e6,ymax=ussb/1e6),fill='gold',alpha=0.5) + 
  geom_ribbon(aes(ymin=llssb/1e6,ymax=uussb/1e6),fill='gold',alpha=0.5) + 
  geom_line() + 
  geom_line(aes(y=ssb6/1e6),lty=2) +
  geom_line(aes(y=ssb542/1e6),lty=3) +
  geom_line(aes(y=ssb931/1e6),lty=4) +
  geom_vline(xintercept = 2017,lty=2) +
  facet_wrap(~rate,ncol=1) +
  theme_light() + 
  labs(title='SSB (in kt)',x='Year',y='') +
  geom_hline(yintercept = bpa,lty=2) +
  geom_hline(yintercept = blim,col='red')+ 
  expand_limits(y=0)

catch_progn.plot <- 
res_by_year %>% 
#  bind_rows(.id='rate') %>% 
  filter(year>2017,rate %in% rates,year < 2050) %>% 
  select(c(year,rate,matches("lnd"))) %>% 
  bind_rows(fit$res.by.year %>% 
              group_by(year) %>% 
              summarise(mlnd=sum(catch/4)) %>% 
              left_join(expand.grid(year=1982:2016,
                                    rate=as.character(rates))))%>% 
  ggplot(aes(year,4*mlnd/1e6)) + 
  geom_ribbon(aes(ymin=4*llnd/1e6,ymax=4*ulnd/1e6),fill='gold',alpha=0.5) + 
  geom_ribbon(aes(ymin=4*lllnd/1e6,ymax=4*uulnd/1e6),fill='gold',alpha=0.5) + 
  geom_line() + 
  geom_line(aes(y=lnd6/1e6),lty=2) +
  geom_line(aes(y=lnd542/1e6),lty=3) +
  geom_line(aes(y=lnd931/1e6),lty=4) +
  geom_vline(xintercept = 2017,lty=2) +
  facet_wrap(~rate,ncol=1) +
  theme_light() + 
  labs(title='Catches (in kt)',x='Year',y='') + 
  expand_limits(y=0)

f_progn.plot <- 
  res_by_year %>% 
  filter(year>2017) %>% 
  bind_rows(bootfit$res.by.year %>% 
              filter(grepl('mat',stock)) %>% 
              group_by(year) %>% 
              dplyr::summarise(mF=mean(F),
                        uuF=quantile(F,0.75),
                        llF=quantile(F,0.25),
                        uF = quantile(F,0.95),
                        lF = quantile(F,0,05)) %>% 
              left_join(expand.grid(year=1982:2016,
                                    rate=as.character(rates))))%>% 
#  bind_rows(.id='rate') %>% 
  filter(rate %in% rates,year < 2050) %>% 
  #select(c(year,rate,)) %>% 
  ggplot(aes(year,mF)) + 
  geom_ribbon(aes(ymin=lF,ymax=uF),fill='gold',alpha=0.5) + 
  geom_ribbon(aes(ymin=llF,ymax=uuF),fill='gold',alpha=0.5) + 
  geom_line() + 
  geom_line(aes(y=F6),lty=2) +
  geom_line(aes(y=F542),lty=3) +
  geom_line(aes(y=F931),lty=4) +
  geom_vline(xintercept = 2017,lty=2) +
  geom_hline(yintercept = Hlim$mF,col='red')+
  geom_hline(yintercept = Hpa$mF,lty=2)+
  facet_wrap(~rate,ncol=1) +
  theme_light() + 
  labs(title='Fishing mortality',x='Year',y='') + 
  expand_limits(y=0)

rec_progn.plot <- 
res_by_year %>% 
  filter(rate %in% rates,year < 2050) %>% 
  select(rate,year,matches('rec')) %>%
  ggplot(aes(year,mrec/1e6)) + 
  geom_ribbon(aes(ymin=lrec/1e6,ymax=urec/1e6),fill='gold',alpha=0.5) + 
  geom_ribbon(aes(ymin=llrec/1e6,ymax=uurec/1e6),fill='gold',alpha=0.5) + 
  geom_line() + 
  geom_line(aes(y=rec6/1e6),lty=2) +
  geom_line(aes(y=rec542/1e6),lty=3) +
  geom_line(aes(y=rec931/1e6),lty=4) +
  geom_vline(xintercept = 2017,lty=2) +
  facet_wrap(~rate,ncol=1) +
  theme_light() + 
  labs(title='Recruitment (in millions)',x='Year',y='') + 
  expand_limits(y=0)

gridExtra::grid.arrange(catch_progn.plot,ssb_progn.plot,f_progn.plot,rec_progn.plot,ncol=4)

@

  \caption{Ling in 5a. Projected catches, spawning stock biomass and fishing mortality for select target harvest rates. Red and black dashed horizontal lines represent the limit and pa reference points respectively for SSB and F. }\label{fig:ssbfor}
\end{figure}


<<Fdist,fig.height=8,fig.width=8,fig.lp='fig:',fig.cap="Ling in 5a. Distribution realised harvest rates as a function target harvest rates",echo=FALSE,warning=FALSE,message=FALSE,cache=TRUE>>=
res_quick %>% 
  filter(year>2060) %>% 
  #filter(rate %in% rates) %>% 
  ggplot(aes(hr)) + geom_histogram(aes(y=..density..)) +
  theme_light() + #xlim(c(0.1,0.45)) + 
  #scale_fill_grey(name='Target harv. rate') +
  #theme(legend.position = c(0.9,0.7)) +
  labs(x='Realised harvest rate',y='Density') + 
  facet_wrap(~rate) +
  theme(strip.background = element_blank(),
        strip.text=element_blank()) +
  geom_label(data=data_frame(rate=rates),
             aes(label=rate), 
             x=-Inf,y=Inf,size=3, 
             vjust = 1.1,hjust=-0.1) +
  xlim(c(0,.75))
@


\begin{table}[!h]
\vspace{1mm}
\caption[]
{Ling in 5a. Equilibrium averages of yield, fishing mortality (F at age $15^+$) spawning stock biomass (SSB),  recruitment and probility that SSB falls below either $B_{pa}$ or $B_{pa}$ at any point in time from forward projections of the stock status of ling. }\label{tbl:prognres}
\vspace{2mm}
\resizebox{\columnwidth}{!}{\centering
\scriptsize
\begin{tabular}{l| r r r r r r}
\toprule
Harvest rate & Eq. yield & F & SSB & Recruitment & $P(\exists y|SSB_y < B_{pa})$ & $P(\exists y|SSB_y < B_{lim})$ \\ \midrule
<<echo=FALSE,results='asis',message=FALSE,warning=FALSE>>=
res2 %>% 
  left_join(res_by_year %>% 
              filter(year>2060) %>% 
              group_by(rate) %>% 
              summarise(mFq5=mean(lF),
                        mFq95=mean(uF),
                        mrecq5=mean(lrec),
                        mrecq95=mean(urec))) %>% 
  transmute(harv.rate=as.numeric(rate),
            yield = sprintf('%.2f (%.2f,%.2f)',mlnd,mlndq5,mlndq95),
            F = sprintf('%.3f (%.3f,%.3f)',mF,mFq5,mFq95),
            ssb = sprintf('%.2f (%.2f,%.2f)',mssb,mssbq5,mssbq95),
            rec = sprintf('%.2f (%.2f,%.2f)',mrec/1e6,mrecq5/1e6,mrecq95/1e6),#) %>% #,
            ppa = sprintf('%.2f',pBpa),
            plim = sprintf('%.2f',pBlim)) %>% 
  filter(harv.rate < 0.6,harv.rate > 0.05) %>% 
  unite(col,matches("."),sep=' & ') %>% 
   (function(x){
     paste(x$col,collapse = '\\\\ \n')
   }) %>% 
   paste0('\\\\') %>% 
   cat() 
@

\bottomrule
\end{tabular}
\par}
\end{table}




\clearpage
\subsection{Proposed target harvest rate}
When considering the candidate harvest rate for ling in 5a on may want to investigate the marginal gain of increasing the harvest rate in terms of equilibrium yields. Even with catch rates as low as 0.13 the equilibrium yields are roughly comparable with that of the $H_{msy}$.  
In addition short term forward projections illustrated in fig. \ref{fig:ssbfor} indicate that for 
harvest rates will have adapted (on average) to their equilibrium catch levels within a decade from now. 
% Second the harvest rates have a non zero chance of exceeding the harvest rate and biomass reference points (as illustrated in fig. \ref{fig:ssbfor} and listed in table \ref{tbl:refpoint}) even at $H_{msy}$, where the probability of SSB going below $B_{lim}$ at any time during the forecast was 0.74, while $H=0.18$ has a probability of 0.05.    

The proposed target havest rate, of 0.18 illustrated in fig. \ref{fig:mp.plot}, is considered safe and precautionary as it is lower than any precautionary reference points listed in the sections above. Furthermore it can be considered consistent with the ICES MSY approach, while lower than the estimated $H_{msy}$ of 0.24, the expected long term yield is less that 2\% lower. The expected 5\% and 95\% percentiles of true harvest rates, when setting catches according 0.18, are 0.12 and 0.28 respectively, as illustrated by figure \ref{fig:Fdist}.



\begin{table}[!h]
\vspace{1mm}
\caption[]
{Ling in 5a. Summary of reference point proposed for ling in 5a. The fishing mortality is relative to ages $15^+$ and harvest rates correspond to the reference biomass of $B_{75cm^+}$. }\label{tbl:refpoint}
\vspace{2mm}
{\centering
\scriptsize
\begin{tabular}{p{2.5cm} l r p{5cm} }
\toprule
Framework & Reference point & Value & Technical basis \\ \midrule
MSY approach & MSY $B_{trigger}$ &  9.93 kt & $B_{pa}$ \\
            & $H_{msy}$ & 0.24 & The harvest rate that maximises the median long-term catch in stochastic simulations with recruitment drawn from a block bootstrap of historical recruitment, with block size 6, scaled according to a hockey stick recruitment function with $B_{lim}$ as defined below.\\
            & $F_{msy}$ & 0.284 & The median fishing mortality when an harvest rate of $H_{msy}$ is applied. \\
%            & $H_{p.05}$ & 0.497 & The harvest rate that has an annual probability of 5\% of SSB < $B_lim$.\\
%            & $F_{p.05}$ & 0.516 &  The median fishing mortality when an harvest rate of $H_{p.05}$ is applied.\\
\hline
Precautionary approach & $B_{lim}$ & 7.09 kt & $B_{pa}/e^{1.645\sigma}$ where $\sigma=0.2$ \\
                      & $B_{pa}$ & 9.93 kt & SSB(1992), corresponding to $B_{loss}$ \\
                      & $H_{lim}$ & 0.56 & $H$ corresponding to 50\% long-term probability of SSB > $B_{lim}$ \\
                      & $F_{lim}$ & 0.70 & F corresponding to $H_{lim}$ \\
                      & $F_{pa}$ &  0.41 & $F_{lim}/e^{1.645\sigma}$ where $\sigma=0.33$\\
                      & $H_{pa}$ & 0.35 & H corresponding to $F_{pa}$ \\
\hline 
Management plan & $H_{mp}$ & 0.18 & $H$ such that $F\leq F_{msy}$, long-term yield is consistent with MSY while leading to high stock biomass \\
             & $B_{trigger}$ & 9.93 kt & Set as $B_{pa}$ as the stock has not been harvested at $F_{msy}$, or equivalents thereof\\ 
\bottomrule
\end{tabular}
\par}
\end{table}

<<mp.plot, fig.height=5,fig.width=10,fig.lp='fig:',fig.cap='Ling in 5a. Graphical presention of the proposed managment rule. The black solid line indicates the harvest rate relative to the >75cm biomass as a function of the SSB',echo=FALSE>>=
Hmp <- 0.18
ggplot(aes(x,y),
       data=data_frame(x=c(0,bpa,bpa*5),y=c(0,Hmp,Hmp))) + 
  geom_path() + 
  expand_limits(y=Hmp*1.5) +
  theme_light() + 
  geom_vline(xintercept = bpa,lty=2) +
  geom_vline(xintercept = blim,col='red') +
  annotate('text',label=sprintf('Btrigger = %.2f',bpa),x=bpa*1.1,y=0.05,angle=90) + 
  labs(y='Harv. rate',x='SSB (in kt)')+
  annotate('text',label=sprintf('Blim = %.2f',blim),x=blim*0.9,y=0.05,angle=90) +
  annotate('text',label=sprintf('Hmp = %.2f',Hmp),x=bpa*2,y=1.05*Hmp)
@


\section{Conclusions}
Overall the gadget model presented here captures the overall trends in
the data, and in spite of minor mis-fits the model is usable for
assessing the stock and to base advice to managers.

In a complicated such as the gadget model that has many parameters and
many data-sets of varying quality it is to be expected that there may
be problems with some parameters and fit to some data-sets.

The main problem the model has, as would any other models,
is the rapid increase in the survey indices in recent years and the
large CV of these indices in that period.  This is more a data problem
than a model problem and given the decrease in the last 5 years
in the smaller length
groups in the tuning series this may resolve it self in coming years. 

Most parameters are well defined except for the ones relating to
gillnets, the reason being the limited data for this fleet.  Catches
from gillnets have been decreasing in recent years.  For example
catches in gillnets were around one third to half of ling catches in
2000 to 2001 but have now decreased to around 7\% of Icelandic
commercial catches in 2016.  This is the result of changes in fleet
dynamics and regulations.  It may even be justifiable to omit the
gillnet fleet in the future from the model.  Anyway the problems with
the gillnet fleet in the model are of minor importance in the current
fishery. 

Another parameter that is poorly defined is the $\sigma_0$ that
is the standard deviation of recruitment length.  This is also of minor
importance as ling does not enter the fishery until the age 5 and 6,
but by then the $\beta$-parameter has created a standard
deviation in the length at age.






\cleardoublepage

\bibliography{library}

\cleardoublepage
\section{Annex}
\subsection{Initial parameter values and boundaries}\label{Ann:Par.base}
{\tiny
\verbatiminput{../08-back2l50/params.in}
\par}

\cleardoublepage
\subsection{Settings of optimisation routines}\label{Ann:Optinfo}
{
\verbatiminput{../00-setup/optinfofile}
\par}




\cleardoublepage
\section{Explaining changes in recruitment}\label{sec:recdisc}
\subsection{Temporal changes in recruitment}
The relationship between the estimated spawning stock and recruitment
is shown in figure \ref{fig:ssbrec}. In the Gadget model for Ling in
5a the annual recruitment, during the observation period, is estimated
as a fixed effect without any consideration of the size of the
spawning stock biomass. This means that no formal stock recruit
relationship is defined. This is allowed by information on past
recruitment such as age and length distributions and survey
indices. It can be observed that for time periods where less data is
available on recruitment, such as recruitment in the most recent
years, have higher levels of uncertainty.


Ling in 5a has experienced an unusual spike in recruitment, when
compared to years prior to 2003. There could be two different reasons
for this observation, impaired recruitment due to over exploitation or
environmental changes.  In the following sub-subsections these theories
will be explored.


\subsection{Impaired recruitment}
Catches in 1950 to the mid
  seventies were around 10 thous. tonnes annually but in the eighties
  and nineties fell to 3 to 4 thous tonnes.  After 2005 catches
  increased again to similar levels as before (10 thous tonnes).  So
  the decrease in recruitment would be the result of
  over-exploitation.  This may certainly be the case
when considering historical fishing mortality (Figure
\ref{fig:catch}).  However there is no information available on
fishing mortality or harvest rates for ling in 5a before 1982, when
catch levels were high for over 25 years.
\subsection{Environmental factors}
Since 2000 bottom temperature has been increasing on the western and
north-western part of the shelf (Figure \ref{fig:temp}).  This
increase in temperature has opened up areas for species that are on
the northern fringe of their distributional range as can be seen from
changes in indices of several of such species such as ling, tusk,
anglerfish and lemon sole (Figure \ref{fig:warmInd}).

There does seem to be a strong correlation between the increase in the
southern species in figure \ref{fig:warmInd} and the increase in
temperature in figure \ref{fig:temp}.1, \ref{fig:temp}.2 and
\ref{fig:temp}.3.  However in \ref{fig:temp}.4 wich is the longest
time series going back to 1945 and comes from the northern part of the
shelf there is no increase in temperature around 2000.  However it can
be seen that there was a significant drop in temperature on the
northern part of the shelf in the early seventies.  This strongly
suggests that the waters around Iceland in the fifties and sixties
ware considerably warmer than in the seventies to nineties.  It is
therefore not unlikely that the changes in catches observed in figure
\ref{fig:catch} are to a large extend driven by changes in the environment.

The increase in the biomass shown in figure \ref{fig:warmInd}
coinsided with a rapid increase in recruitment indices of these
species as can be seen in figure \ref{fig:JuvInd}.  The striking thing
from figure  \ref{fig:JuvInd} is that for three of the four species
the juvenile indices have decreased rapidly from a recod high in
2005-2009 to very low levels.  This may indicate that the increase in
temperature may not on its own be sufficient to ensure continued high
recruitment.  There could be other enviriomental factors at play, such
as species interactions, predation on juveniles or even density
dependent factors.  However there is no guarantee for a continued good
recruitment in coming years.

\begin{figure}
  \includegraphics[width=0.9\linewidth]{catches1950F}
  \caption{Ling in Va: Catches in 1950 to 2012 and estimates of
    fishing mortality from the Gadget model from 1982 to 2012.}\label{fig:catch}
\end{figure}

\begin{figure}
  \includegraphics[width=1.0\linewidth]{Temp3}
  \caption{Changes in bottom temperature in selected areas around Iceland by year.}\label{fig:temp}
\end{figure}


\begin{figure}
  \includegraphics[width=1.0\linewidth]{WarmBioInd}
  \caption{Changes in biomass indices for several southern species in
    5a from the Icelandic spring survey.}\label{fig:warmInd}
\end{figure}


\begin{figure}
  \includegraphics[width=1.0\linewidth]{WarmJuvInd}
  \caption{Changes in juvenile abundance indices for several southern species in
    5a from the Icelandic spring survey.}\label{fig:JuvInd}
\end{figure}


\subsection{Conclusions}
Given the data presented above it seems plausible that the sudden
increase in ling and other southern species on the Icelandic shelf is
driven mainly by changes in the environment and anecdotal evidence
indicates that the decline in catches in the seventies may be
similarly driven by decrease in temperature on the Icelandic shelf.


\cleardoublepage


\end{document}
