
gadgetlikelihood('likelihood',gd$dir,missingOkay = TRUE) %>% 
  ## Write a penalty component to the likelihood file
  gadget_update("penalty",
                name = "bounds",
                weight = "10",
                data = data.frame(
                  switch = c("default"),
                  power = c(2),
                  upperW=10000,
                  lowerW=10000,
                  stringsAsFactors = FALSE)) %>%
  gadget_update("understocking",
                name = "understocking",
                weight = "10") %>%
                    
  gadget_update("catchdistribution",
                name = "ldist.spr.bias",
                weight = 1,
                data = ldist.spr.bias,
                fleetnames = "biasspr",
                stocknames = stock_names) %>%
  gadget_update("catchdistribution",
                name = "alk.spr.bias",
                weight = 1,
                data = alk.spr.bias,
                fleetnames = "biasspr",
                stocknames = stock_names) %>%
  gadget_update("catchdistribution",
                name = "adist.spr.com1",
                weight = 1,
                aggregationlevel = 1,
                data = adist.spr.com %>% filter(year %in% 1974:1994),
                fleetnames = "comspr",
                stocknames = stock_names) %>%
  gadget_update("catchdistribution",
                name = "adist.spr.com2",
                weight = 1,
                aggregationlevel = 0,
                data = adist.spr.com %>% filter(year %in% 1995:2018),
                fleetnames = "comspr",
                stocknames = stock_names) %>%

      gadget_update("catchstatistics",
                name = "waa.spr.com",
                weight = 1,
                data_function = "weightgivenstddev",
                data = waa2pl.spr.com,# %>% select(-stddev),
                fleetnames = "comspr",
                stocknames = stock_names[2]) %>%

  gadget_update("surveyindices",
                name = "si0.spr.rct3",
                weight = 1,
                data = si0.spr.rct3,
                sitype = "ages",
                biomass = 0,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                stocknames = stock_names) %>%
  gadget_update("surveyindices",
                name = "si1.spr.bias",
                weight = 1,
                data = si1.spr.bias,
                sitype = "ages",
                biomass = 0,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                stocknames = stock_names) %>%
  gadget_update("surveyindices",
                name = "si2.spr.bias",
                weight = 1,
                data = si2.spr.bias,
                sitype = "ages",
                biomass = 0,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                stocknames = stock_names) %>%
  gadget_update("surveyindices",
                name = "si3.spr.bias",
                weight = 1,
                data = si3.spr.bias,
                sitype = "ages",
                biomass = 0,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                stocknames = stock_names) %>%
  gadget_update("surveyindices",
                name = "si4.spr.bias",
                weight = 1,
                data = si4.spr.bias,
                sitype = "ages",
                biomass = 0,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                stocknames = stock_names) %>%
  gadget_update("surveyindices",
                name = "si5.spr.bias",
                weight = 1,
                data = si5.spr.bias,
                sitype = "ages",
                biomass = 0,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                stocknames = stock_names) %>%
  gadget_update("surveyindices",
                name = "si6.spr.bias",
                weight = 1,
                data = si6.spr.bias,
                sitype = "ages",
                biomass = 0,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                stocknames = stock_names) %>%
  gadget_update("surveyindices",
                name = "si7.spr.bias",
                weight = 1,
                data = si7.spr.bias,
                sitype = "ages",
                biomass = 0,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                stocknames = stock_names) %>%
  gadget_update("surveyindices",
                name = "si8.spr.bias",
                weight = 1,
                data = si8.spr.bias,
                sitype = "ages",
                biomass = 0,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                stocknames = stock_names) %>%
                    
  write.gadget.file(gd$dir)
