
gadgetlikelihood('likelihood',gd$dir,missingOkay = TRUE) %>% 
  ## Write a penalty component to the likelihood file
  gadget_update("penalty",
                name = "bounds",
                weight = "10",
                data = data.frame(
                  switch = c("default"),
                  power = c(2),
                  upperW=10000,
                  lowerW=10000,
                  stringsAsFactors = FALSE)) %>%
  gadget_update("understocking",
                name = "understocking",
                weight = "10") %>% #
  ## gadget_update("catchdistribution",
  ##               name = "adist.ven.com",
  ##               weight = 1,
  ##               data = adist.ven.com,
  ##               fleetnames = c("comven1","comven2"),
  ##               stocknames = stock_names) %>%
  gadget_update("catchdistribution",
                name = "ldist.ven.com",
                weight = 1,
                data = ldist.ven.com,
                fleetnames = c("comven1","comven2"),
                stocknames = stock_names) %>%
  gadget_update("catchdistribution",
                name = "alk.ven.com",
                weight = 1,
                data = alk.ven.com,
                fleetnames = c("comven1","comven2"),
                stocknames = stock_names) %>%
  gadget_update("catchdistribution",
                name = "adist.ven.seal",
                weight = 1,
                aggregationlevel = 1,
                data = adist.ven.seal,
                fleetnames = c("sealven"),
                stocknames = stock_names) %>%
  ## gadget_update("catchdistribution",
  ##               name = "adist.ven.cpue",
  ##               weight = 1,
  ##               data = adist.ven.cpue,
  ##               fleetnames = c("reffleet"),
                ## stocknames = stock_names) %>%
  ## gadget_update("catchdistribution",
  ##               name = "adist.ven.aco",
  ##               weight = 1,
  ##               data = adist.ven.aco,
  ##               fleetnames = c("aco"),
  ##               stocknames = stock_names) %>%
  gadget_update("catchdistribution",
                name = "ldist.ven.aco",
                weight = 1,
                data = ldist.ven.aco,
                fleetnames = "aco",
                stocknames = stock_names) %>%
  gadget_update("catchdistribution",
                name = "alk.ven.aco",
                weight = 1,
                data = alk.ven.aco,
                fleetnames = "aco",
                stocknames = stock_names) %>%
                    
  gadget_update("surveyindices",
                name = "si.ven.cpue",
                weight = 1,
                data = si.ven.cpue,
                sitype = "fleets", # to account for selectivity
                biomass = 1,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                fleetnames = c("comven1","comven2"),
                stocknames = stock_names) %>%
                    
  ## gadget_update("surveyindices",
  ##               name = "si.ven.reff",
  ##               weight = 1,
  ##               data = si.ven.reff,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'fixedslopeloglinearfit',
  ##               slope = 1,
  ##               stocknames = stock_names) %>%
  ## gadget_update("surveyindices",
  ##               name = "si0.ven.reff",
  ##               weight = 1,
  ##               data = si.ven.reff0,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'fixedslopeloglinearfit',
  ##               slope = 1,
  ##               stocknames = stock_names) %>%
  ## gadget_update("surveyindices",
  ##               name = "si1.ven.reff",
  ##               weight = 1,
  ##               data = si.ven.reff1,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'fixedslopeloglinearfit',
  ##               slope = 1,
  ##               stocknames = stock_names) %>%
  ## gadget_update("surveyindices",
  ##               name = "si2.ven.reff",
  ##               weight = 1,
  ##               data = si.ven.reff2,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'fixedslopeloglinearfit',
  ##               slope = 1,
  ##               stocknames = stock_names[2]) %>%
  ## gadget_update("surveyindices",
  ##               name = "si3.ven.reff",
  ##               weight = 1,
  ##               data = si.ven.reff3,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'fixedslopeloglinearfit',
  ##               slope = 1,
  ##               stocknames = stock_names[2]) %>%
  ## gadget_update("surveyindices",
  ##               name = "si4.ven.reff",
  ##               weight = 1,
  ##               data = si.ven.reff4,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'fixedslopeloglinearfit',
  ##               slope = 1,
  ##               stocknames = stock_names[2]) %>%
  ## gadget_update("surveyindices",
  ##               name = "si5.ven.reff",
  ##               weight = 1,
  ##               data = si.ven.reff5,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'fixedslopeloglinearfit',
  ##               slope = 1,
  ##               stocknames = stock_names[2]) %>%

  gadget_update("surveyindices",
                name = "si.ven.aco",
                weight = 1,
                data = si.ven.aco,
                sitype = "ages",
                biomass = 0,
                fittype = 'fixedslopeloglinearfit',
                slope = 1,
                stocknames = stock_names) %>%
  ## gadget_update("surveyindices",
  ##               name = "si0.ven.aco",
  ##               weight = 1,
  ##               data = si.ven.aco0,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'loglinearfit',
  ##               stocknames = stock_names) %>%
  ## gadget_update("surveyindices",
  ##               name = "si1.ven.aco",
  ##               weight = 1,
  ##               data = si.ven.aco1,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'loglinearfit',
  ##               stocknames = stock_names) %>%
  ## gadget_update("surveyindices",
  ##               name = "si2.ven.aco",
  ##               weight = 1,
  ##               data = si.ven.aco2,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'loglinearfit',
  ##               stocknames = stock_names[2]) %>%
  ## gadget_update("surveyindices",
  ##               name = "si3.ven.aco",
  ##               weight = 1,
  ##               data = si.ven.aco3,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'loglinearfit',
  ##               stocknames = stock_names[2]) %>%
  ## gadget_update("surveyindices",
  ##               name = "si4.ven.aco",
  ##               weight = 1,
  ##               data = si.ven.aco4,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'loglinearfit',
  ##               stocknames = stock_names[2]) %>%
  ## gadget_update("surveyindices",
  ##               name = "si5.ven.aco",
  ##               weight = 1,
  ##               data = si.ven.aco5,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'loglinearfit',
  ##               stocknames = stock_names[2]) %>%
  ## gadget_update("surveyindices",
  ##               name = "si6.ven.aco",
  ##               weight = 1,
  ##               data = si.ven.aco6,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'loglinearfit',
  ##               stocknames = stock_names[2]) %>%
  ## gadget_update("surveyindices",
  ##               name = "si7.ven.aco",
  ##               weight = 1,
  ##               data = si.ven.aco7,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'loglinearfit',
  ##               stocknames = stock_names[2]) %>%
  ## gadget_update("surveyindices",
  ##               name = "si8.ven.aco",
  ##               weight = 1,
  ##               data = si.ven.aco8,
  ##               sitype = "ages",
  ##               biomass = 0,
  ##               fittype = 'loglinearfit',
  ##               stocknames = stock_names[2]) %>%

  gadget_update("stockdistribution",
                name = "mat.ven.com",
                weight = 1,
                data = mat.ven.com,
                fleetnames = c("comven1","comven2"),
                stocknames = stock_names) %>%
  gadget_update("stockdistribution",
                name = "mat.ven.aco",
                weight = 1,
                data = mat.ven.aco,
                fleetnames = "aco",
                stocknames = stock_names) %>%
                    
  write.gadget.file(gd$dir)
